### PR TITLE
🧪 TESTS: convert `AiidaTestCase` -> pytest

### PR DESCRIPTION
**Pull request by chrisjsewell**
Conversion process:

- `unittest2pytest -n -w path/to/file` (see https://github.com/pytest-dev/unittest2pytest)
- add `# pylint: disable=no-self-use`
- replace `AiidaTestCase` with `@pytest.mark.usefixtures('aiida_profile_clean_class')` (I would say this is not recommended unless there are particular performance reasons, since every test should be independent), `@pytest.mark.usefixtures('aiida_profile_clean')`, or using an autouse fixture (see below)
  - replace `def setUp(self):` with `def setup_method(self):` or an autouse fixture
- remove `from aiida.backends.testbase import AiidaTestCase`
- change `@unittest.skip` -> `@pytest.mark.skip`, `@unittest.skipIf` -> `@pytest.mark.skipif`

The were some issues where`assertAlmostEquals` had been used for strange cases, related to this I also added an `__abs__` method to `NumericType`

Annoyingly there are some limitations of using classes with pytest, one being that a class `usefixtures` decorator is called AFTER a `setup_class` method (see
https://stackoverflow.com/questions/31484419/pytest-setup-class-after-fixture-initialization_) so any nodes created in `setup_class` will be wiped from the database by `aiida_profile_clean_class`.
Also class methods do not accept fixtures.
This makes it difficult to do an exact 1-to-1 replacement of any `setUpClass` -> `setup_class` methods used, and also replace the use of `self.computer`

edit: https://docs.pytest.org/en/latest/how-to/unittest.html#using-autouse-fixtures-and-accessing-other-fixtures allows for using fixtures per test, and so can solve the use of `self.computer` etc e.g.

```python
# pylint: disable=attribute-defined-outside-init,no-self-use,unused-argument

class MyTestClass:
    @pytest.fixture(autouse=True)
    def init_db(self, aiida_profile_clean, backend, aiida_localhost):
        self.backend = backend
        self.computer = aiida_localhost
    def test_something(self):
        self.computer
```

or if you don't need any instance attributes:

```python
@pytest.mark.usefixtures('aiida_profile_clean')
class MyTestClass:
   def test_something(self):
```

### CODE REVIEW

**Comment by chrisjsewell** [comment]
cc @ltalirz, this should pass all tests for the files I have changed (plenty more to do), so if you want to have a look do a quick "pre-review" for any issues, before I apply this to any more files?

**Review by ltalirz — COMMENTED** [review]
thanks @chrisjsewell - looks good to me, no obvious issues come to mind.

when transforming more tests you may run into the fact that the AiidaTestCase is a bit more rigorous in cleaning not only the db but also resetting various caches (see the `clean_db` method).
These may need to be ported over to the `reset_db` method of the ProfileManager

**Comment by ltalirz** [comment]
I guess this can then also be closed?

**Comment by chrisjsewell** [comment]
> I guess this can then also be closed?

Yep 👍, superseded by #5372

Perhaps some of the tips for writing tests, in the initial comment, should be copied somewhere?

**Pull request closed without merging**
