### PR TITLE
🐛 FIX: migration for adding `core` prefix

### LINKED ISSUE #5266: Migration: `core.` prefix is not added correctly for some data types
### Describe the bug

During testing, I noticed that after the migration loading any `KpointsData` raised a deprecation warning:

```
In [1]: k = load_node(770)
/home/aiida/envs/aiida-test/code/aiida-core/aiida/plugins/entry_point.py:308: AiidaDeprecationWarning: The entry point `array.kpoints` is deprecated. Please replace it with `core.array.kpoints`.
  warn(
```

This was not an issue for e.g. `StructureData`. It seems that there are some typo's in the SQL commands for the `core.` prefix migration, e.g.:

https://github.com/aiidateam/aiida-core/blob/29915bdb3314dc37171bd264a792b4bbfa6de167/aiida/backends/sqlalchemy/migrations/versions/34a831f4286d_entry_point_core_prefix.py#L27

Note how `KpointData` is missing an `s`. Another faulty migration is the `RemoteStashFolderData` one:

https://github.com/aiidateam/aiida-core/blob/29915bdb3314dc37171bd264a792b4bbfa6de167/aiida/backends/sqlalchemy/migrations/versions/34a831f4286d_entry_point_core_prefix.py#L44

I haven't noticed any others so far. @sphuber if I remember correctly, these migration files are generated via a script. Can we simply correct the SQL commands in the current files or should we regenerate them?

### Steps to reproduce

1. Migrate a database from v1.6.5 to the current `develop` branch.
2. Try loading e.g. any `KpointsData`

### PR DESCRIPTION
**Pull request by mbercx**
Fixes #5266 

Some of the SQL commands for the migration that adds the `core` prefix
have typo's in them. This meant that the entry points weren't migrated
correctly.

Here we fix the typo's for `KpointsData` and `RemoteStashFolderData`.

### CODE REVIEW

**Comment by mbercx** [comment]
@sphuber I checked the database I migrated for some other data type offenders, but so far `KpointsData` and `RemoteStashFolderData` were the only ones from `aiida-core` that were missing the `core` prefix:

```
aiida-test=> select distinct node_type from db_dbnode where node_type not like '%core%';
                     node_type                      
----------------------------------------------------
 data.array.kpoints.KpointsData.
 data.pseudo.upf.UpfData.
 data.remote.stash.folder.RemoteStashFolderData.
 process.calculation.calcfunction.CalcFunctionNode.
 process.calculation.calcjob.CalcJobNode.
 process.workflow.workchain.WorkChainNode.
(6 rows)
```

**Comment by unkcpz** [comment]
I just make the migrate and import, since the archive I have is a `tar` file which leads to that the migration being very slow.  Just solve it with the help of Chris. 

@mbercx How do you find this kind of typos? 
I have no clear idea what should I test. There is no error when I migrate and import the archive. Only when I check a process node, there are deprecate warning "AiidaDeprecationWarning: The entry point `array.kpoints` is deprecated. Please replace it with `core.array.kpoints`." which I think are correct behavior. 
Please tell me what I need to look at in more detail.

**Comment by sphuber** [comment]
I also gave it a look and it seems ok to me now. But not sure how much my opinion is still worth having caused this :)

**Review by sphuber — APPROVED** [review]
Thanks for fixing my incompetence @mbercx

**Comment by mbercx** [comment]
@sphuber had to update the archive used to test the migrations, tests are passing now! Feel free to merge after review

**Review by sphuber — APPROVED** [review]
Good stuff, thanks

**Pull request merged**
