### PR TITLE
Add support for Docker images to use as `Code` for `CalcJob`s

### LINKED ISSUE #5818: `ContainerizedCode`: Add support for running codes within Docker containers
Currently the `ContainerizedCode` implementation supports certain container technologies, such as Singularity and Sarus. These are technologies that are often employed by high-performance computing centers, but users will typically not be familiar with running this on their workstations. Docker is a more common option, but is not yet supported. Providing support for Docker would make a huge step in increasing the provenance of AiiDA even more, as now the compute environment of `CalcJob`s is not stored at all.

At least for the most minimal use case, one single change should be sufficient to enable Docker support. The way a command within a docker container should be invoked is as follows:
```bash
"docker" "run" "-i" "-v" "$PWD:/workdir:rw" "-w" "/workdir" "{image_name}" "sh" "-c" "{executable} {arguments} > "'"'"{stdout}"'"'" "
```
The most important part is that the executable, command line arguments and the redirection of file streams (stdin, stderr and stdout) should all be wrapped in double quotes to form a single argument to the `sh -c` invocation.

It is not possible to do this with the current API provided by `aiida-core`. A solution had already been proposed by @unkcpz in #5507 by adding another attribute to the `ContainerizedCode` called `escape_exec_line` which would be `False` by default. When set to `True` it would instruct `Scheduler` plugins to wrap all arguments after the computer command line arguments in double quotes.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5818 

The `ContainerizedCode` is currently not quite compatible with Docker's containerization technology. The reason is that the executable, including all of its command line arguments and the file descriptor redirections need to be part of a single quoted string, passed to the `bash -c` command that is run inside the container.

For example, to run `pw.x` the submit line needs to look like:

    docker run -i {image_name} sh -c "pw.x -input input.in"

To enable this, a new attribute is added to the `JobTemplateCodeInfo` dataclass. This instructs the `Scheduler` to wrap the executable and all its arguments in quotes. The `AbstractCode` has a new attribute with the same name that is `False` by default to keep backwards-compatibility but which can be set to `True` to enable compatibility with Docker.

The attribute has an associated getter and setter, which is added to the `AbstractCode` and not the `ContainerizedCode` because the `Scheduler` plugin will attempt to retrieve this attribute for all code types. If the properties would be added to `ContainerizedCode`, the scheduler plugin would except with an `AttributeError`.

### CODE REVIEW

**Comment by unkcpz** [comment]
Hi @sphuber, is this ready? I am happy to review it.

**Comment by sphuber** [comment]
> Hi @sphuber, is this ready? I am happy to review it.

Yes, I think this is ready and is working. But maybe we should still have a more high-level discussion with people to see if this is the right approach. I don't see another one that would allow to add support for Docker without changing things a lot, so I would be tempted to say this approach is ok as it is not disruptive and adds important functionality, albeit that it complicates the concept of the `Computer/Code` concepts even further.

**Review by unkcpz — CHANGES_REQUESTED** [review]
@sphuber Thanks! 
I have two minor requests. 1. Could you replace the containerized code test at https://github.com/aiidateam/aiida-core/blob/76b6ba512286b73f89e619c2e5f9e366ef20053e/tests/engine/processes/calcjobs/test_calc_job.py#L243-L247 with the docker? I'd curious to see the real effect of the wrap.
2. the name `wrap_cmdline_params` at first glimpse seems in the same type with `cmdline_params` and `prepend_cmdline_params`, maybe `wrap_cmdline_params_up` or `wrap_cmdline_params_in_double_quotes` to distinguish with others? This request is only personal preference, you can keep it as it is.

**Comment by sphuber** [comment]
> Could you replace the containerized code test at ... with the docker? I'd curious to see the real effect of the wrap.

I have added a test (instead of replacing) in the latest commit.

> the name wrap_cmdline_params at first glimpse seems in the same type with

I will ping other developers in Slack to see if they want to have a look at the naming.

**Comment by unkcpz** [comment]
@sphuber Thanks for adding the test. The conflict comes from the newly merged PR where I removed duplicated `use_double_quotes`. I resolve it with a commit, hope you don't mind.

**Review by unkcpz — APPROVED** [review]
It is all good from my side. I also give it a try for the oncvpsp code. I find it is very helpful if the image's default user is root and using the option `-u $(id -u ${USER}):$(id -g ${USER}) ` for the docker run, the output file belongs to user and can be deleted by the user with `cleanworkdir`. But for me, it is just a bonus set as a docker user, feel free to add it to doc or I think it is ready to be merged.

**Pull request merged**
