### PR TITLE
🔀 MERGE: Refactor/rename storage modules

### PR DESCRIPTION
**Pull request by chrisjsewell**
This is a follow-up to #5330

Previously, I believe this may not have been possible,
due to django loading the database connection on install.
But now, it makes sense to consolidate the full `psql_dos`
storage backend implementation in a central place.
This also leaves `aiida/orm` fully storage backend agnostic.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
P.S. obviously, the next thing will be to rename `sqlalchemy` to `psql_dos`

**Comment by chrisjsewell** [comment]
Note, the docs require #4204 to fix

**Comment by sphuber** [comment]
While we are in the process of renaming things as they should be named, should `aiida/backends` become `aiida/storage`?

**Comment by chrisjsewell** [comment]
> While we are in the process of renaming things as they should be named, should `aiida/backends` become `aiida/storage`?

Yeh was thinking that, can do it in another commit here?

Then, there are other uses of "backend":

- should the `aiida/orm/implementation/backends.py::Backend` class be re-named?
- you have things like `Entity.backend`, but that's a bit more difficult to change

**Comment by sphuber** [comment]
> Yeh was thinking that, can do it in another commit here?

Fine by me to do it in this PR, but not sure if these need to be separate commits. Well, at least the two you have now can really be squashed because it is the same folder being renamed twice in sequence:
1. `aiida.orm.implementation.sqlalchemy` - > `aiida.backends.sqlalchemy.orm`
2. `aiida.backends.sqlalchemy.orm` -> `aiida.backends.psql_dos.orm`

Is really the same as

1.  `aiida.orm.implementation.sqlalchemy` - > `aiida.backends.psql_dos.orm`

The next move of `aiida.backends` -> `aiida.storage` maybe should indeed better be a separate commit, since it involves the renaming of more modules.

> should the aiida/orm/implementation/backends.py::Backend class be re-named?

I don't think the name `backend` is problematic in itself, but for consistency it should probably be `storage_backend/StorageBackend`.

> you have things like Entity.backend, but that's a bit more difficult to change

Why is this more difficult? From a backwards-incompatible perspective? Because if it is that, users are not supposed to be touching this anyway, right?

**Comment by chrisjsewell** [comment]
> Well, at least the two you have now can really be squashed because it is the same folder being renamed twice in sequence
> Is really the same as `aiida.orm.implementation.sqlalchemy - > aiida.backends.psql_dos.orm`

I would not say that is equivalent; it's a movement of some code between modules, then a name change of an entire module.

**Comment by sphuber** [comment]
> it mainly just not particularly descriptive and/or immediately obvious to new users/developers what it means

I meant that I don't think the word "backend" is problematic, however, when it is isolated, it loses meaning. But when combined with a word indicating what it is actually the backend *of*, such as `storage_backend`, then I think it is fine and conveys the correct message.

**Comment by chrisjsewell** [comment]
> But when combined with a word indicating what it is actually the backend ... hen I think it is fine and conveys the correct message.

yep 👍

**Comment by chrisjsewell** [comment]
Ok I'm going to be merging this soon, since I have other PRs to go on top

**Review by sphuber — APPROVED** [review]

**Pull request merged**
