### PR TITLE
🔧 MAINTAIN: Add `verdi devel run-sql`

### PR DESCRIPTION
**Pull request by chrisjsewell**
For quickly running raw SQL commands on the database

### CODE REVIEW

**Comment by chrisjsewell** [comment]
So I can quickly do things like inspecting the schema:

```
$ verdi devel run-sql "SELECT * FROM information_schema.tables WHERE table_schema = 'public'"
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'django_migrations', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'django_content_type', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'auth_permission', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'auth_group', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'auth_group_permissions', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbsetting', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dblog', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbuser', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbauthinfo', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbgroup_dbnodes', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbcomputer', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbgroup', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbnode', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dblink', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
('new_chrisjsewell_3abef2c96e126c712c1d3e256a3590b9', 'public', 'db_dbcomment', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)
```

**Comment by sphuber** [comment]
I can already see the troubleshooting advice in the future:

> To fix the problem, simply run `verdi devel run-sql "TRUNCATE db_dbnode;"

:sweat_smile: 

BTW: why do you label this as "maintain"? Isn't this really a future, even though mostly for developers?

**Comment by chrisjsewell** [comment]
> To fix the problem, simply run `verdi devel run-sql "TRUNCATE db_dbnode;"

haha, can always hide the command, if you think it is too "dangerous" lol?

> BTW: why do you label this as "maintain"? 

yeh for me its not a user feature, so it goes under maintenance, i.e. when I create a changelog section next I would not put it in the "new" section.

**Comment by sphuber** [comment]
> haha, can always hide the command, if you think it is too "dangerous" lol?

Given that its under `devel` I think that is good enough. The one thing I would add is a quick test. I can add one tomorrow morning if you'd like and merge it straight after.

**Review by sphuber — APPROVED** [review]
Hope that given it is under `verdi devel` users will realize this does not come with protection against shooting-yourself-in-the-foot :smile:

**Pull request merged**
