### PR TITLE
🐛 FIX: typing failure

### PR DESCRIPTION
**Pull request by chrisjsewell**
Failing in other open PRs: it appears `numpy.inf` is no longer typed as an integer.

### CODE REVIEW

**Comment by greschd** [comment]
AFAICT, passing `numpy.inf` would still complain.. if we're ok with adding `typing_extensions` to the dependencies for python<3.8, that could be typed as `Optional[Union[int, Literal[inf]]]`.

**Review by ltalirz — APPROVED** [review]
thanks

Just wondering - there is no special treatment needed for `None` anymore either?

**Comment by ltalirz** [comment]
hm.. I also guess this would make any CI run fail that doesn't use numpy 1.20

**Comment by chrisjsewell** [comment]
> AFAICT, passing numpy.inf would still complain.. if we're ok with adding typing_extensions to the dependencies

Yeh it did, I've just cast the `inf` to `int` for now, which should always work.
Would not be adverse to adding `typing_extensions`, but seems a bit drastic for this particular issue

**Review by ltalirz — CHANGES_REQUESTED** [review]
is it possible to support both new and old numpy versions?

it's only for developers, so perhaps it's ok...

 but if you switch to the new numpy, you'll also need to update the numpy dependency as well so that developers won't run into issues

**Comment by greschd** [comment]
> Yeh it did, I've just cast the inf to int for now, which should always work.

Yeah, but that's only for the `None` case.. if someone passes `np.inf` explicitly, it should complain at the call site, no?

**Comment by chrisjsewell** [comment]
> is it possible to support both new and old numpy versions?

not sure what you meany by this? The change in this PR does support both

**Comment by ltalirz** [comment]
> not sure what you meany by this? The change in this PR does support both

Sorry, I was seeing a different change... it also wasn't just the first commit. No idea, I'll leave it to @greschd and you to agree there

**Comment by chrisjsewell** [comment]
> if someone passes `np.inf` explicitly, it would falsely complain at the call site, no?

it would, and that would be correct because the call signature does not allow you to pass `numpy.inf`, that is an internal implementation, and you should use `None` instead

this is only for mypy though obviously, not during actual code execution

**Comment by greschd** [comment]
Yep, sorry, noticed that too late (see my sneaky edit above).

**Review by greschd — APPROVED** [review]

**Comment by chrisjsewell** [comment]
> Yep, sorry, noticed that too late (see my sneaky edit above).

very sneaky 😆

**Pull request merged**
