### PR TITLE
CLI: Fix results not being committed in `verdi code delete`

### LINKED ISSUE #5842: `verdi code delete` falsely claims it actually deleted a node
It claims that the code is deleted, but it is not actually the case. Seems that the problem is with the `PsqlDosBackend.delete_nodes_and_connections` that does perform the deletion but changes are not persisted. This is most likely related to recent refactorings of the `PsqlDosBackend.transaction` method.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5842 

The `verdi code delete` command would report that the `Code` was deleted
but the changes were actually not committed. This went unnoticed since
the test for it used the `click.CliRunner` which doesn't follow the
exact same path as a real invocation on the command line. In particular,
in this example the treatment of the session is different with it not
being committed properly in the command line invocation pathway. The
problem is shown by using `use_subprocess=True` when calling the command
using the `run_cli_command` fixture, after which the test fails.

### CODE REVIEW

**Comment by sphuber** [comment]
@chrisjsewell the failure started after the changes to the `PsqlDosBackend.transaction` released in `v2.2.0`. Most likely `verdi code delete` is not the only command that is now not properly committing changes.

I am not exactly sure why the changes are not being committed. When the command calls `backend.delete_nodes_and_connections` it calls `backend.transaction` and then performs the deletion. The `transaction` method says the session is already in a transaction so it calls `session.begin_nested` and returns the session. Clearly the changes are not being committed. This is supposed to be done when the outer transaction (started when `session.begin` was called for the first time) exits the context manager. I am not sure yet where in the code this is being called and why the commit is not going through.

For now, to demonstrate a potential fix, I added the opening of a transaction in the `with_dbenv` which should now guarantee that changes performed in CLI commands are committed, but not yet sure that this is the correct approach.

**Comment by ltalirz** [comment]
Indeed, it appears `verdi node delete` seems to be broken entirely.
We should either apply a quick fix this or roll back the change that was made

**Comment by sphuber** [comment]
>  We should either apply a quick fix or roll back the change that was made

The [change that caused this](https://github.com/aiidateam/aiida-core/commit/98e902bcc5d38363b5109c38cfae3e6073a3a23c) fixed another problem related to the same code :sweat_smile: so I would prefer not to revert it.

**Comment by sphuber** [comment]
The bug introduced actually affects way more than just `verdi code delete`. All `verdi` commands that change state are affected. The fix in this PR is therefore not correct.

**Pull request closed without merging**
