### PR TITLE
Engine: recover behaviour of `upload_calculation`

### PR DESCRIPTION
**Pull request by mbercx**
This is a replacement PR for https://github.com/aiidateam/aiida-core/pull/6348 that contains a set of commits to recover the behaviour of `upload_calculation` the latest release (v2.5.1).

### CODE REVIEW

**Comment by mbercx** [comment]
@sphuber I could still reorder or merge the commits a bit, but I tried to separate them in order to keep them more atomic and clear.

I forgot to add you as a co-author for the engine fix commit, apologies! Will fix that during review.

**Comment by sphuber** [comment]
> @sphuber I could still reorder or merge the commits a bit, but I tried to separate them in order to keep them more atomic and clear.

Think they look fine (minus the emojis of course ;) ). I would maybe just merge the second and third, since they are both dealing with centralizing the `serialize_file_hierarchy` fixture. Think it is fine and perhaps better even to have them in a single commit.

> I forgot to add you as a co-author for the engine fix commit, apologies! Will fix that during review.

S'all good man

**Comment by mbercx** [comment]
> Think they look fine (minus the emojis of course ;) )

Oops, did I add emojis? I didn't even notice 😇 

> I would maybe just merge the second and third, since they are both dealing with centralizing the serialize_file_hierarchy fixture. Think it is fine and perhaps better even to have them in a single commit.

Makes sense, will do! Do I go ahead and do it now or wait for your first round of review?

**Comment by sphuber** [comment]
> Makes sense, will do! Do I go ahead and do it now or wait for your first round of review?

Going through it now. Might as well hold on a bit

**Review by sphuber — CHANGES_REQUESTED** [review]
Thanks a lot @mbercx . Fantastic piece of work. Since we have already gone through the most important changes in the `upload_calculation` implementation in detail, they should be good to go. I had a look at the other changes and they also look good. The only minor nit would be that I found the naming of the `overwrite` parametrized argument in `test_put_and_get_overwrite` a bit confusing. I would expect it to be used to actually define `overwrite` in the transport calls. But it is not critical to change it.

I am marking this as "changes requested" but that is really just to merge the second and third commit.

**Comment by mbercx** [comment]
@sphuber hierarchy commits squashed and nit picked! Let's I didn't mess up and the tests still pass ;)

**Review by sphuber — APPROVED** [review]

**Comment by sphuber** [comment]
Fan-fucking-tastic @mbercx thanks a lot

**Pull request merged**
