### PR TITLE
Dependencies: Add support for Python 3.11

### LINKED ISSUE #5767: numpy.narray size issue raised from pymatgen
Is anyone had the same issue encountered, to be honest, I am a bit sick of dependencies handled by pymatgen I think this is not the first time we have problem with it. 
In AiiDAlab, we pinned the numpy version to workaround this. Now I encounter it again with sssp workflow, not sure tune numpy version is a good idea.

```
  File "/opt/conda/lib/python3.9/site-packages/pymatgen/core/lattice.py", line 22, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/opt/conda/lib/python3.9/site-packages/pymatgen/util/coord.py", line 17, in <module>
    from . import coord_cython as cuc
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

numpy version `1.21.4`.
pymatgen version `2022.1.9` (I think this pinned by aiida-core)

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5767 

This required a number of dependencies to be updated:

* `pymatgen`
* `circus`
* `pyyaml`
* `myst-nb`
* `kiwipy`
* `plumpy`

In addition, the `importlib-resources` dependency is added. This is a backport of the `importlib.resources` package that was added to the standard library in Python 3.9. We need it to use the functionality that replaces methods that were deprecated in Python 3.11.

Finally, `requirements/requirements-py-3.11.txt` is added which is used to run the test suite against Python 3.11 in the various GHA workflows.

### CODE REVIEW

**Comment by sphuber** [comment]
@unkcpz This is just waiting for the `plumpy` release to hit on `conda-forge`. I just merged the PR, but it always takes a while. Once it is there, all tests will pass, so maybe you can already give these changes a pass. Thanks!

**Review by unkcpz — APPROVED** [review]
@sphuber thanks! I trigger the failed tests, I think if all pass then should be fine.

**Comment by unkcpz** [comment]
Emm... But if you look at conda test, it actually failed https://github.com/aiidateam/aiida-core/actions/runs/3578754491/jobs/6025647264, again the error is hidden.

**Comment by sphuber** [comment]
Thanks @unkcpz . Yeah, I am actually still waiting for this PR on `archive-path`: https://github.com/aiidateam/archive-path/pull/20  @chrisjsewell could we get that merged please?

**Comment by sphuber** [comment]
For some reason, the tests are taking super long on Python 3.11. I have a hard time believing there is an actual problem with the code, but I don't understand where this might be coming from..

**Comment by sphuber** [comment]
Ok, all problems fixed now. The hanging was caused by the environment not being reset after tests that mess with the daemon. After that fix, tests were still running super slow, ~40 minutes for the test suite. Found out that this is due to an outdated version of `coverage`. After updating it, they are running in normal time again.

**Pull request merged**
