### PR TITLE
🧪 TESTS: Entirely remove `AiidaTestCase`

### PR DESCRIPTION
**Pull request by chrisjsewell**
bye bye 👋

### CODE REVIEW

**Comment by ltalirz** [comment]
Thanks a lot @chrisjsewell !

I don't have the time to go through all of the 85 modified files here; if there's something particular I should have a look at, let me know.

**Comment by chrisjsewell** [comment]
Heya, erm not particularly; in #5330 I already ensured consistency between the `AiidaTestCase` and the `aiida_profile_clean` test fixture, then this PR just follows the conversion process I outlined in #4782

So, personally, I'm happy that everything here is fine, and obviously all the tests are still passing, which is the main thing.

**Review by sphuber — APPROVED** [review]

**Comment by chrisjsewell** [comment]
Ok well @sphuber has swooped in and approved lol, @ltalirz are you happy for me to merge, or did you still want to look?

**Comment by ltalirz** [comment]
All good, go ahead

**Pull request merged**
