### PR TITLE
Docs: replace CircleCI build with ReadTheDocs

### LINKED ISSUE #4104: Move doc builds back to GitHub Actions (when artefacts supported)
In #4099, the docs action will be replaced by a build with CircleCI.
When/if GitHub Actions allows for storage of (unzipped) artefacts, we can move back to this action

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #4104

The documentation was being built on CircleCI instead of GHA like the
rest of the CI pipeline, because the former would allow the built
HTML documentation to be inspected as an artifact, whereas for the
latter this wasn't possible.

It is now possible to do the same with ReadTheDocs, and since we already
use that to host the documentation, that means we can now drop CircleCI.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
I've just turned on the RTD PR builds then.
As mentioned (https://github.com/aiidateam/aiida-core/issues/4104#issuecomment-650200606), my only slight concern was on build limits

**Comment by sphuber** [comment]
> I've just turned on the RTD PR builds then.

Also did that already, but build doesn't seem to get triggered here. Do we need to configure a webhook here in this repo explicitly?

**Comment by chrisjsewell** [comment]
Perhaps you didn't save it, because it was selected when I went to the settings.
Try re-triggering the CI again

**Comment by chrisjsewell** [comment]
> I did this on the old aiida meta package

Don't even know what this is lol

**Comment by sphuber** [comment]
> Don't even know what this is lol

It is [this package](https://readthedocs.org/projects/aiida/). Those are the docs for the [`aiida` PyPI package](https://pypi.org/project/aiida/). This was a wrapper package we used to maintain that would install `aiida-core` and some of the main plugins; `aiida-quantumespresso`, `aiida-codtools` and `aiida-nwchem` I believe.

**Comment by sphuber** [comment]
Retriggered the CI but I don't see it triggering the RTD build

**Comment by chrisjsewell** [comment]
ok give it another go

**Comment by chrisjsewell** [comment]
there you go 👍

**Comment by sphuber** [comment]
> there you go +1

What did you change?

**Comment by chrisjsewell** [comment]
magic! (add PR events to the webhook)

**Pull request merged**
