### PR TITLE
Add `aiida` as a `verdi` alias (for now?)

### PR DESCRIPTION
**Pull request by edan-bainglass**
AiiDA should be represented by `aiida` at the command line. Seems obvious. Appears to have been the initial choice but gave way to `verdi` due to a conflict with the `aiida` python package itself. However, this appears to no longer be the case. See https://github.com/orgs/aiidateam/discussions/6381.

Of course, if agreed/accepted, we should consider how to proceed with the docs. At least three votes so far in favor of `aiida` going forward, `verdi` as legacy, so reflect this in docs.

### CODE REVIEW

**Comment by sphuber** [comment]
To give some counterweight to this proposal: does the fact that the CLI is called `verdi` instead of `aiida` really cause any problems? I have only ever heard one person who thought it was a weird choice and found it counterintuitive. On the flipside, I think there is actually a potential benefit to having `verdi` instead of `aiida`. The name `verdi` provides a unique label to refer to the CLI. When talking about it, it is easy to refer to the CLI and everybody knows what you are talking about. If we were to change this for `aiida`, I can see potentially discussions becoming less obvious. Now when someone refers to "aiida", you are not immediately sure if it refers to the software as a whole, the Python API, or the CLI.

So, considering the, what I think, minimal advantages of switching to `aiida`, and the considerable amount of work for us and users to update all their scripts/docs, combined with the downside of  introducing ambiguity, is this change worth it?

**Comment by edan-bainglass** [comment]
I always found `verdi` confusing. I want to do something with AiiDA, so `aiida do-something` seemed reasonable. As I understand from Giovanni, this was also the initial direction, but as mentioned, previous issues prevented this. That said, @sphuber brings up a fair point w.r.t confusion of what you're talking about when you say `aiida` if this change was to take place.

Maybe some input from @giovannipizzi?

**Comment by giovannipizzi** [comment]
I also had a doubt on the advantage of using Verdi as a way to refer specifically to the cli a few days ago. Also, we would have a problem with the `verdi giuseppe` Easter egg ;-) but apart from jokes, I'm not sure what the best is. Once you use aiida and know what verdi is, it's OK. As a new user, or speaking of aiida and verdi to non aiida users, it's possibly confusing. I'm not sure if at least adding also aiida as a cli alias is better or worse (at least having it would have the advantage of aligning with the cli of many plug-ins such as aiida-quantumespresso, aiida-pseudo etc that have the package name as the cli name as well).

**Comment by danielhollas** [comment]
> we would have a problem with the verdi giuseppe Easter egg

Ahaaa! Embarrassingly, even after I found out that this exists, it took me some time to figure out where it is hidden. :sweat_smile:

**Comment by sphuber** [comment]
>  I'm not sure if at least adding also aiida as a cli alias is better or worse

Whatever we do, I definitely would not do a half-way solution. If we were to add the alias, then we should go all the way and update all the docs and tutorials to use this and merely keep `verdi` for backwards compatibility. If we have two different commands, that is for sure going to cause more confusion to new users. And if the main reason is to remove potential confusion for new users, this seems completely counterproductive.

Since this apparently requires more discussion, I will be closing this for now.

**Comment by edan-bainglass** [comment]
... with the understanding that discussion is to continue at https://github.com/orgs/aiidateam/discussions/6381 🙂

**Comment by danielhollas** [comment]
I think these discussions should happen on Discourse right? I belive GitHub Discussions should be deprecated / closed.

**Pull request closed without merging**
