### PR TITLE
🧪 TESTS: add  `config_with_profile` fixture

### PR DESCRIPTION
**Pull request by chrisjsewell**
Using this fixture allows for the removal of `temporary_config_instance` and `with_temporary_config_instance` from `tests/utils/configuration.py`.
Partially addresses #4249

### CODE REVIEW

**Comment by chrisjsewell** [comment]
another quick one for you @ltalirz 😬, off the back of #4712

**Review by ltalirz — APPROVED** [review]
great, thanks!

**Comment by ltalirz** [comment]
Can `create_mock_profile` also be replaced or are there somehow difficulties?

**Comment by chrisjsewell** [comment]
> Can create_mock_profile also be replaced or are there somehow difficulties?

these require the fixture to be directly passes to the functions (not just using the `usefixture` decorator), which in turn requires all the tests to be rewritten to not subclass `AiidaTestCase` and use regular assets. So just more work that I can be bothered with right now lol.

**Pull request merged**
