### PR TITLE
Run test-install GA workflow only on main repository.

### PR DESCRIPTION
**Pull request by csadorf**
* To avoid wasting of resources on forks.
 * Resolves issue #4257.

### CODE REVIEW

**Comment by csadorf** [comment]
https://github.com/csadorf/aiida-core

**Comment by csadorf** [comment]
I went through all forks and identified the following repositories that will need to update their `develop` branch to avoid running the test-install cron job:
* https://github.com/CasperWA/aiida_core
* https://github.com/chrisjsewell/aiida_core
* https://github.com/Crivella/aiida-core
* https://github.com/csadorf/aiida-core
* https://github.com/espenfl/aiida_core
* https://github.com/giovannipizzi/aiida_core
* https://github.com/lorisercole/aiida-core
* https://github.com/ltalirz/aiida-core
* https://github.com/ramirezfranciscof/aiida-core
* https://github.com/sphuber/aiida_core
* https://github.com/unkcpz/aiida_core
* https://github.com/yakutovicha/aiida_core
* https://github.com/zhubonan/aiida_core

Once this PR is merged, I'll create an issue in each of those repositories, recommending that the repository owners synchronize their `develop` branch with `aiidateam:develop`.

**Comment by sphuber** [comment]
>     * Resolves issue #4257.

Just FYI: if you write it this way, Github won't automatically make the link with the issue and close it when this PR is merged. To do so, use the form "Fixes #4257" where "fixes" can also be replaced by "resolves" and some other keywords. If the keyword is properly recognized it will get a small dotted line under it, which is how you can check it easily

**Comment by csadorf** [comment]
> Shouldn't we also add the same guard in the `tests` and `check-requirements` jobs?

These jobs depend on the others, so there is no need for that.

**Comment by csadorf** [comment]
> > ```
> > * Resolves issue #4257.
> > ```
> 
> Just FYI: if you write it this way, Github won't automatically make the link with the issue and close it when this PR is merged. To do so, use the form "Fixes #4257" where "fixes" can also be replaced by "resolves" and some other keywords. If the keyword is properly recognized it will get a small dotted line under it, which is how you can check it easily

Thank you for pointing that out, I've manually linked the issue instead.

**Comment by sphuber** [comment]
Thanks a lot @csadorf !

**Pull request merged**
