### PR TITLE
Docs: remove sphinx_cheatsheet and visual_aids

### LINKED ISSUE #4033: Docs: Shpinx Cheatsheet
Move content from the [sphinx cheatsheet](https://aiida.readthedocs.io/projects/aiida-core/en/latest/developer_guide/tools/sphinx_cheatsheet.html) of the old documentation into the aiida-core wiki.

### LINKED ISSUE #4034: Docs: ASCII graph tool
Move [instructions](https://aiida.readthedocs.io/projects/aiida-core/en/latest/developer_guide/tools/visual_aids.html) on how to use graph easy from the old documentation into the aiida-core wiki.

### PR DESCRIPTION
**Pull request by ramirezfranciscof**
Fixes #4034 and fixes #4033 

The content of visual_aids was moved to the wiki [here](https://github.com/aiidateam/aiida-core/wiki/Graph-Easy), the content of the sphinx_cheatsheet was just removed ([the wiki](https://github.com/aiidateam/aiida-core/wiki/Writing-documentation) already contains a link to an [official reference resource](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)). Both files are no longer in the docs.

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
@csadorf [tis done](https://github.com/aiidateam/aiida-core/wiki/Writing-documentation#useful-resources).

**Comment by sphuber** [comment]
@ramirezfranciscof I edited your OP to use the keyword "fixes" to mark which issues will be fixed by this. You can see that the word is underlined showing that Github understands that it has special meaning. There are other keywords that you can use like "closing", but the way you wrote it there won't be an automatic link created in the corresponding issues.

**Comment by ramirezfranciscof** [comment]
@sphuber Hey, why did this not automatically close the corresponding issues? Did github not recognize the "fixes" correctly because they were edited in instead of being in the original OP?

**Comment by sphuber** [comment]
The reason is just that it wasn't merged into `develop` but into `docs-revamp`. Github will only respect those triggers when merging into the "main" branch, which we have set to `develop`. I guess the philosophy is that until the fix is merged into the main branch it isn't "really" fixed. So I just do it manually for now in order to keep track of what has been done

**Pull request merged**
