### PR TITLE
fix: delete configured computers

### LINKED ISSUE #5396: Unable to delete computer - null value in column "dbcomputer_id" violates not-null constraint
While looking into https://github.com/aiidateam/aiida-core/issues/5395 I noticed that I'm not able to delete a computer despite the fact that no nodes are associated with it:

```
In [26]: nodes=QueryBuilder().append(Node).all()

# no nodes left that are associated with a computer
In [27]: [n[0].computer for n in nodes]
Out[27]: [None, None, None, None]

# deleting computer still fails
In [28]: !verdi computer delete localhost
--- Logging error ---
Traceback (most recent call last):
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "dbcomputer_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aiida/aiida-core/aiida/storage/psql_dos/orm/computers.py", line 130, in delete
    session.commit()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "dbcomputer_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).

[SQL: UPDATE db_dbauthinfo SET dbcomputer_id=%(dbcomputer_id)s WHERE db_dbauthinfo.id = %(db_dbauthinfo_id)s]
[parameters: {'dbcomputer_id': None, 'db_dbauthinfo_id': 1}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiida/aiida-core/aiida/cmdline/commands/cmd_computer.py", line 550, in computer_delete
    orm.Computer.objects.delete(computer.id)
  File "/home/aiida/aiida-core/aiida/orm/computers.py", line 62, in delete
    return self._backend.computers.delete(pk)
  File "/home/aiida/aiida-core/aiida/storage/psql_dos/orm/computers.py", line 132, in delete
    raise exceptions.InvalidOperation(
aiida.common.exceptions.InvalidOperation: Unable to delete the requested computer: it is possible that there is at least one node using this computer (original message: (psycopg2.errors.NotNullViolation) null value in column "dbcomputer_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).

[SQL: UPDATE db_dbauthinfo SET dbcomputer_id=%(dbcomputer_id)s WHERE db_dbauthinfo.id = %(db_dbauthinfo_id)s]
[parameters: {'dbcomputer_id': None, 'db_dbauthinfo_id': 1}]
(Background on this error at: https://sqlalche.me/e/14/gkpj))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiida/aiida-core/aiida/cmdline/utils/log.py", line 37, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/aiida/aiida-core/aiida/cmdline/utils/log.py", line 60, in format
    return f'{click.style(record.levelname.capitalize(), fg=fg, bold=True)}: {record.msg % record.args}'
TypeError: format requires a mapping
Call stack:
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/aiida/aiida-core/aiida/cmdline/utils/decorators.py", line 73, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/aiida/aiida-core/aiida/cmdline/commands/cmd_computer.py", line 552, in computer_delete
    echo.echo_critical(str(error))
  File "/home/aiida/aiida-core/aiida/cmdline/utils/echo.py", line 158, in echo_critical
    CMDLINE_LOGGER.critical(message, extra=dict(nl=nl, err=err, prefix=prefix))
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1493, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/aiida/aiida-core/aiida/cmdline/utils/log.py", line 40, in emit
    self.handleError(record)
Message: '\x1b[22mUnable to delete the requested computer: it is possible that there is at least one node using this computer (original message: (psycopg2.errors.NotNullViolation) null value in column "dbcomputer_id" violates not-null constraint\nDETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).\n\n[SQL: UPDATE db_dbauthinfo SET dbcomputer_id=%(dbcomputer_id)s WHERE db_dbauthinfo.id = %(db_dbauthinfo_id)s]\n[parameters: {\'dbcomputer_id\': None, \'db_dbauthinfo_id\': 1}]\n(Background on this error at: https://sqlalche.me/e/14/gkpj))\x1b[0m'
Arguments: ()

``` 

The issue seems to be that my computer row has "dbcomputer_id" null, which is not allowed.

This computer was created under aiida 2.0 (not migrated).
I'll try whether I can get a minimal reproduction of this issue.

### PR DESCRIPTION
**Pull request by ltalirz**
fix #5396 

Deleting a configured computer resulted in an error, since the
associated Authinfo object was not deleted (instead, the "dbcomputer_id"
was set to null, which violated a not-null constraint).

Deleting computers was already tested, but not deleting a configured
computer. This is fixed as well.

### CODE REVIEW

**Comment by ltalirz** [comment]
@chrisjsewell Seems like the deletion test passes now.

Do I need to write a migration here?
Is there an automatic way of getting it?

**Comment by chrisjsewell** [comment]
> Do I need to write a migration here?

No, relationships are at the ORM level, i.e. transient and not part of the database schema

Might be good to add two tests to `tests/orm/test_authinfos.py`, to specifically test that deleting a computer or user also removes any associated authinfos

**Comment by ltalirz** [comment]
While looking into this, I realized that there actually is no `User.objects.delete` - is there any way to delete a user?

If not should I be adding it in this PR?

**Comment by chrisjsewell** [comment]
> is there any way to delete a user?

Not on the front-end (i.e. in `aiida/orm/implementation/users.py`)

I guess thats a bit of a wider discussion than this PR 😬 
As mentioned above, we should probably not allow for the deletion of the default user for a profile, since that is a bit of a special case

**Comment by ltalirz** [comment]
> > is there any way to delete a user?
> 
> Not on the front-end (i.e. in `aiida/orm/implementation/users.py`)
> 
> I guess thats a bit of a wider discussion than this PR 😬 As mentioned above, we should probably not allow for the deletion of the default user for a profile, since that is a bit of a special case

Ok, then I guess it's enough if I add a test that deleting a computer also deletes the authinfo and leave the test deleting a user for another time.

**Comment by chrisjsewell** [comment]
👍

**Review by chrisjsewell — APPROVED** [review]
Cheers

**Pull request merged**
