### PR TITLE
REST API: list endpoints at base URL

### LINKED ISSUE #3916: REST API: base URL returns 404, not clear how to find the endpoints
Hi,

I started the rest api as follows:

`$ verdi -p aiida restapi`

Then I open http://localhost:5000/ to request a full list of available endpoints for each resource, but failed with:
```

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

```

Any hints?

Regards

### PR DESCRIPTION
**Pull request by ltalirz**
fixes #3916 

The base URL of the REST API was returning a 404 invalid URL response
without providing any guidance to new users as to how to use the API.
We change this to return the list of endpoints formerly available only
under /server/endpoints.

Documentation of where to find the list of endpoints -- which seems
to have been entirely deleted -- is reintroduced.

### CODE REVIEW

**Comment by ltalirz** [comment]
@giovannipizzi @asle85 Does this look good to you?

**Comment by asle85** [comment]
Thanks @ltalirz ! It looks good to me

**Comment by ltalirz** [comment]
@giovannipizzi Could you look into reviewing & merging this?

**Comment by giovannipizzi** [comment]
Thanks a lot @ltalirz !
However as codecov points out, the new code path (line 44) is not tested - could you add a test for the / path? (Probably it could be a copy-paste from one of the existing tests?)

**Comment by ltalirz** [comment]
Makes sense - added!

**Review by giovannipizzi — APPROVED** [review]

**Pull request merged**
