### PR TITLE
DOCS: add top level indexes

### PR DESCRIPTION
**Pull request by chrisjsewell**
This is what the docs look like with indexes for each section, and also moving the tutorial into the Introduction section

### CODE REVIEW

**Comment by chrisjsewell** [comment]
The only stylistic annoyance for me, is that the left ToC tree is now collapsed (I'm pretty sure you can't have it expanded by default: https://github.com/readthedocs/sphinx_rtd_theme/issues/455)

**Comment by chrisjsewell** [comment]
https://137-77234579-gh.circle-artifacts.com/0/html/index.html

**Comment by csadorf** [comment]
> readthedocs/sphinx_rtd_theme#455

Yeah, I'm not sure how I feel about this. That seems to me like the bigger issue. Does it look better with the bootstrap theme?

**Comment by chrisjsewell** [comment]
> > [readthedocs/sphinx_rtd_theme#455](https://github.com/readthedocs/sphinx_rtd_theme/issues/455)
> 
> Yeah, I'm not sure how I feel about this. That seems to me like the bigger issue. Does it look better with the bootstrap theme?

See https://github.com/aiidateam/aiida-core/pull/4129#issuecomment-635981501, no full ToC, because it works a bit differently, by only showing the top-level headings for the section on the right, and sections for the page you are on, on the right (click around and you'll see what I mean) Note there is an issue open to maybe improve this for the front page:  https://github.com/pandas-dev/pydata-sphinx-theme/issues/146

**Comment by csadorf** [comment]
@chrisjsewell This can be closed, right?

**Comment by chrisjsewell** [comment]
yep

**Pull request closed without merging**
