### PR TITLE
`InteractiveOption`: Fix validation being skipped if `!` provided

### LINKED ISSUE #6030: 🐛 Setting `user` (Email) to none is possible but fails quickly
### Describe the bug

While running `verdi profile setup`, it's possible not to set the `user` (which is actually an email, also slightly strange):

```console
❯ verdi setup
Report: enter ? for help.
Report: enter ! to ignore the default and set no value.
Profile name: dev      
Email Address (for sharing data) [()]: 
Error: Please enter a valid email.
Email Address (for sharing data) [()]: !
First name [()]: !
Last name [()]: !
Institution [()]: !
Database engine (postgresql_psycopg2) [postgresql_psycopg2]: 
Database backend (core.psql_dos) [core.psql_dos]: 
Database host [localhost]: 
Database port [5432]: 
Database name: core-dev
Database username: mbercx
Database password: 
Broker protocol (amqp, amqps) [amqp]: 
Broker username [guest]: 
Broker password [guest]: 
Broker host [127.0.0.1]: 
Broker port [5672]: 
Broker virtual host name []:  
Repository directory [/Users/mbercx/project/core/.aiida/repository/dev]: 
Success: created new profile `dev`.
Report: initialising the profile storage.
Report: initialising empty storage schema
Report: Migrating to the head of the main branch
Success: storage initialisation completed.
```

All good, ready to go I'd say 🚀. Alas, the party ends quite quickly:

```python
In [1]: Int(1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 1
----> 1 Int(1)

File ~/project/core/code/aiida-core/aiida/orm/nodes/data/base.py:33, in BaseType.__init__(self, value, **kwargs)
     30 except AttributeError:
     31     raise RuntimeError('Derived class must define the `_type` class member')
---> 33 super().__init__(**kwargs)
     35 self.value = value or self._type()

File ~/project/core/code/aiida-core/aiida/orm/nodes/data/data.py:50, in Data.__init__(self, source, *args, **kwargs)
     48 def __init__(self, *args, source=None, **kwargs):
     49     """Construct a new instance, setting the ``source`` attribute if provided as a keyword argument."""
---> 50     super().__init__(*args, **kwargs)
     51     if source is not None:
     52         self.source = source

File ~/project/core/code/aiida-core/aiida/orm/nodes/node.py:189, in Node.__init__(self, backend, user, computer, **kwargs)
    186 user = user if user else backend.default_user
    188 if user is None:
--> 189     raise ValueError('the user cannot be None')
    191 backend_entity = backend.nodes.create(
    192     node_type=self.class_node_type, user=user.backend_entity, computer=backend_computer, **kwargs
    193 )
    194 super().__init__(backend_entity)

ValueError: the user cannot be None
```

### Expected behavior

If the user is necessary to run with the profile it should not be possible to not specify it during setup. That said, _why_ is the user _necessary_ just to use AiiDA? I understand that e.g. only the groups owned by the current user are shown when doing e.g. `verdi group list`, but I would argue this actually _detracts_ from the UX (I download archive. I import archive. I do `verdi group list` and see no groups).

In fact, do we really have to ask people's names too? And their Institution even? I think there are all unnecessary and hence can be optional but removed from the setup.

### Your environment

- Operating system [e.g. Linux]: MacOS
- Python version [e.g. 3.7.1]: 3.9.16
- aiida-core version [e.g. 1.2.1]: `main` branch

### Additional context

Also I could not find a specific issue with a cursory search, this is heavily related to all issues concerning AiiDA uptake, i.e. getting beginners up and running as fast as possible with AiiDA.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #6030 

The `InteractiveOption` reserves the exclamation point `!` as a special character in order to "skip" the option and not define it. This is necessary for options that are _not_ required but that do specify a defualt. Without this character, it is impossible to _not_ set the default as, if the user doesn't specify anything specific and simply presses enter, the default is taken, even if the user did not want to specify any specific value.

The problem with the implementation, however, is that when `!` was provided, the option would return `None` as the value, bypassing any validation that might be defined. This would make it possible to bypass the validation of a required option.

The solution is to, when `!` is provided for an interactive option, it is translated to `None` and is then processed as normal, validating it as any other value.

### CODE REVIEW

**Comment by mbercx** [comment]
Thanks a lot @sphuber! The logic of the interactive options is not trivial to understand indeed. The changes look fine, but I'm still trying to get a better overview of where everything is coming from.

In the meanwhile, I've been playing around with the `verdi setup` command some more, in an effort to try and break things: 😇 

```console
❯ verdi setup
Report: enter ? for help.
Report: enter ! to ignore the default and set no value.
Profile name: test
Email Address (for sharing data) [()]:
Error: Please enter a valid email.
Email Address (for sharing data) [()]: !
Error: Missing parameter: email
```

This would be my first (minor) nitpick: I suppose "Error: Missing parameter:" comes from the underlying check and makes sense when e.g. trying to set up a profile from a YAML file and this input is missing. In the interactive CLI it would be better to have a message like "Error: Must set value for email."

```console
Email Address (for sharing data) [()]: giuseppi.verdi@aiida.net
First name [()]:
Last name [()]: !
Error: Missing parameter: last_name
Last name [()]:
Institution [()]: !
Error: Missing parameter: institution
Institution [()]:
```

This behaviour was also somewhat unexpected. You can't set it to no value, but you can set an empty default?

```console
Database engine (postgresql_psycopg2) [postgresql_psycopg2]: !
Database backend (core.psql_dos) [core.psql_dos]: !
Database host [localhost]: !
Database port [5432]: !
```

Here I wanted to see if trying to set no value could break the setup. And it turns out it can 😅:

```console
[...] Removed for brevity
Success: created new profile `test`.
Report: initialising the profile storage.
Critical: storage initialisation failed, probably because connection details are incorrect:
Entry point 'None' not found in group 'aiida.storage'
```

It also says that it successfully created the new profile, but it's not in the `config.json`. However, the `first_name`, `last_name` and `institution` are now in the configuration:

```console
❯ verdi config list
Warning: no profiles configured: run `verdi setup` to create one
name                                   source    value
-------------------------------------  --------  ------------------------
autofill.user.email                    global    giuseppi.verdi@aiida.net
autofill.user.first_name               global    ()
autofill.user.institution              global    ()
autofill.user.last_name                global    ()
```

Then I did another test run, but this time I was mean to the broker. This part of the configuration wanted none of my shenanigans, however:

```console
[...] Removed for brevity
Broker protocol (amqp, amqps) [amqp]: !
Error: Missing parameter: broker_protocol
Broker protocol (amqp, amqps) [amqp]:
Broker username [guest]: !
Error: Missing parameter: broker_username
Broker username [guest]:
Broker password [guest]:
Error: Missing parameter: broker_password
Broker password [guest]:
Broker host [127.0.0.1]: !
Error: Missing parameter: broker_host
Broker host [127.0.0.1]: !
Error: Missing parameter: broker_host
Broker host [127.0.0.1]:
Broker port [5672]: !
Error: Missing parameter: broker_port
Broker port [5672]:
Broker virtual host name []: !
Error: Missing parameter: broker_virtual_host
Broker virtual host name []:
```

But then I was like: "bah, who needs a repository!":

```console
Repository directory [/Users/mbercx/project/test/.aiida/repository/test]: !
Success: created new profile `test`.
Report: initialising the profile storage.
Critical: storage initialisation failed, probably because connection details are incorrect:
invalid profile test: `storage.config.repository_uri` is not absolute
```

And that broke things again. 😇 

Not sure how much scope creep you are willing to accept, but maybe we can try and fix all these `!` issues in one fell swoop? In the meanwhile I'll try to get more familiar with the `verdi` code base so I can do a proper review (with of course as  ulterior motive to one day do a hostile takeover and rewrite the entire CLI in `typer` 😈).

**Comment by sphuber** [comment]
Ok Mr. Scope Creep, I have addressed your comments. Even the nitpicky ones. Back to you @mbercx

**Comment by mbercx** [comment]
Much appreciated, @sphuber! I learned from the best scope creepers on Github. Will have a look over the weekend if I can still break something with the interactive setup. 😈

**Comment by sphuber** [comment]
@mbercx will be merging this soonish

**Comment by sphuber** [comment]
> When I still manage to break something later I'll just open an issue. :)

Sounds great, looking forward to those :D

**Comment by unkcpz** [comment]
I think this PR is aiming to improve `verdi setup` but now `repository` fields are required also for `verdi quicksetup`. I think this is not expected behavior.

**Comment by sphuber** [comment]
https://github.com/aiidateam/aiida-core/pull/6129

**Comment by mbercx** [comment]
> Sounds great, looking forward to those :D

Looks like @unkcpz beat me to it ^^

**Pull request merged**
