### PR TITLE
Add missing migration of transport entry points in archives

### LINKED ISSUE #5587: Archive: Missing migration of transport entry point for Computer
### Describe the bug

Creating an archive containing computers in AiiDA < 2.0, migrating this archive and importing it
into a AiiDA 2.0 installation does not migrate the transport entrypoint, e.g. from `local` to `core.local`

### Steps to reproduce

1. Create an archive in 1.X containing a Computer node (I have an example archive but I can't seem to attach it to the issue)
2. In AiiDA 2.0 migrate the archive
3. Import the archive
4. Below is an example of `verdi computer show` on the imported computer

```
---------------------------  ------------------------------------
Label                        localhost_dummy
PK                           39
UUID                         b49f8e6d-5a94-47eb-a280-1c4b1f318d87
Description
Hostname                     localhost
Transport type               local
Scheduler type               core.direct
Work directory               /home/janssen/
Shebang                      #!/bin/bash
Mpirun command               mpirun -np {tot_num_mpiprocs}
Default #procs/machine       1
Default memory (kB)/machine
Prepend text
Append text
---------------------------  ------------------------------------
```
Notice the scheduler entry point is correctly migrated

### Expected behavior

The `core.` prefix should be added to the entry point

### Your environment

- Operating system [e.g. Linux]: Linux
- Python version [e.g. 3.7.1]: Both environments 3.8.10
- aiida-core version [e.g. 1.2.1]: Archive created in 1.6.8, imported in 2.0.1.post0

### PR DESCRIPTION
**Pull request by janssenhenning**
Fixes #5587

### CODE REVIEW

**Review by sphuber — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution @janssenhenning . This would be an important fix to add indeed. The fix itself looks good, however, we can't be putting this in the existing migration and should really rather create a new one. The reason is that since the `11 -> 12` migration has already been released, there will be archives out there with v12 that does not contain the migration. To have these migrate as well, we need to create a new `12 -> 13` migration. Could you add this separately? You can just copy paste from existing migrations and tests

**Comment by janssenhenning** [comment]
@sphuber Sorry for the late response. I now moved it into a separate migration

**Comment by janssenhenning** [comment]
@sphuber There is a test that the migration works. The test in `tools/archive/migration/test_legacy_funcs.py` is parametrized with all of the migrations in the dictionary `LEGACY_MIGRATE_FUNCTIONS` in `aiida.storage.sqlite_zip.migrations.legacy`

I didin't see an explicit test for the `0.11` to `0.12` migration to check if the entry points are correctly changed beyond the test I mentioned. If I missed it could you point me to the file, where this test is located? I can add this of course if you want.

**Comment by sphuber** [comment]
> @sphuber There is a test that the migration works. The test in `tools/archive/migration/test_legacy_funcs.py` is parametrized with all of the migrations in the dictionary `LEGACY_MIGRATE_FUNCTIONS` in `aiida.storage.sqlite_zip.migrations.legacy`

That parametrized test just checks that the migration does not except and the generic migration actions, such as updating the version in the metadata, is done correctly. There is no explicit check on the actual migration specific functionality.


> I didin't see an explicit test for the `0.11` to `0.12` migration to check if the entry points are correctly changed beyond the test I mentioned. If I missed it could you point me to the file, where this test is located? I can add this of course if you want.

You are right, there isn't one for `0.11` to `0.12`. There are a few more missing for recent migrations, but they are there uptil `0.9`. They are in the directory `tools/archive/migration/`. Would be good to add `test_v012_to_v013.py` there.

**Comment by janssenhenning** [comment]
> Would be good to add `test_v012_to_v013.py` there.

Done

**Review by sphuber — APPROVED** [review]
Thanks a lot @janssenhenning !

**Pull request merged**
