### PR TITLE
Update the pre-commit configuration 

### PR DESCRIPTION
**Pull request by sphuber**
* Drop `prospector`: it was only being used to run `pylint` but in that
   case it is much simpler to just run it directly as `prospector` has
   often given issues with incompatible dependencies
 * Add more hooks from `pre-commit` itself:
   - end-of-file-fixer    automatically add new lines to end of files
   - fix-encoding-pragma  automatically add the utf-8 encoding pragma
   - mixed-line-ending    automatically deal with line break characters
 * Run `pylint` and `yapf` directly from the remote repository
   Since `pylint` still needs to be run with `system` such that it can
   see all dependencies and not throw false import errors, we still need
   to keep it in the `pre-commit` extras requirements.
 * Renamed extra requires categories to match other projects
   dev_precommit -> pre-commit
   testing -> tests

### CODE REVIEW

**Comment by chrisjsewell** [comment]
> prospector has often given issues with incompatible dependencies

Yes! It's always been a pain making it compatible with `flake8` that I use for other packages.

I was just having a scan down https://pre-commit.com/hooks.html, to see if there are any other good ones. There is a few for checking the order of imports, but that may be overkill.
What we don't currently do is any specific linting of documentation, maybe:

- `rst-backticks` - Detect common mistake of using single backticks when writing rst
- or https://github.com/myint/rstcheck#use-as-a-pre-commit-hook, is pretty good

**Comment by sphuber** [comment]
> What we don't currently do is any specific linting of documentation, maybe:
> 
>     * `rst-backticks` - Detect common mistake of using single backticks when writing rst
> 
>     * or https://github.com/myint/rstcheck#use-as-a-pre-commit-hook, is pretty good

Sounds good, but I explicitly didn't add this here. In some of the other repos I already added the `pydocstyle` linter to check the docstrings, but that would be a lot of work here. Wanted to postpone that for a bit. But once we add this, we can look at the backtick fixer as well

**Comment by ltalirz** [comment]
Hi guys, sorry for being a bit late to the game but I find the change of the extras a bit problematic.
Please note that plugins/CI workflows may rely on these and will now break silently (because pip does not complain for incorrect extra names).

One possible solution is to add the old extras back in the `setup.py` and to add a deprecation warning to the CHANGELOG

**Comment by sphuber** [comment]
> Hi guys, sorry for being a bit late to the game but I find the change of the extras a bit problematic.
> Please note that plugins/CI workflows may rely on these and will now break silently (because pip does not complain for incorrect extra names).

Sorry if this change is causing issues, that is of course not intended. I figured that since these are merely extras for development, it would be fine to change them. Can you tell me what other packages depend on it?
Also, maybe we should clarify what `tests` is intended for. I was under the impression that this is just for development of `aiida-core` and not necessarily to be used by plugins. They should define their own testing requirements I feel.

**Comment by ltalirz** [comment]
>  I was under the impression that this is just for development of aiida-core and not necessarily to be used by plugins. They should define their own testing requirements I feel.

I agree with you here, and since pip does not (or at least did not, when I last checked) properly support specifying a dependency on the same package twice (e.g. `aiida-core` under `install_requires` and `aiida-core[testing]` under `extras_require['testing']`), all plugins I've now checked actually follow your advice.
I do think this is a "lucky case", though - if pip did support this I bet there would be a number of plugins reusing the aiida-core extras.

I've looked around a bit more - instances that will need to be changed are:
* https://github.com/marvel-nccr/ansible-role-aiida/blob/9ee58f9cc59f7850d1d5d67fb5b7ca707481c205/defaults/main.yml#L4-L9 @chrisjsewell 
 * https://github.com/aiidateam/aiida-core/wiki/Development-environment

**Comment by greschd** [comment]
Relying on a dependency to pull in packages that are used _directly_ in the plugin code is just plain bad practice. There's no way we can guarantee that some dependency we're pulling in will always be there.

There is some nuance to this, though: the pytest fixtures and sphinx extension are _features of AiiDA_, not just internal dev utilities. So IMO the requirements we use there should be in a "feature" extra, just like e.g `atomic-tools`. In this case the user shouldn't have to care about exactly which dependencies are needed to implement these features, because they _don't_ use the dependencies directly.

**Comment by giovannipizzi** [comment]
Just FYI, prospector just made a new release that addresses our original issue #2205, in case you are using prospector in another project.
See [here](https://github.com/PyCQA/prospector/issues/294)

**Pull request merged**
