### PR TITLE
Remove .gitignore from abandoned 'sphinxext/tests' folder.

### PR DESCRIPTION
**Pull request by greschd**
The tests for the Sphinx extension have moved to the top-level `tests/` directory. In the `aiida/sphinxext/tests` directory, a lonely `.gitignore` was left over - this is now deleted.

### CODE REVIEW

**Comment by sphuber** [comment]
Is it okay for me to include this in the PR I am about to open?

**Comment by greschd** [comment]
Sure, go ahead!

**Comment by ltalirz** [comment]
ah, so "include" means we close this?

**Comment by sphuber** [comment]
Superseded by PR #4203

**Pull request closed without merging**
