### PR TITLE
Fixes the ``extend restapi`` section on the documentation to the AiiDA 1.0 version

### LINKED ISSUE #3177: Check documentation for "for AiiDA developers/How to extend the AiiDA REST API"
Check if the section is updated to AiiDA 1.0, if it is correct, and if it should be merged with other documentation or moved/removed.

https://aiida.readthedocs.io/projects/aiida-core/en/latest/developer_guide/core/extend_restapi.html

### PR DESCRIPTION
**Pull request by d-tomerini**
Fixes #3177 

Updated the provided script to make it compatible with the latest AiiDA; 
a few typos corrected, section is basically valid.

One doubt that I have: I included a ``load_profile`` on the app; would it be better
- to have a ``@decorators.with_dbenv()`` on the click command instead? 
- have it as a ``verdi`` command, so that one can simply have a ``verdi -p`` flag?

### CODE REVIEW

**Comment by sphuber** [comment]
@d-tomerini thanks a lot. It seems like there are a lot of changes that is just sentences being split over multiple lines. For the documentation we actually keep the convention to keep each sentence on a separate line. This makes diffs easier to read and see what sentences have been changed or deleted entirely.

It is now also very difficult to see what has actually changed. It seems the majority of changes is just linebreaks but I have to check everything. Would it be possible to revert this and just have the actual changes/additions to the text? Thanks a lot

**Comment by d-tomerini** [comment]
@sphuber Apologies. I've reverted the changes to the actual modification of the code

**Comment by d-tomerini** [comment]
Thanks a lot @asle85. I'll also modify the v3 in the text to v4 to be ready for release
is_flag was an autocomplete of VScode on <CR> I guess...

**Comment by sphuber** [comment]
Thanks @d-tomerini and @asle85

**Pull request merged**
