### PR TITLE
📚 DOCS: Add process submit diagram

### PR DESCRIPTION
**Pull request by chrisjsewell**
I've found it helpful:

image

### CODE REVIEW

**Comment by chrisjsewell** [comment]
https://2946-77234579-gh.circle-artifacts.com/0/html/topics/processes/concepts.html#process-tasks

**Review by ltalirz — COMMENTED** [review]
thanks @chrisjsewell - this looks very helpful indeed!

did you draw it yourself?
could you include the source of the figure as well?

I would have a couple of minor suggestions

**Comment by chrisjsewell** [comment]
> did you draw it yourself?
> could you include the source of the figure as well?

yes I did it in powerpoint, so I wasn't sure whether I should include it in the repo?

**Comment by ltalirz** [comment]
Yes, better to include it - I'm sure this figure will need to be updated over time.

**Comment by chrisjsewell** [comment]
ok added

**Review by ltalirz — APPROVED** [review]
thanks @chrisjsewell ; 

good to merge for me, we can always iterate on it

**Pull request merged**
