### PR TITLE
Fix typo in checking for ignore_nonexisting in LocalTransport

### PR DESCRIPTION
**Pull request by MichaelGoulding**

### CODE REVIEW

**Comment by mbercx** [comment]
Thanks for the contribution @MichaelGoulding! I can see how the fact that the method looks for `ignore_noexisting` in the `kwargs` is problematic... Especially since other methods use an `ignore_existing` input (thankfully not popping `kwargs`). I'm a bit apprehensive towards fixing this directly, however, since users may be relying on the (unintuitive/incorrect) `ignore_noexisting` input and hence this would technically be a backwards-incompatible change.

I'll work on a deprecation path instead, and also add some more tests to make sure we don't break existing behaviour.

**Comment by MichaelGoulding** [comment]
@mbercx The issue is that I when I switched an existing workflow that was using SshTransport to instead use LocalTransport, the workflow no longer worked.   Perhaps LocalTransport could support both names for now?

**Comment by sphuber** [comment]
@mbercx I have added the backwards compatibility fix. I want to release a patch version soonish. Could you have a quick look? Thanks!

**Review by khsrali — COMMENTED** [review]
Just a suggestion:

I noticed we also have `ignore_existing` somewhere. 
Since you are raising an deprecation warning to version `3`. 
How about we deprecate all the three (`ignore_existing`, `ignore_noexisting`, `ignore_nonexisting`) in favor of `exist_ok` ?
Also they have a reversed logic, every time I have to translate in my mind `-1 * -1 = +1` :smile:

**Comment by sphuber** [comment]
> Just a suggestion:
> 
> I noticed we also have `ignore_existing` somewhere. Since you are raising an deprecation warning to version `3`. How about we deprecate all the three (`ignore_existing`, `ignore_noexisting`, `ignore_nonexisting`) in favor of `exist_ok` ? Also they have a reversed logic, every time I have to translate in my mind `-1 * -1 = +1` 😄

I think it is a good suggestion, but that is used in many places of the interface and would be a considerable change. I think that should be left to a separate PR if we decide to implement that name change.

**Review by mbercx — APPROVED** [review]
Looks good to me, thanks @sphuber! Sorry for the slow review

**Pull request merged**
