### PR TITLE
DevOps: Fix the nightly slack notification on PRs from forks 

### LINKED ISSUE #5668: Nightly test failed notification not working
The nightly test failed (https://github.com/aiidateam/aiida-core/actions/runs/3129772900) but the notification not send with this error.

```
Run rtCamp/action-slack-notify@v2
  env:
    SINGULARITY_ROOT: /opt/hostedtoolcache/singularity/3.8.7/x64
    pythonLocation: /opt/hostedtoolcache/Python/3.10.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.7/x64/lib
    SLACK_WEBHOOK: 
    SLACK_ICON: https://www.materialscloud.org/discover/images/0ba0a17d.aiida-logo-1[2](https://github.com/aiidateam/aiida-core/actions/runs/3129772900/jobs/5079265531#step:12:2)8.png
    SLACK_CHANNEL: dev-aiida-core
    SLACK_COLOR: b60205
    SLACK_TITLE: Nightly build of `aiida-core/main` failed
    SLACK_MESSAGE: The tests of the `nightly.yml` GHA worklow failed.
/usr/bin/docker run --name ghcriortcampactionslacknotifyv220_da[3](https://github.com/aiidateam/aiida-core/actions/runs/3129772900/jobs/5079265531#step:12:3)59e --label 817f70 --workdir /github/workspace --rm -e "SINGULARITY_ROOT" -e "pythonLocation" -e "LD_LIBRARY_PATH" -e "SLACK_WEBHOOK" -e "SLACK_ICON" -e "SLACK_CHANNEL" -e "SLACK_COLOR" -e "SLACK_TITLE" -e "SLACK_MESSAGE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --network github_network_bcded18fdafe[4](https://github.com/aiidateam/aiida-core/actions/runs/3129772900/jobs/5079265531#step:12:4)c0[6](https://github.com/aiidateam/aiida-core/actions/runs/3129772900/jobs/5079265531#step:12:6)[8](https://github.com/aiidateam/aiida-core/actions/runs/3129772900/jobs/5079265531#step:12:8)e03dac8b[9](https://github.com/aiidateam/aiida-core/actions/runs/3129772900/jobs/5079265531#step:12:9)b396fe -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/aiida-core/aiida-core":"/github/workspace" ghcr.io/rtcamp/action-slack-notify:v2.2.0
[ERROR] Secret `SLACK_WEBHOOK` is missing. Please add it to this action for proper execution.
Refer https://github.com/rtCamp/action-slack-notify for more information.
```

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5668 

A limitation of secrets in Github Actions is that they are not available
in workflow runs that are triggered by pull requests that come from
forks. This would cause problems for the nightly workflow, which when
failed tried to send a notification to the Slack channel. However, this
requires the `SLACK_WEBHOOK` which is not available and so the step
would error out.

The solution is to only execute the step if the secret is available
which is now explicitly checked for in the conditional.

### CODE REVIEW

**Comment by sphuber** [comment]
This seems to have worked. I triggered the nightly to run and fail on purpose, and with the changes of this PR, the slack notification step is now properly skipped.

**Comment by sphuber** [comment]
Once you approve @unkcpz I will remove the trigger commit and this can be merged.

**Review by unkcpz — DISMISSED** [review]
Looks good to me. It makes very sense that the failure from the pull request should not trigger a notification.

**Review by unkcpz — APPROVED** [review]
Cheers!

**Pull request merged**
