### PR TITLE
common: fix dateutil.parser import in timezone

### LINKED ISSUE #5137: AttributeError: module 'dateutil' has no attribute 'parser' when running `verdi process list` with Python 3.9.5
### Describe the bug

```
$ verdi process list
   PK  Created    Process label    Process State    Process status
-----  ---------  ---------------  ---------------  ----------------
...

Total results: 16

Traceback (most recent call last):
  File "/scratch/tiziano/virtualenvs/aiida/bin/verdi", line 12, in <module>
    sys.exit(verdi())
  File "/scratch/tiziano/virtualenvs/aiida/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/tiziano/virtualenvs/aiida/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/scratch/tiziano/virtualenvs/aiida/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/tiziano/virtualenvs/aiida/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/tiziano/virtualenvs/aiida/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/tiziano/virtualenvs/aiida/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/scratch/tiziano/work/aiida/aiida-core/aiida/cmdline/utils/decorators.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "/scratch/tiziano/work/aiida/aiida-core/aiida/cmdline/commands/cmd_process.py", line 80, in process_list
    print_last_process_state_change()
  File "/scratch/tiziano/work/aiida/aiida-core/aiida/cmdline/utils/common.py", line 75, in print_last_process_state_change
    timestamp = get_process_state_change_timestamp(process_type)
  File "/scratch/tiziano/work/aiida/aiida-core/aiida/engine/utils.py", line 313, in get_process_state_change_timestamp
    time_stamp = timezone.isoformat_to_datetime(manager.get(key).value)
  File "/scratch/tiziano/work/aiida/aiida-core/aiida/common/timezone.py", line 139, in isoformat_to_datetime
    return dateutil.parser.parse(value)
AttributeError: module 'dateutil' has no attribute 'parser'
```

### Your environment

- Operating system [e.g. Linux]: Linux
- Python version [e.g. 3.7.1]: 3.9.5
- aiida-core version [e.g. 1.2.1]: d7d1ac650c28ead6a422a8167a0e06123565e1d4

### PR DESCRIPTION
**Pull request by dev-zero**
fixes #5137

### CODE REVIEW

**Comment by sphuber** [comment]
Thanks @dev-zero . I have also run into this locally, but haven't had the time to fully figure out why this is failing now. Especially I find it weird that this was not picked up by the CI. The [latest run on Python 3.9.6 finished just fine](https://github.com/aiidateam/aiida-core/runs/3594205143?check_suite_focus=true). The import error only occurs when `aiida.common.timezone.isoformat_to_datetime` is called which is only called in `CalcJob.get_scheduler_lastchecktime` (which is never called whatsoever) and `aiida.engine.utils.get_process_state_change_timestamp`, which in turn is only called via-via in `verdi process list`. That command is tested, so I am not yet sure why that pathway isn't called. Anyway, I think it would be good to at the very least add a direct test for this utility such that it is no longer uncovered.

**Comment by dev-zero** [comment]
I would guess it's because the tests run all `process list` invocations with `-r/--raw` which omits `print_last_process_state_change()`.

**Comment by dev-zero** [comment]
@sphuber do you have an opinion on what should be tested for rather than "command" runs (without `-r`)?
Regex on some value might be a good idea to avoid hardcoding to a certain style of output maybe?

**Comment by dev-zero** [comment]
Added a simple checking for a string from the summary and the one checking for a string from this function.

**Comment by sphuber** [comment]
Thanks @dev-zero . Doesn't hurt to have this added test without the `--raw` flag, but I think we should really just add a very simple test that directly calls the `isoformat_to_datetime` utility.

**Comment by dev-zero** [comment]
@sphuber feel free to update this PR, sorry, no time atm

**Comment by sphuber** [comment]
> @sphuber feel free to update this PR, sorry, no time atm

Might just need to give me rights to push to your branch though.

**Comment by dev-zero** [comment]
> > @sphuber feel free to update this PR, sorry, no time atm
> 
> Might just need to give me rights to push to your branch though.

Weird, "Allow edits and access to secrets by maintainers" is set (as default for all of my PRs).

**Comment by sphuber** [comment]
> > > @sphuber feel free to update this PR, sorry, no time atm
> > 
> > 
> > Might just need to give me rights to push to your branch though.
> 
> Weird, "Allow edits and access to secrets by maintainers" is set (as default for all of my PRs). Unset and set it again, let's see whether that changes something?

No it worked. I just said that in advance since last week I tried to push to one of your branches and that was refused. But I guess you already set the correct permissions since then

**Review by sphuber — APPROVED** [review]
Thanks @dev-zero

**Comment by dev-zero** [comment]
@sphuber yeah, I saw it, thanks btw for pushing that one through. No idea why that happens. Maybe it's because I'm opening the PRs with the CLI (`gh pr create`).

**Pull request merged**
