### PR TITLE
Fix profile creation in the test fixture manager

### LINKED ISSUE #4359: Pytest infrastructure seems to be broken
### Describe the bug

Recently, the tests that are run on top of the `aiida-core:latest` image started to fail with the following error:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

../conda/lib/python3.7/site-packages/aiida/engine/launch.py:77: in run_get_pk

    runner = manager.get_manager().get_runner()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:251: in get_runner

    self._runner = self.create_runner()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:285: in create_runner

    settings['communicator'] = self.get_communicator()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:163: in get_communicator

    self._communicator = self.create_communicator()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:185: in create_communicator

    url = profile.get_rmq_url()

../conda/lib/python3.7/site-packages/aiida/manage/configuration/profile.py:344: in get_rmq_url

    protocol=self.broker_protocol,

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiida.manage.configuration.profile.Profile object at 0x7fbfaa172150>

    @property

    def broker_protocol(self):

>       return self._attributes[self.KEY_BROKER_PROTOCOL]

E       KeyError: 'broker_protocol'
```

### Steps to reproduce

1. Install latest aiida-core
2. Run test calculation that rely on aiida-pytest infrastructure.

### Examples of errors.

aiida-cp2k: https://travis-ci.org/github/aiidateam/aiida-cp2k/builds/725311241
aiida-raspa: https://travis-ci.org/github/yakutovicha/aiida-raspa

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #4359 

The test profile provided by the test fixture manager was broken after
the recent added feature where the broker configuration becomes
configurable. Since the test fixture uses custom code to create the
profile that is not tested in the test suite of `aiida-core`, it went
unnoticed that it was not updated to also include the broker
information. Adding the broker defaults fixes the problem, but really
the fixture code should be rewritten to not have its own profile
generation code.

### CODE REVIEW

**Comment by sphuber** [comment]
@yakutovicha and @greschd this fixes the problem, at least I have tested this to work for `aiida-quantumespresso` locally, whereas on `develop` the tests are broken, however, this is a patch of a bigger problem. Really the test fixture code needs to be badly refactored and tested.

**Review by greschd — APPROVED** [review]
Thanks @sphuber , I think it's important we "hot-fix" this now.

As for the refactoring: I'm not intimately familiar with either of these parts (test or "normal" profile creation), so I can't really comment on it. Do you want to make a new issue for that?

**Comment by sphuber** [comment]
> Thanks @sphuber , I think it's important we "hot-fix" this now.

Agree, specially since I cannot work on this now. @yakutovicha if you can just verify that this fix solves your issue, then I will merge it.

> As for the refactoring: I'm not intimately familiar with either of these parts (test or "normal" profile creation), so I can't really comment on it. Do you want to make a new issue for that?

If we merge this in this state, then yes, we should open a new issue for that. The `aiida.manage.tests` code should use the same code as `verdi setup` to create new profiles, because now it manually hacks things together, giving rise to this undetected bug.

**Review by yakutovicha — APPROVED** [review]
Tested, checked - tests seem to run without a problem now.
Screenshot 2020-09-09 at 15 26 06

**Pull request merged**
