### PR TITLE
Dependencies: update requirement `sphinx~=4.0`

### LINKED ISSUE #5367: readthedocs build failing
See https://readthedocs.org/projects/aiida-core/builds/16126865/

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/stable/lib/python3.8/site-packages/markupsafe/__init__.py)

tagging @chrisjsewell @sphuber

### LINKED ISSUE #5373: Dependencies: update Sphinx requirement
Sphinx v4.0 has been out for a while and we should upgrade for the documentation

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5373 

The builds on ReadTheDocs started failing. This was due to release `v2.1`
of `markupsafe` that removed the module `markup_safe`. The version of
`jinja==2.11.3` that was getting installed still imported this. This
version is no longer supported and so they won't be fixing this
incompatibility but instead one should use `jinja>3.0`. This is already
a requirement for `aiida-core`, but the version of `sphinx~=3.2.1` that
we were installing had an upper limit on `jinja` to not install v3
causing the version of jinja to be downgraded. The solution is to update
the version of sphinx which no longer has this limitation of `jinja`.

Finally, we need to require `sphinx~=4.1`, because `v4.0.x` puts an
upper limit `markupsafe<2.0` which is incompatible with `jinja~3.0` but
this upper limit was removed later on.

### CODE REVIEW

**Comment by sphuber** [comment]
Dependency hell :cry: think this solves the dependency requirement mess, but in upgrading sphinx, there are now 800 freaking warnings in the docs for some reason. WIll have to look into those later

**Comment by chrisjsewell** [comment]
> but in upgrading sphinx, there are now 800 freaking warnings in the docs for some reason.

You don't think I'd tried this before, and aborted for the same reason 😅

**Comment by sphuber** [comment]
With `sphinx~-4.0` we are getting the following class of new warnings that fail the build because we use the nitpick option:

1. `WARNING: more than one target found for cross-reference`: most if not all of these are simply our own aliases in module init files such as `aiida.manage.Config, aiida.manage.configuration.config.Config, aiida.manage.configuration.Config`. For some reason Sphinx v4 no longer understands these aliases. Seems to be an unsolved issue. See [[1]](https://www.mail-archive.com/sphinx-users@googlegroups.com/msg04797.html)[[2]](https://github.com/sphinx-doc/sphinx/issues/4961)
2. `WARNING: py:class reference target not found` These include external as well as internal references.
3. `WARNING: duplicate object description of aiida.tools.data.orbital.orbital.Orbital, other instance in reference/apidoc/aiida.tools.data, use :noindex: for one of them` quick scan seems to suggest that it basically is just the `reference/apidoc` folder being the problem, which is the autogenerated API docs through `sphinx-apidoc`.

**Comment by sphuber** [comment]
Closing this for now

**Pull request closed without merging**
