### PR TITLE
`Process`: raise when `exposed_outputs` gets non-existing `namespace`

### LINKED ISSUE #5261: Missing/misspelled namespace argument to exposed_outputs leads silently dismissing outputs
### Describe the bug

When exposing outputs from a subworkchain into a output namespace with an erroneous namespace (either missing or misspelled) the operation fails silently and the outputs are not registered.

### Steps to reproduce

Below is an example modified from the [documentation on exposing inputs/outputs](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/workflows/usage.html#topics-workflows-usage-workchains-expose-inputs-outputs)

```python
from aiida import orm
from aiida.engine import WorkChain, ToContext, run

class ChildWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.input('a', valid_type=orm.Int)
        spec.input('b', valid_type=orm.Float)
        spec.input('c', valid_type=orm.Bool)
        spec.outline(cls.do_run)
        spec.output('d', valid_type=orm.Int)
        spec.output('e', valid_type=orm.Float)
        spec.output('f', valid_type=orm.Bool)

    def do_run(self):
        self.out('d', self.inputs.a)
        self.out('e', self.inputs.b)
        self.out('f', self.inputs.c)
        
class SimpleParentWorkChain(WorkChain):

    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.expose_inputs(ChildWorkChain)
        spec.expose_outputs(ChildWorkChain, namespace='child')
        spec.outline(cls.run_child, cls.finalize)

    def run_child(self):
        child = self.submit(ChildWorkChain, **self.exposed_inputs(ChildWorkChain))
        return ToContext(child=child)

    def finalize(self):
        self.out_many(
            self.exposed_outputs(self.ctx.child, ChildWorkChain, namespace='clhid')
        )

result = run(SimpleParentWorkChain, a = orm.Int(1), b=orm.Float(10.0), c=orm.Bool(False))
print(result) #{}
```
submitting the ``SimpleParentWorkChain`` will lead to empty outputs with no indication that something is wrong

### Expected behavior

Some kind of error should be thrown

### Your environment

- Operating system [e.g. Linux]: Linux
- Python version [e.g. 3.7.1]: 3.8.10
- aiida-core version [e.g. 1.2.1]: 1.6.5

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5261 

Up till now, a call to `exposed_outputs` providing a `namespace` as
argument that doesn't exist, i.e., no outputs were ever exposed in that
namespace, would simply be a no-op. Given that this would often be
because the namespace was accidentally misspelled, the error would go
unnoticed and the process would finish without error message.

To prevent this situation that is difficult to debug, the method will
now raise a `KeyError` if the top-level namespace does not exist.

### CODE REVIEW

**Comment by sphuber** [comment]
@janssenhenning I think this should fix the problem as now it will throw an exception. Let us know what you think of that solution.

**Comment by janssenhenning** [comment]
@sphuber Thank you for the quick fix. Judging from the test this is the behaviour I would like 👍.
I have one question: Does this also prevent the case, where the ``namespace`` argument is missing from the ``exposed_outputs`` call but the output was exposed with a namespace? If not, would it also be possible to catch this case?

**Comment by sphuber** [comment]
> Does this also prevent the case, where the `namespace` argument is missing from the `exposed_outputs` call but the output was exposed with a namespace? If not, would it also be possible to catch this case?

No it does not. This would also be more tricky to do. For example, imagine a process that exposes a process _without_ namespace and a process _with_ a namespace. If the parent process then calls `exposed_outputs` _without_ namespace on accident, there is no way to know for the code whether this was actually an accident or intended. I would say that this case is therefore not really possible to solve in a robust and general way.

**Comment by janssenhenning** [comment]
Okay I see. The current solution seems fine to me

**Comment by sphuber** [comment]
@ramirezfranciscof could you give this a look? It is not a big one and would be good to get merged for v2.0

**Comment by sphuber** [comment]
@chrisjsewell @ramirezfranciscof let me know if you want to still give this a look. Otherwise I am merging tomorrow

**Pull request merged**
