### PR TITLE
verdi computer/code duplicate now reuses prepend_text and append_text

### LINKED ISSUE #3747: Duplication of codes and computers via 'verdi' does not duplicate prepend and append text
Using `verdi code duplicate` or `verdi computer duplicate` duplicates all the standard one-line fields, but the prepend and append texts are not pre-filled.

It would be a nice quality-of-life improvement if these too could be duplicated and then just modified when the editor is opened at the end the `verdi` command.  

Example use case - with QuantumESPRESSO one must setup many executables as codes, but on a cluster these are all typically loaded using a single module. The prepend text, for example, might be `module load qe-6.5.0` and is the same in every case, but is necessary to ensure that the linked libraries are available.

### PR DESCRIPTION
**Pull request by giovannipizzi**
This required adding a new ContextualDefaultOption class
to get a default callable that also receives the context.
Moreover, a but was fixed in the function that prompts
for the prepend/append_text, as if the file was not touched/modified,
instead of reusing the text provided in input, an empty text was used instead.

Fixes #3747

### CODE REVIEW

**Comment by giovannipizzi** [comment]
@ConradJohnston could you check that this work as you expect? If this is the case, after adding tests this is ready to merge

**Review by ConradJohnston — DISMISSED** [review]
Works great, thank you.

One curiosity - why does duplicate allow me to have identical labels for the code?
If one uses orm.Code.get_from_string(), it complains unless the code@computer label is unique.
I understand that this isn't the ID on which uniqueness is enforced, but given that there are convenience functions which do use this label, should we warn the user? Will make a separate issue if you agree that it's an oddity.

**Comment by ltalirz** [comment]
> given that there are convenience functions which do use this label, should we warn the user? 

We should, and there already is an issue for it https://github.com/aiidateam/aiida-core/issues/3303

**Comment by giovannipizzi** [comment]
Thanks @ConradJohnston !

Do you happen to have time to add a test, by chance? I'll be a bit busy in the next days and if we have tests we can merge this.

**Comment by ConradJohnston** [comment]
@giovannipizzi , yes, I'll try to get looking at it as soon as possible.

**Comment by ConradJohnston** [comment]
@giovannipizzi , have test coverage now. Can I push back to your branch?

**Comment by giovannipizzi** [comment]
@ConradJohnston sure, thanks a lot! I just added you as a collaborator to my fork - not sure if this means you can push, in case you cannot I can set this after you accept the invite (GitHub might have changed this workflow recently? I remember I could set the role while inviting...)

**Comment by ConradJohnston** [comment]
> @ConradJohnston sure, thanks a lot! I just added you as a collaborator to my fork - not sure if this means you can push, in case you cannot I can set this after you accept the invite (GitHub might have changed this workflow recently? I remember I could set the role while inviting...)

Hi Giovanni , I've pushed my change now, so we'll need another reviewer. 
Actually, the tests did already cover the duplication of these texts, so all I did was to ensure that the test code and computer objects have something other than an empty string for their prepend/append texts.

**Comment by giovannipizzi** [comment]
Thanks a lot @ConradJohnston!
Indeed you are right, great (also better, it was an easier fix ;-) )

I cannot approve this myself - either you reprove it, or maybe @sphuber could approve and merge?

**Review by sphuber — APPROVED** [review]
Thanks guys

**Pull request merged**
