### PR TITLE
ORM: Add the `Entity.get_collection` classmethod

### LINKED ISSUE #6105: Computer.configure does not use the Computer instance backend (.collection issue?)
Following yesterday discussion with @sphuber and @giovannipizzi 

I'm using aiida v2.4.0 on Python 3.11.5
Take the following code

```
import aiida
import aiida.orm
import aiida.storage.sqlite_temp.backend as sqtemp

#create an in-memory backend
profile = sqtemp.SqliteTempBackend.create_profile()
backend = sqtemp.SqliteTempBackend(profile)

# create a new computer

comp = aiida.orm.Computer(backend=backend, label='localhost', hostname='localhost', transport_type='core.local', scheduler_type='core.direct', workdir='/tmp/aiida')

#create a new user

user = aiida.orm.User(backend=backend, email='pippo@localhost')

user.store()

print(f'user stored {user}')

# configure the computer for the user

#remove comment to reproduce the error
#comp.configure(user=user)

authinfo = aiida.orm.AuthInfo(comp, user, backend=backend)
authinfo.store()

comp.store()
```
This works as expected. But if I use the `configure` method of the Computer class I get the following:
```
user stored pippo@localhost
Traceback (most recent call last):
  File "/home/bertossa/pippo/aiida_test.py", line 23, in <module>
    comp.configure(user=user)
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/orm/computers.py", line 681, in configure
    authinfo = self.get_authinfo(user)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/orm/computers.py", line 574, in get_authinfo
    authinfo = authinfos.AuthInfo.collection(self.backend).get(dbcomputer_id=self.pk, aiidauser_id=user.pk)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/common/lang.py", line 99, in __get__
    return self.getter(owner)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/orm/entities.py", line 184, in collection
    return cls._CLS_COLLECTION.get_cached(cls, get_manager().get_profile_storage())
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/manage/manager.py", line 242, in get_profile_storage
    raise ConfigurationError(
aiida.common.exceptions.ConfigurationError: Could not determine the current profile. Consider loading a profile using `aiida.load_profile()`.
```

An issue very similar to this one (code that is not using the profile stored in the orm class) is found in this function

https://github.com/aiidateam/aiida-core/blob/517ffcb1c5ce32f281589432cde1d58588fa83e0/aiida/orm/nodes/data/upf.py#L73

where again a call to .collection triggers the global profile loading

I think it is natural to expect that a method of an orm class uses the same backend that was used to instantiate the class, but I think this is not happening everywhere.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #6105

### CODE REVIEW

**Comment by sphuber** [comment]
@rikigigi

**Comment by rikigigi** [comment]
Thank you @sphuber ! I will do some test soon

**Comment by rikigigi** [comment]
I feel that we are still missing many points where we use the global backend and not the instance backend, see for example https://github.com/sphuber/aiida-core/pull/14 that makes it only for my use case that is the initialization of a ready-to use aiida database.

**Comment by sphuber** [comment]
Thanks @rikigigi . I have merged your PR. I have found some additional places as well and merged that with your commit. I have now thoroughly searched all the code in `aiida.orm` to check that the collection is always properly instantiated with the correct backend, and if an entity creates another entity it passes its own backend. I think this should fix the majority of cases, even though it remains of course possible that we have missed some

**Pull request merged**
