### PR TITLE
Add capability to download orm.ArrayData from REST-API

### LINKED ISSUE #2809: Rest api: add endpoint to download ArrayData
Currently the endpoint is provided to get general information of ArrayData but there is no endpoint available to download the raw data (numpy array) stored in ArrayData.

Add endpoint for ArrayData to get the size of the raw data and also to download it.

### PR DESCRIPTION
**Pull request by JPchico**
Right now it is not possible to access the arrays stored in the db via the REST-API.

To try to solve this a simple option to download the data in a JSON format has been added.
The function creates a dictionary where the keys are the `arraynames` and the values are lists obtained from the numpy arrays via the `.tolist()` method.

This dictionary is then converted into JSON format so that the user can obtain the contents of the arrays via a REST request in the form
`http://127.0.0.1:5000/api/v4//nodes/UUID_OF_ARRAY/download?download_format=json`.

closes #2809

### CODE REVIEW

**Comment by JPchico** [comment]
Hi @chrisjsewell ! I was looking at the serialization of the numpy arrays to see if one can make it more in the spirit of what is done the `JsonableData`. As numpy arrays do not have the `as_dict` method, the dictionary would need to be something like this
```
json_dict = {
    'array_name': {
        '@class': obj.__class__.__name__,
        '@module': obj.__class__.__module__,
        'data': obj.tolist()
    }
}
```
However, the `@class` and `@module` entries would always be `ndarray` and `numpy` respectively. So I'm not too sure about whether this would be useful. One could add an entry for the `'dtype':  obj.dtype` which might be useful.

Regarding the sanitation of the `np.nan` to make the array json compatible, one could use something like what is used in 
https://github.com/aiidateam/aiida-core/blob/0772f3323f0817c1c63cc87d6841d630578f9ece/aiida/orm/nodes/data/jsonable.py#L90-L108

instead of transforming the json variables to float one would do it the other way around transforming the float/numpy variables to strings (e.g. `np.nan -> 'NaN'`). However, a lot of this is already taken care of by the `json.dumps` `ignore_nan=True` option, at least with regards to the `np.nan`. 

So in my opinion the current approach is quite good, one can make the modifications I raise here, but I'm unsure on whether it is something that it would be necessary.

**Comment by chrisjsewell** [comment]
> However, the @class and @module entries would always be ndarray and numpy respectively. So I'm not too sure about whether this would be useful.

Heya, the other reason I would say this is probably not the way to go, is that the REST API should really provide language agnostic data, e.g. if the client was written in JavaScript, then there is not really anything it can do with a Python class & module

**Comment by JPchico** [comment]
Hi @chrisjsewell ! I was looking at the serialization of the numpy arrays to see if one can make it more in the spirit of what is done the `JsonableData`. As numpy arrays do not have the `as_dict` method, the dictionary would need to be something like this
```
json_dict = {
    'array_name': {
        '@class': obj.__class__.__name__,
        '@module': obj.__class__.__module__,
        'data': obj.tolist()
    }
}
```
However, the `@class` and `@module` entries would always be `ndarray` and `numpy` respectively. So I'm not too sure about whether this would be useful. One could add an entry for the `'dtype':  obj.dtype` which might be useful.

Regarding the sanitation of the `np.nan` to make the array json compatible, one could use something like what is used in 
https://github.com/aiidateam/aiida-core/blob/0772f3323f0817c1c63cc87d6841d630578f9ece/aiida/orm/nodes/data/jsonable.py#L90-L108

instead of transforming the json variables to float one would do it the other way around transforming the float/numpy variables to strings (e.g. `np.nan -> 'NaN'`). However, a lot of this is already taken care of by the `json.dumps` `ignore_nan=True` option, at least with regards to the `np.nan`. 

So in my opinion the current approach is quite good, one can make the modifications I raise here, but I'm unsure on whether it is something that it would be necessary.

> > However, the `@class` and `@module` entries would always be ndarray and numpy respectively. So I'm not too sure about whether this would be useful.
> 
> Heya, the other reason I would say this is probably not the way to go, is that the REST API should really provide language agnostic data, e.g. if the client was written in JavaScript, then there is not really anything it can do with a Python class & module

Hi @chrisjsewell I agree, in my opinion the current implementation gives you basically what you need, the arrays are written as python lists, which transform to JSON arrays. The only thing I can think to make it more flexible is the explicit writing of `NaN` and `Infinity`.  Otherwise I think this is pretty much done. Do you agree?

**Comment by JPchico** [comment]
Hi @chrisjsewell ! Just wanted to double check if you thought that the last suggestion was needed to be able to merge the PR, or if there is something else that need to be done. It would be nice to have this as part of the main branch (even if the REST-API might change to GraphQL later)

**Review by sphuber — APPROVED** [review]
Thanks @JPchico . I hadn't reviewed this because I typically am not involved much with the REST API and its developments, but I think we should decide on this PR. For me this would be fine to merge. @chrisjsewell or @ltalirz if you still want to have a look, let me know by tomorrow otherwise I will merge this.

**Comment by sphuber** [comment]
@chrisjsewell any objections to merging this today?

**Comment by chrisjsewell** [comment]
> any objections to merging this today?

eurgh, yeh sure. I don't foresee this being part of the future REST-API, but don't want to block on it.

**Comment by chrisjsewell** [comment]
the merge conflict need to be fixed first though obviously

**Comment by chrisjsewell** [comment]
> I don't foresee this being part of the future REST-API

Not that there is anything specifically wrong with this PR FYI. Just the whole of `aiida/restapi` lol

**Comment by sphuber** [comment]
Since the interface doesn't allow to resolve the conflicts online, I had to do it locally and had to make a new PR #5425

**Comment by sphuber** [comment]
Thanks for your contribution @JPchico ! And apologies for the long wait.

**Pull request closed without merging**
