### PR TITLE
Dependencies: Restrict Python to strictly below 3.13

### PR DESCRIPTION
**Pull request by agoscinski**
Recstrict Python version ito strictly below 3.13 until we have resolved the dependency issues in PR #6600.

### CODE REVIEW

**Comment by sphuber** [comment]
Not saying we shouldn't do this, but is this really necessary? Our own code is compatible with Python 3.13. It is just that certain dependencies aren't. Adding this limitation is not going to do much then, right? Especially not if we are not going to release it soon. By the time we would release it we will probably be compatible with 3.13 anyway and we would have to remove it again. So far we have never imposed an explicit limit and it has never caused issues. I am also not aware that this is recommended as a best practice by the PyPA.

**Comment by danielhollas** [comment]
Yeah, I think this is actually discouraged, to the point where for example `uv` ignores maximum python version limits when installing dependencies (I think).

**Comment by agoscinski** [comment]
> Yeah, I think this is actually discouraged, to the point where for example uv ignores maximum python version limits when installing dependencies (I think).

Read the same https://github.com/astral-sh/uv/issues/8374#issuecomment-2424246009

There is a huge discussion about it, but I don't see any result comig from it
https://discuss.python.org/t/requires-python-upper-limits/12663/80
The metadata field is used by some like pyreads https://pyreadiness.org/3.13/ but the problem that you install Python 3.13 because it is the newest and then AiiDA crashes remains to me. I don't see a simple solution for this.

**Comment by agoscinski** [comment]
Since we agreed for the release to not include it, this can be closed. If this comes up again as a general discussion one can open an issue.

**Comment by danielhollas** [comment]
The main issue is, even if you did include it in the release it would be
kind of pointless, since the resolver would simply backtrack to the
previous version that did not include the constraint. :-/

Dne st 6. 11. 2024 6:38 uživatel Alexander Goscinski <
***@***.***> napsal:

**Comment by sphuber** [comment]
> The main issue is, even if you did include it in the release it would be
kind of pointless, since the resolver would simply backtrack to the
previous version that did not include the constraint. :-/

:point_up:  That is exactly it.

**Comment by sphuber** [comment]
Another interesting and well laid out point of view just for reference: https://iscinumpy.dev/post/bound-version-constraints/

**Pull request closed without merging**
