### PR TITLE
Fix/issue 4850

### PR DESCRIPTION
**Pull request by csadorf**

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
Cool, thanks for the fix @csadorf ! So were `pytest-cov` and `jupyter-client` the culprits?

One question though before aproving: the extra function you are adding, you used it to look for the problematic dependency and now want to add it for future use in similar cases, or is it part of the fix in some way I'm missing?

**Comment by csadorf** [comment]
> Cool, thanks for the fix @csadorf ! So were `pytest-cov` and `jupyter-client` the culprits?
>

Yes, I believe those were the culprits. 

> One question though before aproving: the extra function you are adding, you used it to look for the problematic dependency and now want to add it for future use in similar cases, or is it part of the fix in some way I'm missing?

I thought it would be useful to maintain the function for the next time we encounter such an issue. I could also move it to #4852, might be more appropriate, just let me know.

**Comment by ramirezfranciscof** [comment]
Nah, that's fine. Also I don't know why the jenkins CI of the branch got stuck if the PR one worked, but I guess if the last one passed it should be ok.

**Review by ramirezfranciscof — APPROVED** [review]
Thanks, good to go!

**Comment by ramirezfranciscof** [comment]
@csadorf should I merge or were you still waiting for @chrisjsewell review?

**Comment by chrisjsewell** [comment]
I added unpinning to https://github.com/aiidateam/aiida-core/issues/4647

**Comment by csadorf** [comment]
> @csadorf should I merge or were you still waiting for @chrisjsewell review?

Please go ahead and merge. 👍

**Pull request merged**
