### PR TITLE
Disallow pickle when storing numpy array in ArrayData

### PR DESCRIPTION
**Pull request by greschd**
Following the discussion in #3411.

### CODE REVIEW

**Comment by greschd** [comment]
We could also add ``allow_pickle=False`` on the load method: In principle it's not necessary because the ``numpy`` version required by ``aiida-core`` does that already, but it's possible some people have an older version installed for some reason.

**Comment by sphuber** [comment]
If we decide that this is always the behavior we want, I would vote for also putting it explicitly on the load method, just in case `numpy` ever decide to change the default (not very likely, but still).

**Comment by greschd** [comment]
Ok, I updated it accordingly.

**Comment by sphuber** [comment]
@giovannipizzi I would be OK with this change with the idea "better safe than sorry".

**Comment by sphuber** [comment]
Thanks a lot @greschd

**Pull request merged**
