### PR TITLE
Not from forked to trigger full docker CI of Fix/6448/s6 notification polling check

### LINKED ISSUE #6448: Replace the sleep in `aiida-prepare.sh` startup script of Docker images with more clever solution
See changes in #6445 that added a sleep in `aiida-prepare.sh` before `verdi presto` is called.
Ideally this is handled with an actual healthcheck, perhaps provided by s6.
See https://github.com/just-containers/s6-overlay/issues/582

### PR DESCRIPTION
**Pull request by unkcpz**
Fixes #6448 

see #6469, this is to trigger the push to ghcr.io

### CODE REVIEW

**Comment by danielhollas** [comment]
@unkcpz very strange that the docker.yml workflow was not triggered here.But in any case I've just triggered it via workflow dispatch.

https://github.com/aiidateam/aiida-core/actions/runs/9500519783

**Comment by unkcpz** [comment]
Thanks @danielhollas 

@sphuber can you test run with the built image 

```
docker run --rm -it ghcr.io/aiidateam/aiida-core-with-services:fix-6448-s6-notification-polling-check bash
```

**Comment by sphuber** [comment]
> Thanks @danielhollas
> 
> @sphuber can you test run with the built image
> 
> ```
> docker run --rm -it ghcr.io/aiidateam/aiida-core-with-services:fix-6448-s6-notification-polling-check bash
> ```

I get the same problem:
```
s6-rc: info: service postgresql-init successfully started
s6-rc: info: service postgresql: starting
waiting for server to start.... done
server started
s6-rc: info: service postgresql successfully started
Error:
RabbitMQ on node rabbit@localhost is not running or has not fully booted yet (check with is_booting)
s6-rc: info: service postgresql-prepare successfully started
Error:
RabbitMQ on node rabbit@localhost is not running or has not fully booted yet (check with is_booting)
 completed with 0 plugins.
```
it hangs there. So maybe it is a problem with my setup? I _am_ running wsl2 which may have its peculiarities. Not sure.

**Comment by unkcpz** [comment]
@sphuber sorry, I didn't notice you update in here already. Please feel free go ahead with this and close the other one.

**Comment by sphuber** [comment]
It may not have been fixed after all. I triggered the workflow through dispatch manually and there the tests failed: https://github.com/aiidateam/aiida-core/actions/runs/9888940447/job/27314039090
It seems that the script is still telling RMQ is up and running when it is not quite fully booted up, so `verdi presto` is still run too fast.

**Comment by sphuber** [comment]
Found (at least part of) the problem. Really unhelpfully, `is_running` can return `0` _even_ if it fails and the server is not yet running
```
$ sudo rabbitmq-diagnostics is_running && echo $?
Asking node rabbit@invader for its status ...
RabbitMQ on node rabbit@invader is not running or has not fully booted yet (check with is_booting)
0
```

**Comment by sphuber** [comment]
Ok, I think this combination of first running `rabbitmq-diagnostics ping` to make sure the server is even started, followed by `rabbitmq-diagnostics check_running` to make sure it if fully up and running, seems to do the trick. I can now build and run this locally, and [the build on GHA](https://github.com/aiidateam/aiida-core/actions/runs/9891716910/job/27322953151) also worked.

**Pull request merged**
