### PR TITLE
⬆️ UPDATE: psgu v0.2

### PR DESCRIPTION
**Pull request by chrisjsewell**
Does this also close any issues @ltalirz?

### CODE REVIEW

**Review by ltalirz — APPROVED** [review]
thanks @chrisjsewell 

I think I already closed the corresponding issue - I erroneously thought that 0.2.0 would be picked up automatically.

thanks for fixing

**Comment by chrisjsewell** [comment]
cheers @ltalirz, anything else you would want before an aiida-core 1.6.1 release?

**Comment by ltalirz** [comment]
nothing super urgent

this one would be nice to fix for togo I guess https://github.com/aiidateam/aiida-core/issues/4752
and then there's this https://github.com/aiidateam/aiida-core/pull/4730 which would then allow updating pyyaml

but both can be done in another release

**Comment by chrisjsewell** [comment]
> I think I already closed the corresponding issue

Do you know what the issue number was?

**Comment by ltalirz** [comment]
https://github.com/aiidateam/aiida-core/issues/4748

**Pull request merged**
