### PR TITLE
Docs: update "AiiDA internals for developers" to `aiida-core==1.0.0`

### LINKED ISSUE #3173: Check documentation for "for AiiDA developers/AiiDA internals"
Check if the section is updated to AiiDA 1.0.

https://aiida.readthedocs.io/projects/aiida-core/en/latest/developer_guide/core/internals.html

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #3173

### CODE REVIEW

**Comment by ltalirz** [comment]
thanks, there are still some conflicts - then happy to approve

**Comment by CasperWA** [comment]
> thanks, there are still some conflicts - then happy to approve

Yeah, GitHub is having some issues at the moment - already pushed the updated commits, but no luck here (see my Skype messages as well)

**Comment by sphuber** [comment]
@CasperWA  Should probably rebase instead of merging to update, if you intend to keep both commits

**Comment by CasperWA** [comment]
> @CasperWA Should probably rebase instead of merging to update, if you intend to keep both commits

Will do, thanks @sphuber. Had indeed hoped to be able to merge this before the other one to not run into this problem - oh well :)

**Comment by CasperWA** [comment]
@ltalirz, this should be ready for approval/review and merging once the tests have passed, again.

**Comment by CasperWA** [comment]
Thanks @sphuber and @ltalirz :)

**Pull request merged**
