### PR TITLE
📚 DOCS: add trove classifier for development status

### PR DESCRIPTION
**Pull request by ltalirz**
aiida-core was missing the trove classifier for the development status.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
I would put it at the top in alphabetical order

**Comment by chrisjsewell** [comment]
Ermm did you accidentally include another PR?

**Comment by ltalirz** [comment]
sorry, I had some local changes lying around.

I should finally have managed to add this single line now ;-)

**Review by chrisjsewell — APPROVED** [review]
Feel free to merge

**Pull request merged**
