### PR TITLE
Add metadata for WCI

### PR DESCRIPTION
**Pull request by ltalirz**
Add metadata for workflows community initiative, see https://workflows.community/systems

### CODE REVIEW

**Comment by ltalirz** [comment]
Already opened PR to be added to the list v

**Comment by ltalirz** [comment]
@sphuber I know this is some top-level metadata but if we want to customize our appearance on https://workflows.community/systems that's what we need to do.

Can you give this a quick look please?

**Comment by sphuber** [comment]
I take it there is no other way to provide them this information? We have been cleaning up the root directory of the repository because it was swamped with configuration files. I have to say that I am personally not a fan of starting to add config files for all sorts of external indexing sites. But if there is no other way I guess we can accept this for now

**Comment by ltalirz** [comment]
I don't think there is another way currently, but I'll open a feature request (we can always move it once/if that becomes possible).

**Review by sphuber — APPROVED** [review]
Thanks @ltalirz

**Comment by ltalirz** [comment]
Turns out they were super fast https://github.com/aiidateam/aiida-core/pull/5398

Where would you like the file to go? `docs`?

**Comment by sphuber** [comment]
Yeah `docs` makes sense

**Pull request merged**
