### PR TITLE
Bump aiida-prerequisites base image to 0.3.0

### PR DESCRIPTION
**Pull request by yakutovicha**
Changes in the new image
- Updated conda (4.9.2)
- Start ssh-agent at user's startup

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Can you explain what the difference is thanks

**Comment by yakutovicha** [comment]
> Can you explain what the difference is thanks

Added to the PR description.

**Review by ltalirz — DISMISSED** [review]
fine with me once the tests pass

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
we should also change:

https://github.com/aiidateam/aiida-core/blob/11cb38cf14b4903ca8af53127ddf78c6034c9cae/.molecule/default/Dockerfile#L1

https://github.com/aiidateam/aiida-core/blob/11cb38cf14b4903ca8af53127ddf78c6034c9cae/.jenkins/Dockerfile#L1

**Review by chrisjsewell — APPROVED** [review]

**Pull request merged**
