### PR TITLE
Update process status in the database before broadcasting that process status has changed (fix #6579)

### LINKED ISSUE #6579: Process is only stored after it  fires `ProcessListener.on_process_finished` event resulting in unfinished process in next step
Bug report from a question on discourse @t-reents https://aiida.discourse.group/t/workchain-continues-before-finishing-the-pervious-step/472 also observed by @superstar54 in the workgraph development

### Describe the bug

Already well described here https://aiida.discourse.group/t/workchain-continues-before-finishing-the-pervious-step/472

Here my results from investigating it: The workchain starts the next step before the finished process is stored in the database and thus loads the process before the process state was updated to `Finished` resulting in the nonzero exit code (`is_finished_ok` checks if the process state is running).

So on the plumpy side the event is already fired before the process is stored in the database. A simplified backtrace of 
the process that fires the event (I guess broadcasting) that it finishes, and by that continuing the next process before it updated its `process_state`:
In the `aiida.engine.processes.process.Process.on_entered` function
https://github.com/aiidateam/aiida-core/blob/c7c289d3892bf76894714f53f58b7ce5b0761178/src/aiida/engine/processes/process.py#L422
the parent method is invoked that is in plumpy
https://github.com/aiidateam/plumpy/blob/b3837fc9dbf7dc5aca0785e93b94cf5b89d04a91/src/plumpy/processes.py#L701
This invokes much later
https://github.com/aiidateam/plumpy/blob/b3837fc9dbf7dc5aca0785e93b94cf5b89d04a91/src/plumpy/processes.py#L837-L840
```python
        self._fire_event(ProcessListener.on_process_finished, self.future().result())
```
that broadcasts the event to all processes resulting in the next process being continued. The update of the process state to `Finished` in the database (the object's process state has been updated but not in the database!) happens later in the `aiida.engine.processes.process.Process.on_entered`function
https://github.com/aiidateam/aiida-core/blob/c7c289d3892bf76894714f53f58b7ce5b0761178/src/aiida/engine/processes/process.py#L442

I will try to switch the events and see what it breaks.

### Environment

I think it happens on all AiiDA version (tried newest 2.6.2 and 2.2) and all backends, since this looks like a bug in the engine.

# Supplementary

Backtrace log of up to the `_fire_event` [backtrace.log](https://github.com/user-attachments/files/17254342/backtrace.log)

### PR DESCRIPTION
**Pull request by agoscinski**
Fix for #6579

Processes start to broadcast their event before they update their process status in the database. This can cause issues if the next process directly tries to access the last process state retrieving it from the database while it has not been updated in the database.

TODO: test

### CODE REVIEW

**Comment by agoscinski** [comment]
I guess the CI failure is because of some unrelated problems.

I would like to have some feedback if anyone sees if this causes problems somewhere else. The tests pass so far.

**Review by sphuber — CHANGES_REQUESTED** [review]
Thanks a lot for tracking this one down @agoscinski and @t-reents . This one is my fault. I changed the behavior in this method [two months ago](https://github.com/aiidateam/aiida-core/commit/cbf672f1ddf13b3b56b7f3666a7ed2a014bde0cc) to make sure a node was sealed when it excepted. I was thinking about the location of the `super` call and didn't remember why I moved it to the beginning originally, so I moved it back. Bad mistake! My comment on line 429 even explicitly reminded myself that attaching outputs _has_ to happen before calling the parent, I just put "for reasons unknown". I guess we now know :D Could you perhaps please update the comment and replace/

> For reasons unknown, it is important to update the outputs first, before doing anything else, otherwise there is the risk that certain outputs do not get attached before the process reaches a terminal state.

with 

> The updating of outputs and state has to be performed before the `super` is called because the super will broadcast state changes and parent processes may start running again before the state change is completed. It is possible that they will read the old process state and outputs that they check may not yet have been attached

**Comment by agoscinski** [comment]
@sphuber Added your test, but on the place where the super is invoked. Also added a test now.

**Review by sphuber — APPROVED** [review]

**Comment by danielhollas** [comment]
> This one is my fault. I changed the behavior in this method two months ago to make sure a node was sealed when it excepted. I was thinking about the location of the super call and didn't remember why I moved it to

Just to clarify, which versions are affected by this bug? The linked issues mentioned that the bug is present in both 2.2 and 2.6 but that doesn't seem in line with the comment above?

**Comment by sphuber** [comment]
The bug has never been released, it was just sitting on `main`

**Comment by agoscinski** [comment]
> The linked issues mentioned that the bug is present in both 2.2

I think when I did the test my aiida-core upgraded at the installation of the pseudo potential, so this was wrong. At least I don't get the bug in 2.6.1. I'll correct it in the issue. But the bug was released for 2.6.2 https://github.com/aiidateam/aiida-core/blob/v2.6.2/src/aiida/engine/processes/process.py#L421

**Comment by danielhollas** [comment]
Thank, makes sense. So I guess it would make sense to push a new patch release, and I'll have to then upgrade aiida-core in AiiDAlab image which now uses 2.6.2

**Comment by sphuber** [comment]
Ah @agoscinski is right, it _was_ released. I just quickly looked at [the commit where the change was introduced](https://github.com/aiidateam/aiida-core/commit/cbf672f1ddf13b3b56b7f3666a7ed2a014bde0cc) and Github didn't show any associated tags, which is usually a useful feature. However, I forgot that in this case, we made the release from a support branch and so the linked commit was cherry-picked onto the support branch before being released, and so the tag didn't show.

**Pull request merged**
