### PR TITLE
Add repository issue templates

### LINKED ISSUE #4121: Add Issue Templates for GitHub
Along the lines of: https://github.com/executablebooks/MyST-Parser/tree/master/.github/ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by chrisjsewell**
As the title suggests! I have also copied them to this repository, so you can see how they look: https://github.com/chrisjsewell/issues_test/issues/new/choose

closes #4121

### CODE REVIEW

**Comment by greschd** [comment]
I'd be in favor of adding a "blank" template, for cases which don't neatly fall into one of the categories.

For example, #3764 is a bug report / feature request where the user has already identified the root cause of the issue. In that case, I think adding all the environment / steps to reproduce / etc. of the bug report is just unnecessary noise.

Of course you can just delete the template once selected, but it creates a mental barrier to doing so.

**Comment by chrisjsewell** [comment]
> I'd be in favor of adding a "blank" template, for cases which don't neatly fall into one of the categories.

Note, there is the option for this at the bottom of the form:

image

**Comment by greschd** [comment]
Ah, yeah.. guess I missed it because it doesn't get that much screen real estate. Anyway, in that case I think it's fine as is.

**Comment by chrisjsewell** [comment]
Yes I imagine when any of us open an issue, we will probably just use the blank template, in which case this unnecessary boiler plate. But for new users I think it could be quite useful, and allows us to also point them towards other places they can look first; like the troubleshooting documentation and the mailing list.
But anyway, I will leave it to @giovannipizzi and @sphuber to decide if they think it is worthwhile 😁

**Comment by sphuber** [comment]
Is there anyway to test and see what this looks like? In principle I am not opposed but so far we have had very little issues from external users that are not clear enough, so currently I don't feel this is really necessary. This might of course change in the future

**Comment by chrisjsewell** [comment]
> Is there anyway to test and see what this looks like?

I don't know of a way to preview directly on this repo, but as I mention above, this link is a direct replica of what you will see:
https://github.com/chrisjsewell/issues_test/issues/new/choose

**Comment by sphuber** [comment]
So for us to create an issue we would have an intermediate page where we need to click on one button and then remove the context. This is not too much of a hassle, but I doubt that the benefits really outweigh the downsides for now, simply since it is mostly us creating the majority of issues and we don't really need to be that specific oftentimes

**Comment by chrisjsewell** [comment]
> click on one button and then remove the context. 

Yes it's essentially an extra click, but you don't need to remove anything just click on the bottom blank issue link:

image

> but I doubt that the benefits really outweigh the downsides for now

I'm not fussed either way, just wanted to bring it up as a suggestion

**Comment by sphuber** [comment]
> I'm not too fussed either way, just wanted to bring it up as a suggestion

Cheers for that. I think it is not necessary right now, but I don't mind adding it either if others think it is a useful addition.

**Comment by sphuber** [comment]
OK, in that case we will add it for now. If we get reports that is disturbs more than that it helps, we can remove it

**Comment by chrisjsewell** [comment]
> OK, in that case we will add it for now. If we get reports that is disturbs more than that it helps, we can remove it

👍 
I've personally found it helpful on repos, especially when getting lots of "new users" raising issues. But if it becomes a hindrance to developers, then by all means drop it

**Pull request merged**
