### PR TITLE
WIP: Restructured the detailed job info from SLURM

### PR DESCRIPTION
**Pull request by espenfl**
This is work in progress and the first attempt to realize:

- a standardized way to return detailed job info, ideally the keys should be available to all schedulers
- a way to pick the exit code from the detailed job info
- a way to, if the exit code is larger than zero, parse the files of the scheduler in order to give a more sensible exit code to the calculation/workchain

The last point is crucial as a lot of calculations for instance hit memory issues and need to be restarted with different memory and node/cpu configurations. Corrections need to be performed on the calculation plugin as the way to correct might be different based on input and job configuration.

What still remains:

- a parser to analyze the schedulers stdout and stderr (should reside in the `scheduler.plugins.somescheduler`)
- a nice way to return an exit code or information about why the job is listed as `Done`, but still not okey

Some questions:
- how do I get access to the schedulers stdout and stderr in `scheduler.plugins.somescheduler`?
- should we introduce a `Failed` state in addition to the `Done`?

### CODE REVIEW

**Comment by espenfl** [comment]
Okey, it seems there is no existing parser for the stdout and stderr of SLURM. Problem is that the exit code is inherited from the bash script return code. Some packages do not return sensible exit codes rendering the inspection of the exit code itself rather useless. However, at least for memory overflow, a message exists and is dumped in stdout/stderr, but there is no record of that in  `sacct` for instance. So it seems we would have to write a simple parser.

Happy to do this, but right now I am a bit unsure how to access the schedulers stdout and stderr from `scheduler.plugins.somescheduler`.

**Comment by espenfl** [comment]
Investigating this a bit further it seems the sensible approach would be to do the following:

- make sure we have an entry under `JobInfo()` that contains the detailed job information (exit codes)
- implement parsers of stdout/stderr in `schedulers.plugins.somescheduler`
- inspect the exit code, if not zero, trigger parser and raise a defined exit code on the AiiDA side

In order to do the last step we need to decide where to put the exit codes. I am a bit tempted to suggest that we implement the same stuff that is now sitting on the calculation and workchain for the scheduler, e.g. putting it on `JobInfo()` or something similar. Then, on the plugin side we can modify those returns by issuing something like `get_scheduler_exit_status` (which would have to be implemented of course). It would just be a shortcut to fetch the exit status in the `JobInfo()` dict.

Is this the way to go? Other suggestions? Would be nice to have something rolling in not too distant of future as this stuff is really hindering production runs.

**Comment by ltalirz** [comment]
Just mentioning this is related to #2431 and @FelixBoelle is interested in this topic as well

**Comment by sphuber** [comment]
Superseded by PR #3906 and #3931

**Pull request closed without merging**
