### PR TITLE
♻️ REFACTOR: verdi export/import -> verdi archive

### LINKED ISSUE #4599: Add `verdi archive` that replaces `verdi export` and `verdi import`
The commands `verdi export` and `verdi import` are to be deprecated and will be joined into `verdi archive`.

### PR DESCRIPTION
**Pull request by chrisjsewell**
This commit deprecates `verdi export` and `verdi import` and combines them into `verdi archive`.

Deprecated groups/commands are hidden (so they don't show in `verdi --help`) and decorated with `deprecated_command`.

closes #4599

### CODE REVIEW

**Comment by ltalirz** [comment]
I'll unsubscribe here for the moment; if my review is needed, just ping me again

**Review by yakutovicha — COMMENTED** [review]
Thanks a lot @chrisjsewell. Looks good. Just two very minor stylistic changes to be consistent with the rest.

**Comment by chrisjsewell** [comment]
cheers, ready for approval 👍

**Review by yakutovicha — APPROVED** [review]
Approved, please merge once tests are passed.

**Comment by chrisjsewell** [comment]
oops, forgot to find/replace `verdi export` and `verdi import` in the docs

**Pull request merged**
