### PR TITLE
🔀 MERGE: v1.6.4 release

### PR DESCRIPTION
**Pull request by chrisjsewell**
hotfix for psycopg2 v2.9 issue

### CODE REVIEW

**Review by sphuber — APPROVED** [review]
Thanks @chrisjsewell

**Comment by chrisjsewell** [comment]
@sphuber what happens with the support branch, in relation to master/develop branches, i.e. the key commits are obviously already cherry-picked from develop, but what about 1517534?

**Comment by sphuber** [comment]
So far only the CHANGELOG update commits have been important to keep from support releases. Since they are far and between I just added those changes manually in the next release from the main line. For now I think that is simple and good enough I would say.

**Comment by chrisjsewell** [comment]
Yeh fair, just making sure I wasn't missing a trick 👍

**Pull request merged**
