### PR TITLE
CI: Bump reentry to v1.3.2

### LINKED ISSUE #4723: Remove deprecated import from 'collections' instead of 'collections.abc' module
I found at least two more issues with py 3.9 compatibility.

First, I created this: DropD/reentry#57 that needs to be fixed first.

Second: I have (from `pip freeze`): `SQLAlchemy-Utils==0.34.2` that matches our requirements in the setup.json (`sqlalchemy-utils~=0.34.2`). 
However, with this requirement I get:
```
tests/transports/test_all_plugins.py::TestBasicFunctionality::test_is_open
  /Users/pizzi/.virtualenvs/aiida-dev/lib/python3.8/site-packages/sqlalchemy_utils/observer.py:176: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import defaultdict, Iterable, namedtuple
```
I think this has been fixed in [this PR of them](https://github.com/kvesteri/sqlalchemy-utils/pull/397) and, looking [at the corresponding commit](https://github.com/kvesteri/sqlalchemy-utils/commit/45f4e4a3d83f7e45cdf449c7c2c4bfab659d47a7), this should have been released from 0.35.0 (see list of tags in the blue bar at the top of the page from GitHub). So we should update the dependency?

Probably this second issues is not caught in new venvs since the most recent version is installed, but I had an older venv.
[EDIT]: I tested and indeed 0.35.0 does not raise that warning anymore. However, I don't know if the version has been pinned to < 0.35 on purpose or not.

@csadorf I'm reopening this issue, but of course feel free to open another one instead moving my comments there.

_Originally posted by @giovannipizzi in https://github.com/aiidateam/aiida-core/issues/4302#issuecomment-775020859_

### PR DESCRIPTION
**Pull request by csadorf**
Closes #4723

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
Hey @csadorf , couple of questions:

(1) Why is this draft?

(2) Do you know/understand why the rmq test failed on push?? It did succeed on PR, so I'm guessing it might be ok to ignore the failed one?

**Comment by csadorf** [comment]
> Hey @csadorf , couple of questions:
> 
> (1) Why is this draft?

I was going to mark it as ready once the tests pass. This is currently affected by #4731 .

> (2) Do you know/understand why the rmq test failed on push?? It did succeed on PR, so I'm guessing it might be ok to ignore the failed one?

No idea.

**Review by ltalirz — APPROVED** [review]
thanks.

not sure whether the order of the packages is supposed to be alphabetical (see py3.9) but that doesn't matter

**Comment by csadorf** [comment]
> thanks.
> 
> not sure whether the order of the packages is supposed to be alphabetical (see py3.9) but that doesn't matter

They are in the order as `pip freeze` produces it: https://github.com/aiidateam/aiida-core/blob/e794287218a5d3b85a85ba36eed6d6928a849a26/.github/workflows/test-install.yml#L202

**Pull request merged**
