### PR TITLE
✨ NEW: `structure.data.import` plugin entrypoint

### PR DESCRIPTION
**Pull request by dev-zero**
The use case is that I would like to add an option to import structures from a CP2K input file.
While this could be done in an `aiida-cp2k` cli or an extension of `verdi data`, it would make more sense to add it directly here.
On the other hand it might not be a good idea to open up too many entry points since we would have to maintain those.

### CODE REVIEW

**Review by ltalirz — APPROVED** [review]
thanks @dev-zero - I see no issue with this and would support it (this would anyhow move outside aiida-core together with the materials-science specific classes, if that ever happens).

Could you please bring the PR up to date?

@chrisjsewell any comments?

**Comment by dev-zero** [comment]
@ltalirz thanks a lot for the positive feedback, rebased as requested

**Review by ltalirz — APPROVED** [review]
@chrisjsewell I approve this but I'd like one more pair of eyes on this.
Feel free to merge if you agree

**Review by chrisjsewell — CHANGES_REQUESTED** [review]
Looks good cheers, but you add a small bit of documentation of the feature here thanks: https://github.com/aiidateam/aiida-core/blob/develop/docs/source/topics/plugins.rst#aiidacmdline

**Comment by dev-zero** [comment]
> Looks good cheers, but could you add a small bit of documentation of the feature around here thanks: https://github.com/aiidateam/aiida-core/blob/develop/docs/source/topics/plugins.rst#aiidacmdline

Done. Based on the already existing one with a spec, example and example usage.

**Review by ltalirz — APPROVED** [review]
thanks @dev-zero !

**Comment by ltalirz** [comment]
@chrisjsewell can you approve & merge?

**Review by chrisjsewell — APPROVED** [review]
cheers!

**Pull request merged**
