### PR TITLE
Docs: Fix typo's in "Internal Architecture - Repositories" section

### LINKED ISSUE #4036: Docs: Internals: Data storage (File repository)

### PR DESCRIPTION
**Pull request by mbercx**
Fixes #4036

Here we fix some typos in the "Internal Architecture - Repositories"
section, as well as restructure the page so the current repository design is
presented first. The original design is still explained at the end of the section 
since it can offer some insight into the motivation behind the current design.

### CODE REVIEW

**Review by ramirezfranciscof — DISMISSED** [review]
Keen eyes ;)

**Comment by sphuber** [comment]
Can we use this PR to also potentially change the reordering of the sections? At least I remember now that during the reviewing of the original new repo PR @giovannipizzi suggested that we change the sections and don't start with the historical perspective, but instead just explain how the current repo system works. Then after that we can give the insight in the legacy design. I'd be ok with this if others think this is also better. Would be good to include those changes in this PR then and revise the entire section since it hasn't really been reviewed yet.

**Comment by giovannipizzi** [comment]
Indeed - now moving forward to the next release, it's better to start with the "current status", and then only at the end (if/when appropriate) give a historical perspective, maybe even linked in a different page if not crucial to be read by new users. I let you decide if you can do it directly in this PR (if you can't, please open an issue so we don't forget, but great if you can)

**Comment by sphuber** [comment]
> if not crucial to be read by new users.

Note that this is the "Internal Architecture" which is not intended for new users, but developers and maybe interested advanced users.

**Comment by sphuber** [comment]
If we fix the ordering in this one, we could even close #4036 with this PR which would be good

**Comment by sphuber** [comment]
Thanks a lot @mbercx . This is looking good to me. If you fix the warning in the docs build:
```
/home/circleci/project/docs/source/internals/repository.rst:94: WARNING: undefined label: internal-architecture:repository:design:requirements (if the link has no caption the label must precede a section header)
```
then we can merge this.

Sorry for slipping you the additional work during this PR ;)

**Comment by mbercx** [comment]
> Thanks a lot @mbercx . This is looking good to me. If you fix the warning in the docs build:
> 
> ```
> /home/circleci/project/docs/source/internals/repository.rst:94: WARNING: undefined label: internal-architecture:repository:design:requirements (if the link has no caption the label must precede a section header)
> ```
I know, I saw it. 🙃 Couldn't build the docs on my macBook because I just upgraded to Big Sur and apparently I had to update Xcode, which takes a gazillion years. 🙄  Now building on my work station to make sure I don't have any more warnings.

> Sorry for slipping you the additional work during this PR ;)

Haha, no worries, I'm used to your tricks. 😏

**Review by sphuber — APPROVED** [review]
Appreciate the accepted scope creep :+1:

**Pull request merged**
