### PR TITLE
remove leftover use of Computer.name

### PR DESCRIPTION
**Pull request by ltalirz**
Remove leftover use of deprecated Computer.name attribute in `verdi
computer list`.

```
23:40 $ verdi computer list
Info: List of configured computers
Info: Use 'verdi computer show COMPUTERNAME' to display more detailed information
/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/computers.py:738: AiidaDeprecationWarning: this property is deprecated, use the `label` property instead
  warnings.warn('this property is deprecated, use the `label` property instead', AiidaDeprecationWarning)  # pylint: disable=no-member
```

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@ltalirz was there a specific reason for now requiring click 7.1?

**Comment by ltalirz** [comment]
> @ltalirz was there a specific reason for now requiring click 7.1?

Yes - I had click 7.0 locally and it resulted in different whitespace in the verdi autodocs.
Feel free to check whether you get the same

**Comment by ltalirz** [comment]
I can create a separate PR for this if desired

**Comment by chrisjsewell** [comment]
> Yes - I had click 7.0 locally and it resulted in different whitespace in the verdi autodocs.
Feel free to check whether you get the same

Ah yes I do indeed 👍 

> I can create a separate PR for this if desired

I will leave that up to you, I think just make sure to note this in the commit message

**Review by chrisjsewell — APPROVED** [review]

**Comment by ltalirz** [comment]
pinging @csadorf for info (bumping click dependency version here; no further action needed)

**Pull request merged**
