### PR TITLE
Added `compress` option to `verdi storage maintain`

### PR DESCRIPTION
**Pull request by zhubonan**
Enable compression by default for `verdi storage maintain`.
At moment the storage backend (disk-objectstore) has compression configured, but not used by default during the maintainance operation. 

This is because `pack_all_loose` defaults to not compress the data. This PR addes the option to compress the data when doing `verdi storage maintain`, and makes compressing the data the default. 

Since at the moment `disk-objectstore` cannot retrospectively compress the data (e.g. with `repack`), once they make the way to the pack files. Calling `pack_all_loose(compress=True)` is the only way to have the data compressed.

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
Hey @zhubonan , thanks for the contribution! I can take a better look at the code later, but I think that we need to discuss one general aspect before that.

The interface of `verdi storage maintain` has to remain backend agnostic. Although the concept of compressing could be considered to be general to any storage solution (since it is a "property" of the data content itself), I'm thinking the implementation detail of this having to be clarified during the packing procedure is not. For example, if another backend allowed a per-object specification of compression that was handled at the time of storing the object, and would not be changeable during maintenance.

I also have some reservations about having this be the default, but I guess there is no point in discussing such details until we figure out the general issue. I do believe this would be a very interesting feature to enable, I'm just not sure that adding a direct and general option to `verdi storage maintain` is the best option.

Let me know what you think; in the meantime I'm also pinging @sphuber and @giovannipizzi for feedback and ideas.

**Comment by ramirezfranciscof** [comment]
Idea: for the `disk-objectstore` perhaps it would be better to have an option in that storage backend section of the config that is called `compress_when_packing`, and check that value inside of the `DiskObjectStoreRepositoryBackend.maintain` method.

**Comment by zhubonan** [comment]
I see. For backend not supporting compression can they just ignore the supplied option? I don't have any strong opinion on what the default should be, just that I think this functionality should be exposed to the user. 

Since each backend would can handle things differently, rather than having a agnostic interface, may be the cmd line should be defined by each backend themselves (like verdi computer configure)?

**Comment by sphuber** [comment]
> Since each backend would can handle things differently, rather than having a agnostic interface, may be the cmd line should be defined by each backend themselves (like verdi computer configure)?

I added some functionality last week to make this common pattern more easy to use. It is a command group subclass that automatically loads its subcommands based on registered entry points in some category, as for `verdi computer configure` does for the various transports. This time it is used for `verdi code create`. It is not a perfect solution though. Currently the entry point has to be a subcommand for it to work. You cannot have a single command, and have that have dynamic parameters based on the value of one of its arguments. Maybe that could be done, but then basic things like `command --help` wouldn't be able to show the correct help strings. Anyway, something to think about and see if it could be of use here indeed.

**Comment by giovannipizzi** [comment]
Thanks,
- I also think that having some variant per backend is useful/needed, as there will always be backend-specific actions one might want to do
- I'm not sure that compressing by default is a good idea. Maybe better to implement the possibility to repack changing the compression type directly in the object store is better? This might fit well with the work that @zhubonan is doing on the "sealing" of packs as ZIP

**Comment by giovannipizzi** [comment]
one thing we can do, however, is to have a `verdi config` option per profile, where the user can set if they want to compress when packing, and keep it off by default for now - what do you think?

**Comment by chrisjsewell** [comment]
> I'm not sure that compressing by default is a good idea.

Why @giovannipizzi? I think most people will just never use it if it's not on by default, and then you lose its benefits

**Comment by zhubonan** [comment]
Perhaps I should keep uncompressed the default, while still making the option avalaible? 
With the new "searling" function one can compress packed objects that are not already compressed. 

> I'm not sure that compressing by default is a good idea. Maybe better to implement the possibility to repack changing the compression type directly in the object store is better?

I agree, these options should be made avalaible.

**Comment by sphuber** [comment]
What is the situation with this PR?

> Maybe better to implement the possibility to repack changing the compression type directly in the object store is better?

Has this been implemented in the `disk-objectstore`? Can we for now simply add to the documentation how users can maintain the repo of a `psql_dos` backend directly, using the CLI of the `disk-objectstore`?

I think the main objections currently are:

* For now, the `verdi storage maintain` interface is backend-agnostic and it should stay that way until we have a proper system where subcommands are automatically generated for each storage plugin (as with `verdi code create` for example).
* @giovannipizzi and @ramirezfranciscof seemed to have reservations regarding compressing by default. Could you provide details why?

Can we come to an agreement as how to proceed here?

**Comment by zhubonan** [comment]
> Has this been implemented in the disk-objectstore? 

No, I don't think so. I think for now, it is important for `verdi storage maintain` to provide the functionality for allowing compressed packing capability in `disk-objectstore`. For some code, namely VASP, storing text output files in compressed form can lead to 5X-10X spacing saving. To do this, I have been using `disk-objectstore`'s own CLI to perform the maintenance tasks. There is this PR which somewhat allows the compression to be turned on when one "archives" a pack. 
Unfortunately, with the current implementation, if user performs the operation visa `verdi storage maintain`, the **_data will never have the chance to be compressed_**. So I think we should have this PR merged soon if possible.

How about making not compressing by default, and if a `compress` flag is passed, request for compression if the backend supports it? 

Turning on compression by default may have some negative effects as: 1. packing will take longer. 2. Some data analysis requires reading file from the end, this is not implemented in disk-objectstore yet. There is a PR for it though: https://github.com/aiidateam/disk-objectstore/pull/140. 3. Some data types, for examples binary wavefunction files, do not benefit much from compression.

**Comment by sphuber** [comment]
Thanks @zhubonan . Ok, I would be willing to accept these changes with the default being `False`. We should probably just add a note to the docs where we talk about `verdi storage maintain` and explain that the `--compress` flag exists and whether users should use it. We can reuse the 3 potential downsides you mentioned in your previous comment. I just would like to have a final confirmation from @giovannipizzi that he is ok, but he doesn't read github notifications, so I will quickly email him.

**Comment by giovannipizzi** [comment]
Hi, sorry for my delay.
I'm OK with default=False. However, in the future an backend could have more options (e.g. I see the possibility of compressing only files for which the benefit is > a given threshold).

We can either say that we keep --compress only, and the backend will decide what it means, or we convert to --compress=STRING, where the default is "false", and is always supported, "true" also exists, and other options might exist, backend-specific? In the AiiDA CLI we just say that true and false are accepted but anything else is also accepted, and the backend implementation has to validate this.

But maybe this second option is not relevant, one can have a default when True is specified, and go via the cmdline of the backend for more complex options?

**Comment by sphuber** [comment]
I wouldn't go too far down this rabbit hole of potential future requirements. In any case it isn't fully dynamic based on the relevant storage, so I would just do the simple thing and _if_ we ever come to a real backend-independent interface, we can simply deprecate this option. That won't be such a big deal. I think it is unlikely this need would even come up any time soon.

**Comment by chrisjsewell** [comment]
Seems pragmatic to me 👍

**Review by sphuber — APPROVED** [review]
Ok, given that there is no objection in principle to allowing users to compress their pack files should they choose to, I think we can merge this PR. The only objection is that we are adding a backend specific option that might not be supported by all storage backends. However, currently there are few alternative backends that are in use that would require maintenance so a fully dynamic CLI is not really required yet. Should that be needed in the future, we can simply deprecate the `--compress` option if needed, which would not be a huge deal.

Thanks @zhubonan for the PR :+1:

**Pull request merged**
