### PR TITLE
switch to sphinx-book-theme

### PR DESCRIPTION
**Pull request by ltalirz**
fixes https://github.com/aiidateam/aiida-core/issues/4441

### CODE REVIEW

**Comment by ltalirz** [comment]
Besides the logo size that will need to be adjusted, I have to say that I find the default font choices of the pydata-sphinx-theme a bit nicer

Old
image

New
image

**Comment by chrisjsewell** [comment]
Fine, but I already have a PR doing this

**Comment by ltalirz** [comment]
@chrisjsewell You mean a PR switching the theme of the AiiDA docs?

Could you link to #4441 please; that way I would have noticed it

**Comment by chrisjsewell** [comment]
I was holding it off while I fixed some things: https://github.com/executablebooks/sphinx-book-theme/issues/459

**Comment by ltalirz** [comment]
Also, is there a built-in way to display a twitter handle?

**Comment by ltalirz** [comment]
Really like the [announcement banner support](https://sphinx-book-theme.readthedocs.io/en/latest/customize/announcements.html); I think this will come in very handy

**Comment by chrisjsewell** [comment]
> You mean a PR switching the theme of the AiiDA docs?

No, I have a personal branch doing this and a number of other things, like moving from sphinx-panels to sphinx-design, but had opened the PR yet while improve some things on my end

**Comment by chrisjsewell** [comment]
There's lots of work going on in this space, with sphinx-book-theme and others (https://github.com/python/docs-community/issues/1) so I was wary to push forward a change right now

**Comment by ltalirz** [comment]
Ok, then I'll point that out in the issue and leave this change to you

**Pull request closed without merging**
