### PR TITLE
Pin ase dependency to <3.20 for Python 3.5.

### PR DESCRIPTION
**Pull request by csadorf**
Resolves issue #4295.

I recommend to create a hotfix release for this.

### CODE REVIEW

**Comment by csadorf** [comment]
@ltalirz The branch is purposely out-of-date with `develop` in case we want to create a hot-fix release for this. If not, feel free to just update the branch.

**Comment by csadorf** [comment]
> thanks @csadorf !
> 
> would you be able to go forward with the hotfix release?

Yes.

**Comment by ltalirz** [comment]
After discussion with @csadorf , we'll wait a bit to see whether the guys at ASE manage to fix the issue on the ASE side https://gitlab.com/ase/ase/-/issues/718

(after all python 3.5 is pretty close to EOL anyways...)

**Comment by greschd** [comment]
@ltalirz this should now be fixed from the side of ASE - I think we can test that and then close the PR & issue.

**Comment by csadorf** [comment]
The issue is resolved by the recent ase patch releases: https://github.com/aiidateam/aiida-core/actions/runs/204921217

**Pull request closed without merging**
