### PR TITLE
Bump docker stack python version to 3.10.13

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by sphuber** [comment]
Is this ready for review? If we are updating, is there a reason not to take 3.11 ? Even 3.12 would be possible, but maybe that is a bit _too_ recent and we might be safer with 3.11 still

**Comment by unkcpz** [comment]
> If we are updating, is there a reason not to take 3.11 ?

I test with the `3.11` locally, but it require also update the PostgreSQL from 15->16. Do we have guidance on how to update PostgreSQL version?

**Comment by sphuber** [comment]
> > If we are updating, is there a reason not to take 3.11 ?
> 
> I test with the `3.11` locally, but it require also update the PostgreSQL from 15->16. Do we have guidance on how to update PostgreSQL version?

Huh? 🤔 where the heck does that requirement come from? Postgres doesn't use Python does it? I am running Python 3.11 with Postgresql 12 without any issues

**Comment by unkcpz** [comment]
I did a close look, it is not from PostgreSQL but the conda forge it relies on. The PostgreSQL is installed with conda and there is a very weird dependency of `openssl` that is `openssl >=3.2.0,<3.2.0a0` from `libqp`.

```
 > [aiida-core-with-services 2/8] RUN mamba install --yes      --channel conda-forge      postgresql=15 &&      mamba clean --all -f -y &&      fix-permissions "/opt/conda" &&      fix-permissions "/home/aiida":                                                                       
14.29 warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE                                                                                                                                                                                                        
14.29 warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE                                                                                                                                                                                                        
14.31                                                                                                                                                                                                                                                                                     
14.31 Looking for: ['postgresql=15']                                                                                                                                                                                                                                                      
14.31 
14.31 
14.31 Pinned packages:
14.31   - python 3.11.*
14.31   - python 3.11.7
14.31 
14.31 
14.31 Could not solve for environment specs
14.31 The following packages are incompatible
14.31 ├─ postgresql 15**  is installable with the potential options
14.31 │  ├─ postgresql [15.0|15.1] would require
14.31 │  │  └─ libpq [15.0 hd77ab85_1|15.1 h2baec63_2|15.1 h2baec63_3|15.1 hd77ab85_0|15.1 hf695f80_1], which requires
14.31 │  │     └─ openssl >=1.1.1s,<1.1.2a , which can be installed;
14.31 │  ├─ postgresql [15.0|15.1] would require
14.31 │  │  └─ libpq [15.0 he2d8382_1|15.1 h67c24c5_1|15.1 hb675445_2|15.1 hb675445_3|15.1 he2d8382_0], which requires
14.31 │  │     └─ openssl >=3.0.7,<3.2.0a0 , which can be installed;
14.31 │  ├─ postgresql 15.2 would require
14.31 │  │  └─ libpq 15.2 hb675445_0, which requires
14.31 │  │     └─ openssl >=3.0.8,<3.2.0a0 , which can be installed;
14.31 │  ├─ postgresql 15.3 would require
14.31 │  │  └─ libpq [15.3 hbcd7760_0|15.3 hbcd7760_1], which requires
14.31 │  │     └─ openssl >=3.1.0,<3.2.0a0 , which can be installed;
14.31 │  ├─ postgresql 15.3 would require
14.31 │  │  └─ libpq 15.3 hfc447b1_2, which requires
14.31 │  │     └─ openssl >=3.1.1,<3.2.0a0 , which can be installed;
14.31 │  ├─ postgresql 15.4 would require
14.31 │  │  └─ libpq 15.4 hfc447b1_0, which requires
14.31 │  │     └─ openssl >=3.1.2,<3.2.0a0 , which can be installed;
14.31 │  ├─ postgresql 15.4 would require
14.31 │  │  └─ libpq [15.4 hfc447b1_1|15.4 hfc447b1_2], which requires
14.31 │  │     └─ openssl >=3.1.3,<3.2.0a0 , which can be installed;
14.31 │  └─ postgresql 15.4 would require
14.31 │     └─ libpq [15.4 hdb747bd_4|15.4 hfc447b1_3], which requires
14.31 │        └─ openssl >=3.2.0,<3.2.0a0 , which does not exist (perhaps a missing channel);
14.31 └─ python is installable with the potential options
14.31    ├─ python 3.11.7 would require
14.31    │  └─ openssl >=3.2.0,<4.0a0 , which conflicts with any installable versions previously reported;
14.31    ├─ python [1.0.1|1.2|...|3.9.9], which can be installed;
14.31    └─ python 3.12.0rc3 would require
14.31       └─ _python_rc, which does not exist (perhaps a missing channel).
------
Dockerfile:15
--------------------
  14 |     
  15 | >>> RUN mamba install --yes \
  16 | >>>      --channel conda-forge \
  17 | >>>      postgresql=${PGSQL_VERSION} && \
  18 | >>>      mamba clean --all -f -y && \
  19 | >>>      fix-permissions "${CONDA_DIR}" && \
  20 | >>>      fix-permissions "/home/${SYSTEM_USER}"
  21 |     
--------------------
```

If we want to continue without bump PostgreSQL for the docker stack, we need ask them to continue work on https://github.com/conda-forge/postgresql-feedstock/issues/190 and make the change.

**Comment by sphuber** [comment]
> If we want to continue without bump PostgreSQL for the docker stack, we need ask them to continue work on [conda-forge/postgresql-feedstock#190](https://github.com/conda-forge/postgresql-feedstock/issues/190) and make the change.

Honestly, I don't care enough about that to pursue that. I just asked out of curiosity 😄 if you are happy with Python 3.10 then I'll happily merge this

**Comment by unkcpz** [comment]
I think 3.10 will live long enough until it bothers me with the PostgreSQL version problem. I am always happy. :smile:

**Review by sphuber — APPROVED** [review]
Thanks @unkcpz

**Pull request merged**
