### PR TITLE
Improve error message when an error occurs while building the spec in the sphinx extension.

### LINKED ISSUE #3604: sphinx suppresses build errors on RTD
When building documentation of AiiDA plugins on readthedocs.org, there is no AiiDA database, so - obviously - sphinx running on RTD cannot process code that forces it to instantiate ORM objects.

When you put a `orm.Int(1)` somewhere on the module level, you'll get an error message from sphinx [1] - we should perhaps work on making it more useful, but at least you have some indication on what & where the problem is.

However, when you put a `orm.Int(1)` as the default value of an input/output port in a workflow spec (see e.g. [here](https://github.com/yakutovicha/aiida-raspa/blob/develop/aiida_raspa/workchains/aiida_base_restart.py#L95-L98)), and then use the AiiDA sphinx extension to document it, the html output of the extension will lack certain content but no error or warning will be shown in the sphinx output (see https://github.com/lsmo-epfl/aiida-lsmo/issues/18).

This makes both the detection and the debugging of such issues really difficult, even more so as one workchain may be exposing inputs/outputs of other workchains from other packages.

There are two directions along which we could make progress here:
 1. We need to find a way to display helpful error messages for this
 2. When the `IN_RT_DOC_MODE` value is `True`, we could consider attempting a "graceful" failure of all database operations, so that even when you have `orm.Int(1)` on the module level, perhaps a warning would be printed but the documentation would still build.

I think 1. definitely seems like a good idea.
2. has the potential of saving plugin developers with "slightly dirty" plugins from having to rewrite everything just in order to have their docs on RTD, but one would need to see whether/how such a "hook" could work.

Mentioning @sphuber @giovannipizzi @greschd for info

[1] The exception raised by sphinx
```
WARNING: autodoc: failed to import module 'workchains.aiida_base_restart' from module 'aiida_raspa'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "aiida" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-raspa/aiida_raspa/workchains/__init__.py", line 11, in <module>
    from .base import RaspaBaseWorkChain
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-raspa/aiida_raspa/workchains/base.py", line 9, in <module>
    from aiida_raspa.workchains.aiida_base_restart import BaseRestartWorkChain
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida-raspa/aiida_raspa/workchains/aiida_base_restart.py", line 14, in <module>
    orm.Bool(False)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/data/base.py", line 46, in __init__
    super(BaseType, self).__init__(**kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/node.py", line 119, in __init__
    user = user.backend_entity if user else User.objects(backend).get_default()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/users.py", line 69, in get_default
    self._default_user = self.get(email=email)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/entities.py", line 136, in get
    return res.one()[0]
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2085, in one
    res = self.all()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2160, in all
    return list(self.iterall(batch_size=batch_size))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2117, in iterall
    for item in self._impl.iterall(query, batch_size, self._attrkeys_as_in_sql_result):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/implementation/django/querybuilder.py", line 442, in iterall
    with transaction.atomic():
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/transaction.py", line 158, in __enter__
    if not connection.get_autocommit():
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 385, in get_autocommit
    self.ensure_connection()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "aiida" does not exist

```

### PR DESCRIPTION
**Pull request by greschd**
Fixes #3604. 

In its initial setup phase, sphinx swallows _all_ errors. When an exception occurs within the ``define`` method, this can lead to an incomplete spec being present. Because the spec is only built once, it will not trigger an exception within the AiiDA sphinx extension.

By deleting the ``_spec`` attribute in the sphinx extension, we force the spec to be re-built, meaning that such errors will now be raised.

Also adds a test for this behavior, with a workchain that raises a ``ValueError`` in ``define``, and checking that this error is printed when building the documentation.

Also mentioning @ltalirz - since we developed this fix together someone else should probably review this.

### CODE REVIEW

**Comment by ltalirz** [comment]
So, when I build the documentation of `aiida-raspa` (which only involves workchains from within the plugin), I now get an exception when I make an error:
```
$ make html 
...
reading sources... [100%] workflows
Exception occurred:
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "aiida" does not exist
The full traceback has been saved in /var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/sphinx-err-18ighg1g.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
This is an improvement, although it does not really give the user any hints on where to look. 

Can we somehow do better than this?

This gets particularly important when you're building the documentation of plugins that reuse workchains from other plugins, in which case the search space for the source of the issue can be pretty large

**Comment by ltalirz** [comment]
Here is the full traceback
```
# Sphinx version: 2.2.1
# Python version: 3.6.9 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   reading sources... [ 50%] apidoc/aiida_lsmo.workchains
#   
#   reading sources... [ 62%] get_started
#   
#   reading sources... [ 75%] index
#   
#   reading sources... [ 87%] technicalities
#   
#   reading sources... [100%] workflows
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.1) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.2.1) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (2.2.1) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (2.2.1) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinxcontrib.contentui (unknown version) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/contentui.py
#   sphinxcontrib.details.directive (0.1.0) from /Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinxcontrib/details/directive/__init__.py
#   aiida.sphinxext (1.0.1) from /Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/sphinxext/__init__.py
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/plumpy/processes.py", line 180, in spec
    return cls.__getattribute__(cls, '_spec')
AttributeError: 'ProcessStateMachineMeta' object has no attribute '_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "aiida" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/io.py", line 114, in read
    self.parse()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 3007, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2099, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/sphinx/domains/__init__.py", line 265, in run
    return super().run()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/sphinxext/process.py", line 57, in run
    self.initialize()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/sphinxext/process.py", line 83, in initialize
    self.process_spec = self.process.spec()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/plumpy/processes.py", line 184, in spec
    cls.define(cls._spec)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/aiida_lsmo/workchains/isotherm_calc_pe.py", line 97, in define
    default=Dict(dict=ISOTHERM_PARAMETERS_DEFAULT),
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/data/dict.py", line 35, in __init__
    super().__init__(**kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/node.py", line 113, in __init__
    user = user.backend_entity if user else User.objects(backend).get_default()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/users.py", line 66, in get_default
    self._default_user = self.get(email=email)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/entities.py", line 133, in get
    return res.one()[0]
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2080, in one
    res = self.all()
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2155, in all
    return list(self.iterall(batch_size=batch_size))
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/querybuilder.py", line 2112, in iterall
    for item in self._impl.iterall(query, batch_size, self._attrkeys_as_in_sql_result):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/implementation/django/querybuilder.py", line 438, in iterall
    with transaction.atomic():
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/transaction.py", line 175, in __enter__
    if not connection.get_autocommit():
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/base/base.py", line 379, in get_autocommit
    self.ensure_connection()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida-lsmo-rtd/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  role "aiida" does not exist
```

**Comment by ltalirz** [comment]
Unfortunately, it turns out this solution doesn't work for WorkChains that expose inputs of other WorkChains (=specs), since we aren't invalidating those...

**Comment by greschd** [comment]
**Update**: This is now fixed "properly" with https://github.com/aiidateam/plumpy/pull/136, but we retain the test here, and added a nicer error message.

For the test to pass, we first need to update plumpy and change the corresponding requirement.

**Comment by greschd** [comment]
Fixed ``plumpy`` is now released, making this ready for review.

**Comment by ltalirz** [comment]
@sphuber Do you still want to give a look?

**Comment by sphuber** [comment]
Thanks a lot guys

**Pull request merged**
