### PR TITLE
CI: move Jenkins workflow to nightly GHA workflow

### LINKED ISSUE #5276: Move the Jenkins CI to a GitHub Action nightly build
The only tests that are run on Jenkins that are not already in the GHA CI workflow, should be the polish workflows. We can simply migrate these to a nightly build (since they can be costly and should not be run on every commit) which will allow us to decommission the Jenkins machine which requires a lot of maintenance.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5276 

Up till now, we have been running a Jenkins server to run certain tests.
The idea was to use this server to run more heavy integration tests that
would clog the CI pipeline, which was running on Travis at the time.

The only test that was added and has been running since are the Reverse
Polish Notation (RPN) workchains. These have uncovered a bug or two, but
it has been rare and the burden of maintaining the Jenkins server is not
neglible. In addition, since then we have moved from Travis to GitHub
Actions as the CI platform, and throughput has not been a problem there.

Therefore, we move the RPN tests to a GHA workflow that runs nightly.
This allows us to decommission the custom Jenkins server while
maintaining the additional coverage that the tests provide, without
overloading the CI by not having them run on every commit.

### CODE REVIEW

**Comment by sphuber** [comment]
@chrisjsewell I have left the `.molecule` directory even though it is not used anymore in the CI. I would have removed it, but I think you might be using it locally to run tests? If that is not the case, should we maybe get rid of it?

Then, as discussed before, I have implemented this as a separate workflow that runs nightly. The idea was because the operation was too expensive to run on every commit. But actually it doesn't take that long at all. Question is thus if it still makes sense to keep it separate or whether we integrate it in the existing tests?

**Comment by giovannipizzi** [comment]
Indeed, I think it's better to run as standard tests since they are fast.
Regarding `.molecule` I let @chrisjsewell comment, I'm not sure how these are currently used

**Comment by sphuber** [comment]
The tests seem to take on the order of 2 minutes: https://github.com/sphuber/aiida-core/runs/4534676923?check_suite_focus=true
Have to say that it isn't the worst, but still significant on the typical 14 minutes that the tests take now. I have added a commit to include them with the main tests to see how this is affected. Should be a simple addition of 2 minutes, but just to be sure.

**Comment by giovannipizzi** [comment]
Mmm - I had understood that they actually were faster... Now tests are a indeed slower.
What do you prefer to do? Merge, or revert your last change?

**Comment by sphuber** [comment]
The last run of the RPN takes a minute, i.e., about half the time. If we remove that one, we still run 4 workchains and we are just adding 1 minute. Might be a compromise?

**Comment by sphuber** [comment]
@chrisjsewell thoughts? Is another minute added to the ci-code workflow acceptable? Or do we just accept another workflow that we schedule as nightly build?

**Comment by chrisjsewell** [comment]
> @chrisjsewell thoughts? Is another minute added to the ci-code workflow acceptable? Or do we just accept another workflow that we schedule as nightly build?

Ughh, I guess another minute is not the end of the world.

One thing I'd note, is that we also have the `tests/benchmark/` tests, which are only run on pushes to `develop` (in `.github/workflows/benchmark.yml`, and the results uploaded to https://aiidateam.github.io/aiida-core/dev/bench/ubuntu-18.04/django/ / https://aiidateam.github.io/aiida-core/dev/bench/ubuntu-18.04/sqlalchemy/
It might be ideal, to role up these tests and the benchmarking into one in some way

**Comment by sphuber** [comment]
> It might be ideal, to role up these tests and the benchmarking into one in some way

I will leave that for a separate PR if you don't mind. This way @giovannipizzi can decommission the Jenkins machine after we merge this.

**Comment by giovannipizzi** [comment]
Thanks! I see that I don't find any reference to Jenkins anymore in the settings, probably you already removed it?

**Comment by sphuber** [comment]
Yes, I already removed the webhook

**Pull request merged**
