### PR TITLE
👌 Make Workchain awaitable methods private

### PR DESCRIPTION
**Pull request by chrisjsewell**
These methods are not inherited,
and so they can be made private,
without the need for decorating.

### CODE REVIEW

**Review by sphuber — APPROVED** [review]
Not sure what you mean with "These methods are not inherited, and so they can be made private", would be good if you can clarify. But changes are ok.

**Comment by chrisjsewell** [comment]
> Not sure what you mean with "These methods are not inherited, and so they can be made private", would be good if you can clarify. But changes are ok.

So e.g. ideally here you would probably also want to change `WorkChain.run` to `WorkChain._run`, but this is not trivial because then you would also need to change `plumpy.Process.run` (where it's inherited from), `aiida.Calcjob.run` (that also inherits it), etc

**Comment by sphuber** [comment]
> So e.g. ideally here you would probably also want to change `WorkChain.run` to `WorkChain._run`, but this is not trivial because then you would also need to change `plumpy.Process.run` (where it's inherited from), `aiida.Calcjob.run` (that also inherits it), etc

Not sure I agree, because `run` is a method that needs to be called from outside the class, so it shouldn't be private. Anyway, I don't think it was a bad thing to protect these methods. Whether they are private or not, a `WorkChain` implementation can override it just as easily. With the explicit protection of the decorator, the user would actually not be able to accidentally make this mistake. But given that the chance of them choosing the name `_insert_awaitable` for their implementation is minimal, I won't stop these changes.

**Comment by chrisjsewell** [comment]
Yeh merge away

**Pull request merged**
