### PR TITLE
CI: move time consuming tests to separate workflow that runs nightly

### PR DESCRIPTION
**Pull request by sphuber**
The test that runs the Reverse Polish Notation (RPN) workchains and the
migrations tests are relatively time consuming and they should not be
affected by most commits. That's why we can afford to have them just run
nightly instead of on every PR.

A `nightly` GHA workflow is added that runs every day at midnight. It
runs a bash script `tests_nightly.sh` that in turns runs the script
`test_polish_workchains.sh` as well as the unit test using `pytest`. The
latter is called with the option `-m 'nightly'` which will select only
tests that are marked as nightly.

All tests under `tests/backends/aiida_sqlalchemy/migrations` are marked
as nightly dynamically through the `pytest_collection_modifyitems`
function in the `tests/backends/aiida_sqlalchemy/migrations/conftest.py`
configuration file.

### CODE REVIEW

**Comment by sphuber** [comment]
> As mentioned, the only issue here is that, this is can going to kill code coverage of unit tests

I don't think this should be a problem though. Sure [the coverage percentage reported by Codecov](https://codecov.io/gh/aiidateam/aiida-core/commit/34c9088cb87d7e436983bf55923063454c9abc8b/graphs) will be a few points lower, but we know that the code is still being covered, just not at every commit. That is the whole point of this change though. We discussed and agreed that the tests were starting to take way too long and it would make sense to split off those tests that don't require being run at every commit. I don't think we should be led in this discussion by the percentage reported by Codecov. That is just an indicator.

> 
> Even if we do add some, I don't think we should mark all migration tests as nightly.
> It should at most be:
>  ...
> i.e. only ones that relate to "legacy" migrations

That is fair enough. But that is essentially the entire directory which I mark now, except for `test_main` and `test_head_vs_orm` in `test_all_schema`. The `test_alembic_cli` as well, but that should really not be part of the `migrations` directory but moved one up.
If you are happy with that compromise, I can add those changes.

**Comment by chrisjsewell** [comment]
>  I don't think we should be led in this discussion by the percentage reported by Codecov.

We are never going to get 100% test coverage with that attitude 😛 

> If you are happy with that compromise, I can add those changes.

Yeh sounds good

**Comment by sphuber** [comment]
> We are never going to get 100% test coverage with that attitude

Just have to wait until we drop the legacy migrations :smile:

**Comment by sphuber** [comment]
> Yeh sounds good

Done!

**Review by chrisjsewell — APPROVED** [review]
Can merge this next cheers 👍

**Pull request merged**
