### PR TITLE
Update Coverage and Travis badges in README - and all relevant instances of `aiida_core` to `aiida-core`

### LINKED ISSUE #3149: Rename repository vs. coverage
Relate to issue #3127.

I think perhaps Coverage has suffered under the repository rename from `aiida_core` to `aiida-core`.
It hasn't seen a build update on develop since #3122 was merged.

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #3149

This was necessary due to the repository name change from `aiida_core`
to `aiida-core`.

'aiidateam/aiida-core' repository was enabled on coverage.io.

### CODE REVIEW

**Comment by sphuber** [comment]
Just to check, since I am not going to check 728 files one-by-one. You simply did a search-and-replace for `aiida_core`? Did you make sure to only match it in a URL, e.g. it is preceded by `aiidateam/`?

**Comment by CasperWA** [comment]
> Just to check, since I am not going to check 728 files one-by-one. You simply did a search-and-replace for `aiida_core`? Did you make sure to only match it in a URL, e.g. it is preceded by `aiidateam/`?

Ah right, I meant to write exactly what I did:

1. Search-and-replace for the whole line of the top comment, i.e.:
  `# The code is hosted on GitHub at https://github.com/aiidateam/aiida_core #` to
  `# The code is hosted on GitHub at https://github.com/aiidateam/aiida-core #`
1. Search-and-replace (when it made sense) for `aiidateam/aiida_core` to `aiidateam/aiida-core`
1. Search-and-replace (when it made sense) for `aiida_core` to `aiida-team`

For the second point, I even found some colons missing in some links for the changelog :) (`https//` to `https://`)

**Comment by CasperWA** [comment]
The only thing that I have changed, but couldn't properly check was the change in the Travis release build job (I checked the links that was changed, which weren't going directly to the repo)

**Comment by CasperWA** [comment]
It should be noted that if I do a search in all files now for `aiida_core` nothing comes up, i.e., "when it made sense" was all instances it seems.

**Pull request merged**
