### PR TITLE
🐛 FIX: Initialising a Node with a User

### PR DESCRIPTION
**Pull request by chrisjsewell**
So it appears that no one has ever tried to specifically set a user for a node (e.g. `Data(user=another_user)`) because, as you see from the diff, it would then try to call `.backend_entity` on the backend entity and fail.
Disappointing that mypy didn't pick this up in the type checking (perhaps there is a stricter setting that I haven't added)

cc @ltalirz as this came up with respect to the REST API (i.e. if we want to create a node for a specific user)

### CODE REVIEW

**Review by sphuber — CHANGES_REQUESTED** [review]
Thanks @chrisjsewell . Straight forward enough, but since this wasn't caught by tests and is so basic, would be good to add a simple test for this.

**Comment by chrisjsewell** [comment]
> but since this wasn't caught by tests and is so basic, would be good to add a simple test for this.

yeh yeh I knew you were going to say this 😛 Just wanted to quickly add the code change via github first, so I didn't forget

**Comment by chrisjsewell** [comment]
@sphuber I converted all of `tests/orm/node/test_node.py` to pytest and added some extra tests

**Review by sphuber — APPROVED** [review]
Thanks @chrisjsewell

**Pull request merged**
