### PR TITLE
Docs: Add redirects from old documenation

### PR DESCRIPTION
**Pull request by chrisjsewell**
This adds redirects from old documentation,
e.g. if you try to open https://aiida.readthedocs.io/projects/aiida-core/en/latest/install/quick_installation.html, it will redirect you to https://aiida.readthedocs.io/projects/aiida-core/en/v1.0.0/intro/get_started.html

### CODE REVIEW

**Comment by ltalirz** [comment]
Will this also redirect links of the form: https://aiida-core.readthedocs.io/en/stable/apidoc/aiida.orm.html ?

**Comment by ramirezfranciscof** [comment]
Also to add to leopold's: does it also rederict link to sections? https://aiida-core.readthedocs.io/en/v1.0.0/apidoc/aiida.orm.html#module-aiida.orm

**Comment by chrisjsewell** [comment]
> Will this also redirect links of the form

I'm not sure what you mean "of the form"? As in with the "stable"

**Comment by chrisjsewell** [comment]
You have to specify every page you wish redirected, then it basically just adds an HTML page like:

docs/build/html/working_with_aiida/index.html
```html
<html>
    <head>
        <noscript>
            <meta http-equiv="refresh" content="0; url=../howto/index.html"/>
        </noscript>
    </head>
    <body>
        <p>You should have been redirected.</p>
        <a href="../howto/index.html">If not, click here to continue.</a>
        <script>
            window.location.href = '../howto/index.html' + (window.location.search || '') + (window.location.hash || '');
        </script>
    </body>
</html>

```

**Comment by ltalirz** [comment]
> I'm not sure what you mean "of the form"? 

The link has the aiida-core prefix, not aiida and then with projects/aiida-core.
In any case, I guess it will work but we will nevertheless need the list of broken links to check that things have been fixed.

**Comment by chrisjsewell** [comment]
it will also "solve" chained redirects, such that you won't be redirected through multiple pages

**Comment by chrisjsewell** [comment]
> The link has the aiida-core prefix, not aiida and then with projects/aiida-core.

Yeh it does not matter about the prefix, since it is still pointed st the same site with the same HTML pages

**Comment by chrisjsewell** [comment]
you can give it a go now at e.g. https://1394-77234579-gh.circle-artifacts.com/0/html/install/prerequisites.html

**Comment by ltalirz** [comment]
Thanks @chrisjsewell , this looks great to me!

Can you take care of searching the items in the list and make sure that the doc links mentioned there are added to the redirects?

After this, I'm happy to review/approve the PR

**Comment by giovannipizzi** [comment]
Thanks! Looks great, lets maybe keep this open and we merge it tomorrow night - anybody who finds more redirects can add them as comments to this PR

**Comment by ltalirz** [comment]
Fyi, the google doc with the list of broken links is here: https://docs.google.com/document/d/1ayC2jO3zPLybE3tbmBsUMl7SqWwUltzerDYn3ym8nG8/edit#

(only accessible from EPFL)

**Comment by ltalirz** [comment]
@chrisjsewell Not sure which links you already covered but the link I mentioned in the issue above remains broken:

https://aiida-core.readthedocs.io/en/stable/apidoc/aiida.orm.html

Also e.g.
https://aiida-core.readthedocs.io/en/stable/import_export/main.html#export-file-format

**Comment by ltalirz** [comment]
Hmm that may not be this PR's fault - there seem to be issues with building the docs https://readthedocs.org/projects/aiida-core/builds/

**Comment by chrisjsewell** [comment]
Yeh I haven't covered any of them yet, since people wanted to use this feature imminently, I was going to add the specific ones from the google docs in a separate PR

**Pull request merged**
