### PR TITLE
pytest: reset test manager after test run

### PR DESCRIPTION
**Pull request by ltalirz**
fixes part of #4722 

Tests written in pytest did not reset the AiiDA manager, resulting in the
global singleton manager instance remaining after the end of the test.

This was already taken care of in the teardown method of the unit test
class AiidaTestCase.

### CODE REVIEW

**Comment by ltalirz** [comment]
@chrisjsewell Do you have an idea why this change breaks the memory leak system tests (first commit)?
It looks like the first test passes, and then since the second test will need to recreate the manager (?) the process ends up staying in memory.

When I uncomment the memory leak system tests, the rest of the test suite runs fine (second commit) although the warnings about the unclosed event loop remain.

**Comment by chrisjsewell** [comment]
> Do you have an idea why this change breaks the memory leak system tests (first commit)?

hmm no idea off-hand, will think about it

**Comment by chrisjsewell** [comment]
Perhaps the asycio loop is closed before all background processes are finished and the process has a chance to "clean up" 🤷

**Comment by ramirezfranciscof** [comment]
I understand this is currently WIP, correct? I'll set it to draft, once it is ready to review (or if I misinterpreted the status) you can set the status back and someone will review it.

**Comment by ltalirz** [comment]
Great, feel free to close if you're sure this is fixed

**Comment by ltalirz** [comment]
https://github.com/aiidateam/aiida-core/pull/5330 has been merged

**Pull request closed without merging**
