### PR TITLE
Fix `aiida.cmdline.utils.decorators.with_dbenv` always loading the db

### LINKED ISSUE #4864: The `aiida.cmdline.utils.decorators.with_dbenv` loads database environment even if it is already loaded
It calls the function `load_backend_if_not_loaded` but the name is a lie as it will always load the backend, regardless of its state.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #4864 

The premise of the method `with_dbenv` is that it will load the profile
and corresponding database environment if not already loaded. However,
due to a bug in `load_backend_if_not_loaded` it was actually *always*
loading the environment for every call, even if the database env was
already loaded, leading to very expensive calls for nothing.

### CODE REVIEW

**Comment by sphuber** [comment]
@ramirezfranciscof also this would be good to quickly merge and release with 1.6.2

**Comment by ramirezfranciscof** [comment]
@sphuber is there a way to add a quick test that uses this method twice and somehow checks that there was a double load? It would be nice to have, but I do recognize that it is not clear to me how it could check for that...

**Comment by sphuber** [comment]
> @sphuber is there a way to add a quick test that uses this method twice and somehow checks that there was not a double load? It would be nice to have, but I do recognize that it is not clear to me how it could check for that...

It could be done: we would have to mock the database loading env by a function that counts the number of times it is called with a global and raises the second time. But I didn't have the time to implement it and don't think it was necessary for this change. Doubt that this will accidentally be reverted at some point.

**Comment by ramirezfranciscof** [comment]
Ok, I'll just open an issue then and we can just merge it as is (maybe if its quick and we don't have other problems I can even take care of it during the coding days after merging the new repository).

**Review by ramirezfranciscof — APPROVED** [review]
Good to go!

**Pull request merged**
