### PR TITLE
add file retrieval lists to job template

### PR DESCRIPTION
**Pull request by ltalirz**
In some scenarios, retrieving files after job completion may need to be handled by pushing them back via the compute job rather than by AiiDA trying to fetch them.

By adding the various retrieval/copy lists to the JobTemplate, this is made possible.

### CODE REVIEW

**Comment by ltalirz** [comment]
@sphuber We needed this information at the scheduler level for an internal plugin. In general, I think this will be necessary for supporting a mode where the compute node is responsible for pushing results back, rather than AiiDA being responsible for pulling results in.

Can you please let me know whether there are any concerns for adding these at the top-level of the job template? If not I can add a test and get this PR ready for review.

**Comment by sphuber** [comment]
> In general, I think this will be necessary for supporting a mode where the compute node is responsible for pushing results back, rather than AiiDA being responsible for pulling results in.

How is this information read by the compute node though? The code of the `Scheduler` plugin and the `JobTemplate` are executed by the machine that AiiDA is running on.

**Comment by sphuber** [comment]
Should this maybe be converted into an issue with a feature request describing the use case?

**Comment by ltalirz** [comment]
> How is this information read by the compute node though? The code of the `Scheduler` plugin and the `JobTemplate` are executed by the machine that AiiDA is running on.

The scheduler plugin uses the information to add corresponding commands to the batch script.

**Comment by ltalirz** [comment]
> Should this maybe be converted into an issue with a feature request describing the use case?

Yes, I'll do that, but it will require a bit of thought. 
This PR is a "quick fix" that enables a specific use case.

**Comment by sphuber** [comment]
> This PR is a "quick fix" that enables a specific use case.

I see that, but what is the idea of the PR? Were you looking to get it merged? I am asking since you opened it as a draft and like you say it might merit some discussion before changing this. If you agree with opening an issue, maybe this can be closed for the time being

**Comment by sphuber** [comment]
I will close this for now as the requested feature can be discussed in #5892

**Pull request closed without merging**
