### PR TITLE
Dependencies: drop support for Python 3.7

### LINKED ISSUE #5306: Drop support for Python 3.7
Following AEP 003 which follows NEP 029, we drop support for Python 3.7 on 26-Dec-2021

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5306 

Following AEP 003, which follows NEP 029, support for Python 3.7 is
dropped as of December 26 2021.

### CODE REVIEW

**Review by csadorf — COMMENTED** [review]
Changes look fine to me however the tests are failing.

**Comment by sphuber** [comment]
It looks like `pytest-asyncio==0.17.0` is now getting installed instead of `pytest-asyncio==0.16.0`, so it seems likely it has to do with this. Will try to pin and see if that fixes it.

**Comment by sphuber** [comment]
`pytest-asyncio` v0.17 was released 3 hours ago ... https://pypi.org/project/pytest-asyncio/

**Comment by csadorf** [comment]
> `pytest-asyncio` v0.17 was released 3 hours ago ... https://pypi.org/project/pytest-asyncio/

[dependecy hell]

**Comment by sphuber** [comment]
@csadorf added temporary fix in #5309 . Opened issue #5310 for a more long term solution as it is not immediately obvious how to solve this for all versions

**Review by csadorf — APPROVED** [review]

**Pull request merged**
