### PR TITLE
CLI: Add the `verdi blitz` command

### PR DESCRIPTION
**Pull request by sphuber**
**Disclaimer**: `verdi blitz` is just a working title for now 😅 fully up for discussion of course

This command will provide a one-stop-shop to create a new profile that
requires no services (no PostgreSQL nor RabbitMQ) and is as much
ready-to-go as is possible.

The profile created uses the `core.sqlite_dos` plugin for the storage
and sets `core.no_comms` as the broker. The profile is automatically set
to be the default and a number of options are configured to sensible
defaults. Finally the localhost is configured as a `Computer`.

This command will make it a lot easier for users to try AiiDA as
services are typically difficult to install and are not really necessary
for a sandbox so potential users can play around to get a sense of how
things work. With this addition, going from scratch to running a calcjob
takes three commands in total:

    pip install aiida-core
    verdi blitz
    verdi devel launch-add

Of course, if a user wants to run other codes, they may have to install
another plugin and install their pre-requisites.

### CODE REVIEW

**Comment by sphuber** [comment]
This builds on top of #6303 . With this changes, the [goals stated in this document](https://hackmd.io/@aiida/rkskVxxia) of running an EOS workchain with `aiida-quantumespresso` can be achieved in the following steps:
```
pip install aiida-quantumespresso
mamba install qe
verdi blitz
verdi code create core.code.installed -n \
        --label pw \
        --default-calc-job-plugin quantumespresso.pw \
        --computer localhost --prepend-text 'eval "$(conda shell.posix hook)"\nconda activate base\nexport OMP_NUM_THREADS=1' \
        --filepath-executable pw.x
verdi run script.py
```

This requires no services, the workchain is run locally so no need to juggle with the `PATH`, and the calculations will still be run in parallel.

**Comment by danielhollas** [comment]
Exciting stuff. It would be awesome if this also allowed easier testing. Maybe creating new lightweight pytest fixtures?

**Comment by GeigerJ2** [comment]
Hi, @sphuber, indeed exciting stuff! It's something @khsrali and I have also been discussing with @giovannipizzi recently (and also @superstar54) today, based on the previous related PRs (#6070 and #6261) and the hackmd document. So I guess this here provides exactly what we were aiming for :rocket:

**Comment by giovannipizzi** [comment]
Thanks, looks great! One question (not immediately obvious to me). Where is the profile stored? Can it be by default a sub folder of the pwd, and have a cmdline option to specify a path?

Also, I'm not sure how to have the cmdline api support it, but it would be good to have a second way to pick the profile, somehow similar to how git does it (look if you have a profile in the pwd), so you can easily switch beteek  profiles? Now the profile name is hardcoded, and I need to delete it from the global config. It would be better to have the option to also have the config.json (or .aiida folder) in the same folder somehow, and have that as the priority option (I think this is not the current default behavior of AIIDA_PATH, but I might be wrong). Of course we need to think if this is backward compatible, but to me it looks that at least for those profiles, it makes everything much more self-contained.

So in essence, the blitz command could actually create a .aiida in the current pwd and use that (so the default profile name is less important - still, if run twice, it should not crash but use a different profile name?)

Anyway, mostly comments to improve usability, the pr itself goes a great way in a great direction!

**Comment by sphuber** [comment]
> Thanks, looks great! One question (not immediately obvious to me). Where is the profile stored? Can it be by default a sub folder of the pwd, and have a cmdline option to specify a path?

In the normal `config.json`. It is a normal profile just like any profile that would be created with `verdi quicksetup/setup`, it just uses the new "no-comms" broker which doesn't require RMQ.

> Also, I'm not sure how to have the cmdline api support it, but it would be good to have a second way to pick the profile, somehow similar to how git does it (look if you have a profile in the pwd), so you can easily switch beteek profiles? Now the profile name is hardcoded, and I need to delete it from the global config. It would be better to have the option to also have the config.json (or .aiida folder) in the same folder somehow, and have that as the priority option (I think this is not the current default behavior of AIIDA_PATH, but I might be wrong). Of course we need to think if this is backward compatible, but to me it looks that at least for those profiles, it makes everything much more self-contained.

Ok, after reading all this, it seems that you are expecting a new feature that the command somehow creates a new AiiDA instance. What is the reason for wanting this? I haven't added it yet, but adding an option to allow the user to specify a profile name other than the default, or simply autogenerating one that doesn't exist yet, should be trivial.

**Comment by GeigerJ2** [comment]
Proposal for the name: How about `verdi allegro`, to stay with the references to Italian opera? :)
And, to me, `verdi setup allegro` or `verdi setup --allegro` would seem more consistent with the current API, rather than adding a new `verdi` command? Also, considering that `verdi quicksetup` already exists, so it might add more confusion as to which one to use otherwise?

**Comment by sphuber** [comment]
> How about `verdi allegro`, to stay with the references to Italian opera? :)

I like that idea a lot! Maybe instead of `allegro` we could also consider `presto` which is an even faster faster rhythm indicator.. Another nicety of this option is that the word is often used in common parlance: "... and _presto_, it was done" to indicate an action that was accomplished quickly and effortlessly.

**Comment by sphuber** [comment]
Closing this because I think the `verdi init` solution of #6315 seems preferred

**Pull request closed without merging**
