### PR TITLE
`ProcessFunction`: Automatically serialize Python base type inputs

### LINKED ISSUE #5686: Add automatic input serialization to `ProcessFunction`s
This will allow users to pass normal Python types to calculation and work functions
```python
@calcfunction
def add(x, y):
    return x + y

add(1, 2)
```

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #5686 

The `to_aiida_type` dispatcher is set as the `serializer` of the input ports of the `ProcessFunction` process class. This process class is generated on the fly for a function decorated by the `calcfunction` and `workfunction` decorators.

Through change, process functions can now be called with Python base types for their arguments, which will be automatically wrapped in the corresponding AiiDA data type.

### CODE REVIEW

**Review by unkcpz — COMMENTED** [review]
@sphuber thanks! Really a quick and clear implementation. I am curious, what if the input argument is a complex datatype, which error it will raise?

**Comment by sphuber** [comment]
> @sphuber thanks! Really a quick and clear implementation. I am curious, what if the input argument is a complex datatype, which error it will raise?

If a type is passed that is not known by `to_aiida_type` nothing is serialized and the value itself is passed. It will then go to the normal type validation on the corresponding port and if the type is incorrect, an error is raised like normal. It would be like passing a `StructureData` to a port that would expect an `Int`.

**Review by unkcpz — DISMISSED** [review]
LGTM!🚀

**Comment by ltalirz** [comment]
This looks very useful to me; it will also make people wonder why they can't do the same with other processes ;-)

One comment: perhaps it makes sense to adapt some existing tests of work/calcfunctions, replacing AiiDA type inputs with python types, just to have an "integration test" as well.

**Comment by ltalirz** [comment]
No further review needed from my side.

**Review by chrisjsewell — APPROVED** [review]
Yep all good cheers

**Comment by sphuber** [comment]
> This looks very useful to me; it will also make people wonder why they can't do the same with other processes ;-)

We could consider to set `to_aiida_type` as the default `serializer` for all newly created `InputPort`s. This would achieve the desired effect. Users will just have to realize that if they replace the serializer, the functionality is lost. But usually that is anyway when you are specifying an input port with a valid type that is not a Python base type, so I doubt this would matter much.

**Pull request merged**
