### PR TITLE
reversing: daemon start and profile setup sections

### PR DESCRIPTION
**Pull request by flavianojs**
Informing the profile setup before starting the daemons because if a person has no AiiDA profile, there will be an error.

### CODE REVIEW

**Review by csadorf — APPROVED** [review]
Thank you! Very much appreciated @flavianojs ! 👍

**Comment by csadorf** [comment]
@flavianojs Can you fix the one issue marked up by the pre-commit check?
https://github.com/aiidateam/aiida-core/pull/4574/checks?check_run_id=1414399826

**Review by csadorf — COMMENTED** [review]
Thx!

**Comment by flavianojs** [comment]
> Thank you! Very much appreciated @flavianojs ! 👍

Not a problem, @csadorf !

**Pull request merged**
