### PR TITLE
Bump ipykernel dependency in test requirements

### LINKED ISSUE #5071: update ipykernel once v6.1 is released
ipykernel 6.0.3 required importlib-metadata<4 for python 3,7, which caused @chrisjsewell to use ipykernel 5 (which does not have this restriction) for python3.7 in the test requirements [1], see https://github.com/aiidateam/aiida-core/pull/5058/files#diff-5096c356dcee4904c32d307b2394b651880eca46af0b1255d3bada8a8cc302fd

My PR to relax this requirement in ipykernel has been merged https://github.com/ipython/ipykernel/pull/738#event-5148667693 and should be released with ipykernel 6.1

@aiidateam/dependency-manager Please update the ipykernel dependency in the python3.7 requirements after ipykernel 6.1 is released 

[1] While this makes the tests pass, not sure whether that solves the problem for users installing aiida under python3.7

### PR DESCRIPTION
**Pull request by ltalirz**
fix #5071

ipykernel 6.0.3 required importlib-metadata<4 for python 3,7, which
caused @chrisjsewell to use ipykernel 5 (which does not have this
restriction) for python3.7 in the test requirements.

In the meanwhile, my PR to relax this requirement in ipykernel has been
merged and ipykernel 6.1 has been released.

### CODE REVIEW

**Comment by ltalirz** [comment]
@chrisjsewell only the performance test seems to be failing

**Comment by chrisjsewell** [comment]
No just fluctuation: they seem to go up to max 4.3

**Comment by chrisjsewell** [comment]
You did ask me to revert the allowed time 😉 I guess #5070 will fix this for good

**Comment by ltalirz** [comment]
Ok, then please approve & merge

**Review by csadorf — APPROVED** [review]

**Pull request merged**
