### PR TITLE
🧪 TESTS: Add pytest `requires_rmq` marker

### PR DESCRIPTION
**Pull request by chrisjsewell**
and also use this for the rabbitmq github workflow

### CODE REVIEW

**Comment by ltalirz** [comment]
pre-commit is failing...

**Comment by chrisjsewell** [comment]
> pre-commit is failing...

hopefully just fixed

**Review by ltalirz — COMMENTED** [review]
thanks @chrisjsewell for the addition - have you checked that when skipping the markers the test suite passes also without rabbitmq being online?

Will approve once/if this check has been done.
Also, please add one sentence in https://github.com/aiidateam/aiida-core/wiki/Writing-tests on how to skip the rabbitmq tests

**Comment by chrisjsewell** [comment]
> have you checked that when skipping the markers the test suite passes also without rabbitmq being online?

Oh yeh, that's how I identified them all; using my trusty `.docker/docker-rabbitmq.yml` 😉

**Review by ltalirz — APPROVED** [review]
thanks!

**Pull request merged**
