### PR TITLE
Make `postgres_cluster` and `config_psql_dos` fixtures configurable

### PR DESCRIPTION
**Pull request by sphuber**
The `postgres_cluster` and `config_psql_dos` fixtures are made available publicly in order to help plugin packages with unit testing. Particularly, these fixtures should make it easy to generate test profiles using the `core.psql_dos` storage plugin, generating the postgres database in a test cluster that is created on-the-fly.

The problem was that the interface did not actually allow to configure anything, such as the database name, but this was hardcoded. This would work fine in case it was used just once, but the fixtures could not be used to create a second profile, as the database name would already exist.

The `postgres_cluster` fixture is turned into a factory, allowing the database name, username and password to be customized. The unbound method `create_database` is added to the `PGTest` instance that it returns to easily create a new database.

The `config_psql_dos` fixture now actually forwards the relevant part of the `custom_configuration` to the `postgres_cluster.create_database` call.

Finally, the `aiida_profile_factory` fixture factory now makes the `custom_configuration` argument actually optional, as originally was intended.

### CODE REVIEW

**Comment by sphuber** [comment]
@unkcpz would you care to have a look please?

**Review by unkcpz — APPROVED** [review]
Thanks @sphuber. The changes looks all good.

**Comment by unkcpz** [comment]
When I review the PR, it reminds me a warning exception in AiiDAlab test, I can confirm it comes from the `pytest_fixture` and from `aiida_profile`. Maybe not related to the PR but I assume you have expertise to spot why it happened:

It is a dummy test in `aiidalab-widgets-base` only load the `aiida.manage.tests.pytest_fixtures`. It appears after we turn on pytest option of show warning as error. 

After I comment out the `aiida_profile` fixture, this warning disappeared.

```
tests/test_a.py::test_a Exception ignored in: <_io.FileIO name=6 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/jyu/micromamba/envs/aiidalab-dev/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedReader name=6>
Exception ignored in: <_io.FileIO name=8 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/jyu/micromamba/envs/aiidalab-dev/lib/python3.9/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedReader name=8>
```

**Comment by sphuber** [comment]
> When I review the PR, it reminds me a warning exception in AiiDAlab test, I can confirm it comes from the `pytest_fixture` and from `aiida_profile`. Maybe not related to the PR but I assume you have expertise to spot why it happened

I have seen these warnings before as well, but haven't had the time to investigate it yet. The `aiida_profile` fixture does depend on some other fixtures that create temporary files, for example for the `config.json` it creates, and these may not be properly cleaned up. But I would have to look in depth. Don't have an immediate hunch now what it might be.

**Pull request merged**
