### PR TITLE
DevOps: devcontainer update to use new docker stack

### PR DESCRIPTION
**Pull request by unkcpz**
The effect can be see from https://github.com/unkcpz/aiida-core/tree/fix/xx/devcontainer-new-docker

### CODE REVIEW

**Comment by unkcpz** [comment]
After this one, can we make a patch release with all new docker stack implementations (https://github.com/aiidateam/aiida-core/pull/6131, https://github.com/aiidateam/aiida-core/pull/6129, https://github.com/aiidateam/aiida-core/pull/6127, https://github.com/aiidateam/aiida-core/pull/6119, https://github.com/aiidateam/aiida-core/pull/6080)?  @sphuber

**Review by sphuber — APPROVED** [review]
Thanks @unkcpz

**Comment by sphuber** [comment]
> After this one, can we make a patch release with all new docker stack implementations (#6131, #6129, #6127, #6119, #6080)? @sphuber

I think we are getting close to being able to release v2.5.0. Would it be ok to wait a bit and ship it with this minor release?

**Comment by unkcpz** [comment]
The only concern I have is these four lines haven't been run before and they are supposed to give the right tag to the image when making the release to dockerhub.

https://github.com/aiidateam/aiida-core/blob/61828e26ad34ed592e8528ca58d68c1175afb926/.github/workflows/docker-push.yml#L67-L70

Can you give it double-check the matching pattern is all good? I am totally fine with `v2.5.0`.

**Comment by sphuber** [comment]
@unkcpz I am not familiar with the syntax for those acxtions, but our tags do follow the pattern `pattern=v(\d+\.\d+.\d+)`, e.g., `v2.5.1`. So think that looks okay

**Pull request merged**
