### PR TITLE
drop support for python 3.6

### LINKED ISSUE #4691: Drop support for Python 3.6.
According to our [support table](https://www.aiida.net/download/), support for Python 3.6 is dropped.

### PR DESCRIPTION
**Pull request by ltalirz**
fix #4691 

Following our support table, we drop python 3.6 support.

### CODE REVIEW

**Review by chrisjsewell — APPROVED** [review]

**Comment by ltalirz** [comment]
pinging @aiidateam/dependency-manager

**Review by csadorf — CHANGES_REQUESTED** [review]
Please remove file `requirements/requirements-py-3.6.txt` otherwise good! 👍

**Comment by ltalirz** [comment]
thanks, done!

**Review by csadorf — APPROVED** [review]

**Comment by chrisjsewell** [comment]
@ramirezfranciscof don't merge PRs with failing checks

**Pull request merged**
