### PR TITLE
Docs: Add "Sharing data" to "How to work with data"

### LINKED ISSUE #3998: Docs: How to share data

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #3998

Do not move over the technical aspects, i.e., the sections discussing the export archive format and the JSON files.

This is now related to #4458.

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
Thanks for the work @CasperWA !

For the reviewer: here is a checklist of some of the relevant stuff to verify for your convenience (use it as you please).
- [ ] Pull the PR and check that it can locally compile correctly.
- [ ] There are no format-display issues (unrecognized code blocks, broken links, etc.).
- [ ] All links that must remain temporarily unresolved have been reported in issue #4120.

When checking the formatting, make sure that the [guidelines](https://github.com/aiidateam/aiida-core/wiki/Writing-documentation) are being followed. The most relevant ones:
- There is only one sentence per line and otherwise no manual line wrapping.
- All headers are in sentence-case ('Entry points' instead of 'Entry Points')
- Paragraphs are separated by a single line (not more).
- Code blocks: 'bash' and 'python' for scripts, 'console' and 'ipython' for interactive sessions and verdi shell ('$' for normal bash user, '#' for root).

**Comment by ltalirz** [comment]
After discussing with @CasperWA , I will pull in these changes into a new top level "How to share data" section

**Comment by giovannipizzi** [comment]
As a comment, I would be very careful of only moving part of an old page - i.e., if you really don't want to move the internals, then at least make 100% sure it's clear what part of the old page is still not migrated, or we'll just "lose" it.
If it's easy to just copy-paste and adapt the style to the new docs, I'd suggest to do it at the same time, if possible

**Comment by giovannipizzi** [comment]
Sorry - after discussion with @sphuber I realised the old content is still in the source code, unlinked. The important thing to remember is to delete the corresponding text from the old docs when we add the new docs, so at the end we can easily see what has still been left out from the new docs.
Also,  I realised that the parts on the `internals` have been done by Francisco in #4467

**Pull request closed without merging**
