### PR TITLE
Clean up top level directory of repository

### LINKED ISSUE #3730: cleanup of top-level dir
Some ideas for reducing files at the top level

 - [x] move `conftest.py` to `tests`
 - [x] ~~remove `bin/runaiida` (is this needed?)~~ Move to `console_scripts` in `setup.json`
 - [x] remove `examples/`  (@sphuber should these go to the docs?)
 - [x] remove `utils/plugin_tpl` (ok, that's not top-level but seems outdated)

### PR DESCRIPTION
**Pull request by ltalirz**
fix #3730

### CODE REVIEW

**Comment by ltalirz** [comment]
@sphuber despite the current issues with CI, I believe the tests actually pass (see 2nd-to-last commit) and the coverage should not be decreasing.

**Comment by sphuber** [comment]
The tests are failing because it is still trying to install the `bin/runaiida` script during package setup:
```
error: [Errno 2] No such file or directory: '/home/runner/work/aiida-core/aiida-core/bin/runaiida'
```
You should remove the `scripts` key from the `setup.json` as well. Then we should really test that in a completely new environment the `#!/usr/bin/env runaiida` shebang still works exactly the same

**Comment by ltalirz** [comment]
> The tests are failing because it is still trying to install the bin/runaiida script during package setup:

Ah... ;-) Thanks, fixed!

> Then we should really test that in a completely new environment the #!/usr/bin/env runaiida shebang still works exactly the same

I checked it on my side and it worked. Please check as well.

**Comment by sphuber** [comment]
@ltalirz I also verified that the new `runaiida` still works. The pre-commit is now failing. These are the lines that you addressed in another PR, that we were wondering how they came there. I guess you must have mixed those files from this PR into the other one. Anyway, should be an easy fix. Once that is done I will merge this. Thanks!

**Comment by ltalirz** [comment]
>  These are the lines that you addressed in another PR, that we were wondering how they came there.

Indeed, this is what I introduced [here](https://github.com/aiidateam/aiida-core/pull/3875#discussion_r399698549).
I don't see these changes anymore in the final squashed commit of yours in https://github.com/aiidateam/aiida-core/pull/3875

Very strange... how is it possible that the tests did pass for you while they did not for me?

Anyhow, I will re-introduce the changes here.

**Comment by ltalirz** [comment]
Just to follow up on this, here are links to recent github actions runs:
 * [passed](https://github.com/aiidateam/aiida-core/runs/543814195) (despite the # pylint:disable comments missing)
 * [failed](https://github.com/aiidateam/aiida-core/runs/551894467) 

Looking at the python environment, the only differences are:
```
7c7
< Werkzeug-1.0.0
---
> Werkzeug-1.0.1
42c42
< django-2.2.11
---
> django-2.2.12
84c84
< nbformat-5.0.4
---
> nbformat-5.0.5
```
I don't think those have anything to do with it (also, it would be unclear why the pre-commit hooks worked, then broke, then worked again, then broke again).

**Comment by sphuber** [comment]
The tests are failing for SqlAlchemy. They seem to be hanging at `tests/backends/aiida_sqlalchemy/test_generic.py`. I have already restarted them once but they timed out at the same point. I am not sure what is going on

**Comment by ltalirz** [comment]
I can reproduce the issue locally using
```
$ AIIDA_TEST_BACKEND=sqlalchemy pytest tests/backends/aiida_sqlalchemy
```

Actually, the tests in `test_generic.py` run fine for me:

```
 $ AIIDA_TEST_BACKEND=sqlalchemy pytest tests/backends/aiida_sqlalchemy/test_generic.py
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.7.1, pytest-5.3.4, py-1.8.0, pluggy-0.13.1
rootdir: /Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq, inifile: pytest.ini
plugins: timeout-1.3.4, datadir-1.3.1, cov-2.8.1
collected 4 items

tests/backends/aiida_sqlalchemy/test_generic.py ....                                                                                                                                                                                   [100%]

============================================================================================================= 4 passed in 8.17s ==============================================================================================================
```
For me it's hanging at `tests/backends/aiida_sqlalchemy/test_migrations.py`
```
$ AIIDA_TEST_BACKEND=sqlalchemy pytest tests/backends/aiida_sqlalchemy
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.7.1, pytest-5.3.4, py-1.8.0, pluggy-0.13.1
rootdir: /Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq, inifile: pytest.ini
plugins: timeout-1.3.4, datadir-1.3.1, cov-2.8.1
collected 39 items

tests/backends/aiida_sqlalchemy/test_generic.py ....                                                                                                                                                                                   [ 10%]
tests/backends/aiida_sqlalchemy/test_migrations.py ^C
```

**Comment by ltalirz** [comment]
It actually hangs here:
https://github.com/aiidateam/aiida-core/blob/6ce6cd48907bd3976e50e260e8b609d74c9cf692/tests/backends/aiida_sqlalchemy/test_migrations.py#L67

Is it a problem if a user is already stored in the DB at this point? 
How do the migration tests work?

Perhaps @giovannipizzi could also comment

**Comment by giovannipizzi** [comment]
I might be fixing this in #3650

**Comment by ltalirz** [comment]
Yeah, I introduced this fixture because it was necessary.

There are two options for this PR - either we fix the underlying issue or we keep the "pytest tests" separate from the rest (it's not strictly about cleaning up the top-level of the directory).

Note, however, that we will likely run into this issue again soon, namely when people start to use pytest fixtures in the test suite more actively.

**Comment by sphuber** [comment]
I am just playing around with this now and it indeed seems a problem in the two different ways be currently setup and clean the database. By adding the fixture, we ensure that a user instance is created for the `pytest` tests, however, this interferes with the setup of the `AiidaTestCase` tests and particularly with the migrations. Given that already the moving is really a bit outside of the scope of this PR, I would vote to remove it for now and continue in a separate issue.

**Comment by ltalirz** [comment]
Fine with me - can you take care of it?

**Comment by sphuber** [comment]
> Fine with me - can you take care of it?

done

**Comment by ltalirz** [comment]
Looks good to me - you'll need to approve yourself ;-)

**Pull request merged**
