### PR TITLE
Fix: release signal handlers after run execution

### PR DESCRIPTION
**Pull request by chrisjsewell**
After a process has executed (when running rather than submitting),
return the signal handlers to their original state.

This fixes an issue whereby using `CTRL-C` after a process has run still calls the `process.kill` (https://github.com/aiidateam/aiida-core/issues/4649#issuecomment-767683215).
It also is a step towards fixing #4603, releasing the `kill_process` function's reference to the process.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
grr, pytest failure is some unrelated (transient?) error:

```
>           raise exception_to_raise('\n'.join(messages))
E           tests.transports.test_all_plugins.run_for_all_plugins.<locals>.CollectiveException: *** At least one test for a subplugin failed. See below ***
E           
E           *** [For plugin <module 'tests.transports.test_ssh' from '/home/runner/work/aiida-core/aiida-core/tests/transports/test_ssh.py'>]: Exception 'ValueError': ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])
E           Traceback (most recent call last):
E             File "/home/runner/work/aiida-core/aiida-core/tests/transports/test_all_plugins.py", line 89, in test_all_plugins
E               actual_test_method(self, custom_transport)
E             File "/home/runner/work/aiida-core/aiida-core/tests/transports/test_all_plugins.py", line 120, in test_is_open
E               with custom_transport:
E             File "/home/runner/work/aiida-core/aiida-core/aiida/transports/transport.py", line 125, in __enter__
E               self.open()
E             File "/home/runner/work/aiida-core/aiida-core/aiida/transports/plugins/ssh.py", line 437, in open
E               self._client.connect(self._machine, **connection_arguments)
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/client.py", line 446, in connect
E               passphrase,
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/client.py", line 735, in _auth
E               filename, pkey_class, passphrase
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/client.py", line 586, in _key_from_filepath
E               key = klass.from_private_key_file(key_path, password)
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
E               key = cls(filename=filename, ***
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/rsakey.py", line 55, in __init__
E               self._from_private_key_file(filename, password)
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/rsakey.py", line 176, in _from_private_key_file
E               self._decode_key(data)
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/paramiko/rsakey.py", line 202, in _decode_key
E               ).private_key(default_backend())
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 311, in private_key
E               return backend.load_rsa_private_numbers(self)
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 628, in load_rsa_private_numbers
E               return _RSAPrivateKey(self, rsa_cdata, evp_pkey)
E             File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 316, in __init__
E               raise ValueError("Invalid private key", errors)
E           ValueError: ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])
```

**Comment by ltalirz** [comment]
Thanks @chrisjsewell  - if you repeat your experiment from https://github.com/aiidateam/aiida-core/issues/4603#issuecomment-767646196 does this now result in the process reference being released?

**Comment by chrisjsewell** [comment]
> does this now result in the process reference being released

Yes it does 👍 (only for this particular reference, still other references to address)

**Review by sphuber — APPROVED** [review]
Thanks @chrisjsewell . This looks good to merge

**Pull request merged**
