### PR TITLE
Fix `ZeroDivisionError` in worker slots check

### LINKED ISSUE #4512: ZeroDivisionError: percent_load = (active_slots / available_slots)
NB for a severely overloaded environment (_e.g._ all the Postgres `max_connections` are busy) this place produces an error:

https://github.com/aiidateam/aiida-core/blob/33c9f41d029a22640646be295b9316c533685b19/aiida/cmdline/utils/common.py#L509

### PR DESCRIPTION
**Pull request by chrisjsewell**
closes #4512

### CODE REVIEW

**Comment by chrisjsewell** [comment]
if someone could just give this the seal of approval 😄

**Review by ltalirz — APPROVED** [review]
thanks @chrisjsewell , that seems an obvious fix.

I'd also say that `percent_load` is a misnomer here; `load_ratio` (or just `load`) would be better but I leave it up to you whether you want to fix this as well.

**Comment by chrisjsewell** [comment]
> but I leave it up to you whether you want to fix this as well.

Cheers, nah can't be bothered to wait for the tests again lol

**Comment by chrisjsewell** [comment]
hmm I hope there is not an issue with jenkins

**Comment by ltalirz** [comment]
> hmm I hope there is not an issue with jenkins

In any case, it has already passed on the PR, so you can merge

**Comment by chrisjsewell** [comment]
seems ok but just not being reported back:

image

**Pull request merged**
