### PR TITLE
📚 DOCS: Replace sphinx-panels with sphinx-design

### PR DESCRIPTION
**Pull request by chrisjsewell**
sphinx-panels is deprecated,
see: https://sphinx-design.readthedocs.io/en/furo-theme/get_started.html#migrating-from-sphinx-panels

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Also tidies up the `conf.py` a little

**Review by sphuber — COMMENTED** [review]
It looks like the content of the panels on the front page is no longer centered and there is less margin. I personally prefer the current style over the one of this PR. Is it possible to keep that? Also, it seems the title "Welcome to AiiDA's documentation!" is gone. Was this on purpose? Ok to change the title but removing it completely is maybe not great

**Comment by sphuber** [comment]
Pretty good, cheers. Just noticed the following though:

- Old title `Welcome to AiiDA's documentation!` is still missing, but it is still in the landing page source. Seems like it just isn't getting rendered. Might as well get rid of it then? I am fine with the new layout just having `AiiDA` as title.
- The old panels have a slightly different color and a bigger drop-shadow, making them stand out more. Can we have keep the older styling?
- If possible would be good to remove the horizontal line dividing the panel in two, between the text paragraph and the button "To the ..."
- Padding could still be a bit larger

**Comment by chrisjsewell** [comment]
> Seems like it just isn't getting rendered. Might as well get rid of it then?

Yep little bit of sphinx-design magic 😉: https://sphinx-design.readthedocs.io/en/furo-theme/get_started.html#configuration
(you can't get rid of it, because of the docutils AST structure)

**Comment by chrisjsewell** [comment]
> The old panels have a slightly different color and a bigger drop-shadow
> Padding could still be a bit larger

I've increased the shadow (I would note, we decided with theme designers to specifically reduce the default for this: https://github.com/executablebooks/sphinx-design/issues/6#issuecomment-886527131),
plus also removed the bold of the card titles.

IMO the padding is now equivalent to the old style:

image

image

> If possible would be good to remove the horizontal line dividing the panel in two,

Don't think there is an easy way I'm afraid, I'll look at this in sphinx-design at a later date

**Pull request merged**
