### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ltalirz**
To the best of my knowledge, we haven't had issues with inappropriate conduct so far (others may know more), but if we look forward, organisations like [numfocus](numfocus.org) require projects and their members to conduct themselves appropriately - similar things may apply for other organisations.

The "Contributor Covenant Code of Conduct" is widely used, particularly on github - @sphuber @giovannipizzi let me know in case you find anything off.

### CODE REVIEW

**Comment by sphuber** [comment]
Where did you get the template from?

**Comment by ltalirz** [comment]
It's provided by Github

**Comment by sphuber** [comment]
does the `aiidateam@gmail.com` address exist? And does this file need to be included in the `MANIFEST.in` for it to be considered valid by organizations like numfocus?

**Comment by ltalirz** [comment]
> does the aiidateam@gmail.com address exist?

It does but I just realized that we use `developers@aiida.net` in the `setup.json`. @giovannipizzi Does anybody monitor this email address?

> And does this file need to be included in the MANIFEST.in for it to be considered valid by organizations like numfocus?

Good point, I'll check. Maybe it's not necessary since this is really about how managing contributions, i.e. what matters is that it is visible where contributions are happening.

**Comment by ltalirz** [comment]
> And does this file need to be included in the MANIFEST.in for it to be considered valid by organizations like numfocus?

Ok, looking at what other projects do, this does not seem to be necessary.

**Comment by giovannipizzi** [comment]
I would go for developers@aiida.net - for the rest it looks fine

**Comment by sphuber** [comment]
I was looking around at other popular packages and noticed that `numpy` does not have a CoC: https://github.com/numpy/numpy/community
Yet they are powered by numfocus. I thought you said having a CoC is required?

**Comment by ltalirz** [comment]
It is required, and they do have it (just not as part of the repository)
https://numpy.org/devdocs/dev/conduct/code_of_conduct.html

**Pull request merged**
