### PR TITLE
♻️ REFACTOR: Move to sqlachemy 1.4 (and v2 API)

### PR DESCRIPTION
**Pull request by chrisjsewell**
This PR is intended to update our use of sqlalchemy to the 2.0 API, which is supported by v1.4: https://docs.sqlalchemy.org/en/14/glossary.html#term-1

(note this currently builds on #5063)

### CODE REVIEW

**Comment by chrisjsewell** [comment]
cc @sphuber, in case you tried any of this in #4855

**Comment by chrisjsewell** [comment]
this is the query before/after `self._raw_columns.pop(0)`

```
SELECT db_dbnode_1.id, db_dbnode_1.uuid, db_dbnode_1.node_type, db_dbnode_1.process_type, db_dbnode_1.label, db_dbnode_1.description, db_dbnode_1.ctime, db_dbnode_1.mtime, db_dbnode_1.attributes, db_dbnode_1.extras, db_dbnode_1.repository_metadata, db_dbnode_1.user_id, db_dbnode_1.dbcomputer_id, db_dbnode_2.id AS id_1, db_dbnode_2.uuid AS uuid_1, db_dbnode_2.node_type AS node_type_1, db_dbnode_2.process_type AS process_type_1, db_dbnode_2.label AS label_1, db_dbnode_2.description AS description_1, db_dbnode_2.ctime AS ctime_1, db_dbnode_2.mtime AS mtime_1, db_dbnode_2.attributes AS attributes_1, db_dbnode_2.extras AS extras_1, db_dbnode_2.repository_metadata AS repository_metadata_1, db_dbnode_2.user_id AS user_id_1, db_dbnode_2.dbcomputer_id AS dbcomputer_id_1 
FROM db_dbnode AS db_dbnode_1 JOIN db_dblink AS db_dblink_1 ON db_dblink_1.input_id = db_dbnode_1.id JOIN db_dbnode AS db_dbnode_2 ON db_dblink_1.output_id = db_dbnode_2.id 
WHERE CAST(db_dbnode_1.node_type AS VARCHAR) LIKE 'data.%%' AND CAST(db_dbnode_2.node_type AS VARCHAR) LIKE 'data.%%'
---
SELECT db_dbnode_1.id, db_dbnode_1.uuid, db_dbnode_1.node_type, db_dbnode_1.process_type, db_dbnode_1.label, db_dbnode_1.description, db_dbnode_1.ctime, db_dbnode_1.mtime, db_dbnode_1.attributes, db_dbnode_1.extras, db_dbnode_1.repository_metadata, db_dbnode_1.user_id, db_dbnode_1.dbcomputer_id 
FROM db_dbnode AS db_dbnode_2, db_dbnode AS db_dbnode_1 JOIN db_dblink AS db_dblink_1 ON db_dblink_1.input_id = db_dbnode_2.id JOIN db_dbnode AS db_dbnode_1 ON db_dblink_1.output_id = db_dbnode_1.id 
WHERE CAST(db_dbnode_2.node_type AS VARCHAR) LIKE 'data.%%' AND CAST(db_dbnode_1.node_type AS VARCHAR) LIKE 'data.%%'
SELECT db_dbnode_1.id AS db_dbnode_1_id, db_dbnode_1.uuid AS db_dbnode_1_uuid, db_dbnode_1.node_type AS db_dbnode_1_node_type, db_dbnode_1.process_type AS db_dbnode_1_process_type, db_dbnode_1.label AS db_dbnode_1_label, db_dbnode_1.description AS db_dbnode_1_description, db_dbnode_1.ctime AS db_dbnode_1_ctime, db_dbnode_1.mtime AS db_dbnode_1_mtime, db_dbnode_1.attributes AS db_dbnode_1_attributes, db_dbnode_1.extras AS db_dbnode_1_extras, db_dbnode_1.repository_metadata AS db_dbnode_1_repository_metadata, db_dbnode_1.user_id AS db_dbnode_1_user_id, db_dbnode_1.dbcomputer_id AS db_dbnode_1_dbcomputer_id 
FROM db_dbnode AS db_dbnode_2, db_dbnode AS db_dbnode_1 JOIN db_dblink AS db_dblink_1 ON db_dblink_1.input_id = db_dbnode_2.id JOIN db_dbnode AS db_dbnode_1 ON db_dblink_1.output_id = db_dbnode_1.id 
WHERE CAST(db_dbnode_2.node_type AS VARCHAR) LIKE %(param_1)s AND CAST(db_dbnode_1.node_type AS VARCHAR) LIKE %(param_2)s
---
```

**Comment by sphuber** [comment]
> cc @sphuber, in case you tried any of this in #4855

I remember looking at this, but mostly that the whole logic around the private `_raw_columns` attribute had changed. I thought it completely changed structure and remember having to get rid of it completely. Fact that you are still using it seems to suggest I am misremembering though :D

**Comment by chrisjsewell** [comment]
> Fact that you are still using it seems to suggest I am misremembering though

well, as per the issue above, I don't know if I can actually get it to work, and its obviously not great to be accessing private attributes anyway.
Going to look through the `_build` method in more detail, and think if there's a better way, rather than having to start hacking into the sqlalchemy internals

**Comment by chrisjsewell** [comment]
Note some other issues to look into closing while I'm focussing on the querybuilder:

- [ ] #3844
- [ ] #4856
- [ ] #3845 
- [ ] #4659
- [ ] #4992
- [ ] #3755
- [ ] #4502
- [ ] #4041 
- [ ] #4327
- [ ] #4305
- [ ] #3946
- [ ] #3852
- [ ] #1389
- [ ] #2577 
- [ ] #2196
- [ ] #2475
- [ ] #3082
- [ ] #3564
- [ ] #3460
- [ ] #3420
- [ ] #3230
- [ ] #3161

**Comment by chrisjsewell** [comment]
Note:

        # Note: according to https://github.com/sqlalchemy/sqlalchemy/commit/0d1efeec475621b5c2c2aca0632b02edef54c1a6
        # automatic uniquing of rows is turned off for the new 2.0 style of ORM querying,
        # so this sqlalchemy < 1.4 hack is no longer necessary
        # self._query._has_mapper_entities = False

**Comment by chrisjsewell** [comment]
superceded by #5103

**Pull request closed without merging**
