### PR TITLE
Release/2.0.4

### PR DESCRIPTION
**Pull request by sphuber**

### CODE REVIEW

**Comment by chrisjsewell** [comment]
You might wanna wait for  #5654

**Comment by sphuber** [comment]
> You might wanna wait for #5654

Good timing, would indeed like to get that one in.

**Comment by sphuber** [comment]
@chrisjsewell updated the branch two include your two recent fixes. Should be ready for review now.

**Comment by chrisjsewell** [comment]
first you can look at  #5658 😉

**Pull request merged**
